<div class="main_courseboard">
<div class="courseboard_left dual-panel">
	<table cellpadding="0" cellspacing="0" width="100%" border="0" style="width:100%;">
       <thead>
        <tr class="row-0">
        <th class="top_td_bg">
        <span class="node-circle node-white-circle-expanded"> N </span>
        Course</th>
   <th class="top_td_bg ExcelTableFormationCol add"><span class="node-circle node-white-circle-expanded"> N </span><span class="role_text">Role</span>
  <i class="fa fa-angle-down roledrop add-phase-segment"></i>
      <div class="add-col-wrap add-colums"  >
            <ul class="dropdown-menu show-1" >
              <li role="presentation"> 
              <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Entropolis </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target="#Seriespoup"> <a  class="popupPhaseClass">
                    <div class="node-circle node-white-circle">N</div>
                    Founder </a> </li>
                  <li class="add-operation-series"> <a class="" href="#">
                    <div class="node-circle node-white-circle">N</div>
                    CTO </a> </li>
                    <li data-toggle="modal" data-target="#Seriespoup"> <a  class="popupPhaseClass">
                    <div class="node-circle node-white-circle">N</div>
                    Product Manager </a> </li>
                  <li class="add-operation-series"> <a class="" href="#">
                    <div class="node-circle node-white-circle">N</div>
                    Sage </a> </li>
                </ul>
              </li>
            </ul>
      </div>
      
      
      <!--<i class="fa fa-plus add add-phase-segment"></i>
      <div class="add-col-wrap add-colums"  >
            <ul class="dropdown-menu show-5" >
              <li class="no-bg "> <a class="add-left disabled">
              <div class=" node-circle node-white-circle-expanded">N</div>
              Add left </a>
                <ul class="sub-item">
                  <li class="no-bg disabled"> <a class="add-left-col">
                    <div class="node-circle node-white-circle">N</div>
                    Phase </a> </li>
                  <li class="no-bg disabled"> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Operation </a> </li>
                </ul>
              </li>
              <li role="presentation"> 
              <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add right </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target="#Seriespoup"> <a  class="popupPhaseClass">
                    <div class="node-circle node-white-circle">N</div>
                    Phase </a> </li>
                  <li class="add-operation-series"> <a class="" href="#">
                    <div class="node-circle node-white-circle">N</div>
                    Operation </a> </li>
                </ul>
              </li>
            </ul>
      </div>-->
    </th>
        <th class="top_td_bg">
        <span class="node-circle node-white-circle-expanded"> N </span>
        Draft</th>
      </tr>
       </thead>
 		<tbody>
        	 <tr>
              <td> <span class="node-circle node-green-circle-expanded"> N </span>Draft: Publish new Advice</td>
               <td>Entropis: Sage</td>
               <td><span>08/07/2015</span><a class="open-chat-modal"><i class="fa fa-comment cht_icon "></i></a></td>
              </tr>
               <tr>
              <td> <span class="node-circle node-white-circle-expanded"> N </span>Publish new Advice</td>
               <td>Entropis: Sage</td>
               <td><span>08/07/2015</span><a class="open-chat-modal"><i class="fa fa-comment cht_icon "></i></a></td>
              </tr>
               <tr>
              <td> <span class="node-circle node-white-circle-expanded"> N </span>Publish new Advice</td>
               <td>Entropis: Sage</td>
               <td><span>08/07/2015</span></td>
              </tr>
               <tr>
              <td> <span class="node-circle node-white-circle-expanded"> N </span>Publish new Advice</td>
               <td>Entropis: Sage</td>
               <td><span>08/07/2015</span></td>
              </tr>
               <tr>
              <td> <span class="node-circle node-white-circle-expanded"> N </span>Publish new Advice</td>
               <td>Entropis: Sage</td>
               <td><span>08/07/2015</span></td>
              </tr>
               <tr>
              <td> <span class="node-circle node-white-circle-expanded"> N </span>Publish new Advice</td>
               <td>Entropis: Sage</td>
               <td><span>08/07/2015</span><a class="open-chat-modal"><i class="fa fa-comment cht_icon "></i></a></td>
              </tr>
        </tbody>
</table>
</div>
<div class="courseboard_right dual-panel">
                       <div>
                            <!-- Nav tabs -->
                            <div>
                              <ul class="nav nav-tabs dialogue-tab courseboard_tab" role="tablist">
                               <li role="presentation"><a href="#form-tab" aria-controls="form-tab" role="tab" data-toggle="tab"><i class="tab-icon form_icon"></i><span>Form</span></a></li>
                                <li role="presentation"><a href="#plan-tab" aria-controls="plan-tab" role="tab" data-toggle="tab"><i class="tab-icon plan_icon"></i><span>Plan</span></a></li>
                                <li role="presentation" class="active"><a href="#index-tab" aria-controls="index-tab" role="tab" data-toggle="tab"><i class="tab-icon index_icon"></i><span>Index</span></a></li>
                                <li role="presentation"><a href="#document-tab" aria-controls="document-tab" role="tab" data-toggle="tab">
                                  <i class="tab-icon document_icon"></i><span>Document</span></a></li>
                               
                              </ul>
                            </div>
                            <!-- Tab panes -->
                            <div class="tab-content">
                              <div role="tabpanel" class="tab-pane active" id="form-tab">
                                 <div class="req-task-tree permission-table-wrap" id="center-screen">   
                                <div id="entr_center_content" class="class-bulider-section-modal">
                                    <div id="main">
                                        <div class="">
                                            <div class="">
                                                <section id="node-wrapper" class="clearfix">
                                                    <ol class="sortable ui-sortable">
                                                        <li id="firstNode" data-id="node-6" class="mjs-nestedSortable-expanded entrnode download-cashed mjs-nestedSortable-branch parent-node" data-type="node_role">
                                                            <div class="node-content clearfix">
                                                                <div class="node-left">
                                                                    <div data-id="node-6" class="node-circle node-white-circle-expanded node-green-circle-expanded">N</div>
                                                                    <span class="disclose"><span></span></span>
                                                                    <div class="node-head node-input"> 
                                                                        <span>Post Job</span> 
                                                                        <span class="node-input">
                                                                        <input type="hidden" class="node-title-text" name="title" value="Classes">
                                                                        <input type="hidden" class="caption-text" name="captionText" value="Classes">
                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="Pane 1">
                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                        </span> 
                                                                    </div>
                                                                </div>
                                                                <div class="node-right">
                                                                    <a id="classesDisplayPlus~6~Classes" class="action-move get-section-details"><span><i class="fa fa fa-plus"></i></span></a>
                                                                    <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a> 
                                                                    <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a> 
                                                                </div>
                                                            </div>
                                                            <ol class="classDisplaySortable">
                                                                <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-expanded parent-node">
                                                                    <ol>                                                                       
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed child-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Properties</span> 
                                                                                        <span class="node-input"> 
                                                                                        <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                                                        <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                                        </span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol></ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-expanded parent-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Oprations</span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol class="child-node">
                                                                                <li data-id="node-00" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                                                    <div class="node-content clearfix">
                                                                                        <div class="node-left isSorting_a">
                                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                                            <span class="disclose"><span></span></span>
                                                                                            <div class="node-head node-input"> 
                                                                                                <span>Properties</span> 
                                                                                                 
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="node-right"> 
                                                                                            <a class="action-move" onClick="addProperty(this);"><span><i class="fa fa fa-plus"></i></span></a>
                                                                                            <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                                            <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <ol></ol>
                                                                                </li>
                                                                            </ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed child-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Event</span> 
                                                                                        <span class="node-input"> 
                                                                                        <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                                                        <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                                        </span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol></ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed child-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Properties</span> 
                                                                                        <span class="node-input"> 
                                                                                        <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                                                        <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                                        </span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol></ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-expanded parent-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Oprations</span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol class="child-node">
                                                                                <li data-id="node-00" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                                                    <div class="node-content clearfix">
                                                                                        <div class="node-left isSorting_a">
                                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                                            <span class="disclose"><span></span></span>
                                                                                            <div class="node-head node-input"> 
                                                                                                <span>Properties</span> 
                                                                                                 
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="node-right"> 
                                                                                            <a class="action-move" onClick="addProperty(this);"><span><i class="fa fa fa-plus"></i></span></a>
                                                                                            <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                                            <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <ol></ol>
                                                                                </li>
                                                                            </ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed child-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Event</span> 
                                                                                        <span class="node-input"> 
                                                                                        <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                                                        <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                                        </span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol></ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed child-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Properties</span> 
                                                                                        <span class="node-input"> 
                                                                                        <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                                                        <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                                        </span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol></ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-expanded parent-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Oprations</span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol class="child-node">
                                                                                <li data-id="node-00" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                                                    <div class="node-content clearfix">
                                                                                        <div class="node-left isSorting_a">
                                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                                            <span class="disclose"><span></span></span>
                                                                                            <div class="node-head node-input"> 
                                                                                                <span>Properties</span> 
                                                                                                 
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="node-right"> 
                                                                                            <a class="action-move" onClick="addProperty(this);"><span><i class="fa fa fa-plus"></i></span></a>
                                                                                            <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                                            <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <ol></ol>
                                                                                </li>
                                                                            </ol>
                                                                        </li>
                                                                        <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed child-node">
                                                                            <div class="node-content clearfix">
                                                                                <div class="node-left">
                                                                                    <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                                                    <span class="disclose"><span></span></span>
                                                                                    <div class="node-head node-input"> 
                                                                                        <span>Event</span> 
                                                                                        <span class="node-input"> 
                                                                                        <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                                                        <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                                                        <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                                        <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                                        <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                                        <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                                        <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                                        <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                                        </span> 
                                                                                    </div>
                                                                                </div>
                                                                                <div class="node-right"></div>
                                                                            </div>
                                                                            <ol></ol>
                                                                        </li>
                                                                    </ol>
                                                                </li>
                                                            </ol>
                                                            <ol class="yes-no">
                                                                <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed parent-node ">
                                                                    <div class="node-content clearfix interaction-yes">
                                                                        <div class="node-left">
                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                            <span class="disclose"><span></span></span>
                                                                            <div class="node-head node-input"> 
                                                                                <span>Yes</span> 
                                                                            </div>
                                                                        </div>                                                                
                                                                    </div>

                                                                </li>
                                                                 <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed parent-node ">
                                                                    <div class="node-content clearfix interaction-no ">
                                                                        <div class="node-left">
                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                            <span class="disclose"><span></span></span>
                                                                            <div class="node-head node-input"> 
                                                                                <span>No</span> 
                                                                            </div>
                                                                        </div>                                                                
                                                                    </div>

                                                                </li>
                                                            </ol>
                                                           
                                                            <ol class="saved">
                                                                <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed parent-node">
                                                                    <div class="node-content clearfix">
                                                                        <div class="node-left">
                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                            <span class="disclose"><span></span></span>
                                                                            <div class="node-head node-input"> 
                                                                                <span>Save</span> 
                                                                            </div>
                                                                        </div>                                                                
                                                                    </div>

                                                                </li>
                                                                 <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed parent-node">
                                                                    <div class="node-content clearfix">
                                                                        <div class="node-left">
                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                            <span class="disclose"><span></span></span>
                                                                            <div class="node-head node-input"> 
                                                                                <span>Save As</span> 
                                                                            </div>
                                                                        </div>                                                                
                                                                    </div>

                                                                </li>
                                                                <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed parent-node">
                                                                    <div class="node-content clearfix">
                                                                        <div class="node-left">
                                                                            <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                            <span class="disclose"><span></span></span>
                                                                            <div class="node-head node-input"> 
                                                                                <span>Cancel</span> 
                                                                            </div>
                                                                        </div>                                                                
                                                                    </div>

                                                                </li>
                                                            </ol>
                                                    </ol>
                                                </section>
                                            </div>
                                            <div class="nano-pane" style="display: none;">
                                                <div class="nano-slider" style="height: 495px; transform: translate(0px, 0px);"></div>
                                            </div>
                                        </div>
                                    </div>                                   
                                </div>
                            </div>
                              </div>
                              <div role="tabpanel" class="tab-pane" id="plan-tab">
                               <i><img src="public/img/plan_bg.jpg" class="img-responsive" /></i>
                              </div>
                              <div role="tabpanel" class="tab-pane" id="index-tab">
                                 index
                              </div>
                              <div role="tabpanel" class="tab-pane" id="document-tab">
                                 document
                              </div>
                            </div>
                          </div>
</div>
<div class="clearfix"></div>
</div>