// view add/edit form html -----------------------------
<div id="content_scroler_div" class="customScroll mid-section-HT" >
  <!-- Show the notification/alert to user -->
    <div class="notification-wrap"><div id="notification-row" class="notification-row" style="display:none"><p></p></div></div>
  <!-- End of show the notification/alert to user -->
  <div class="listing-content-wrap" >
  <form class="form-horizontal" id="<FORM_ID></FORM_ID>" name="<FORM_ID></FORM_ID>" action="post">
      <div>
        <a class="list-title-heading" data-toggle="collapse" href="#editGeneral" aria-expanded="false" aria-controls="editGeneral">
            <i class="fa fa-angle-down"></i>GENERAL
        </a>
        <div class="collapse in" id="editGeneral">
          <div class="list-detail-section">            
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input autogenerated"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group lookup-btn-wrap">
                  <div class="col-md-12">
                      <button type="button"  class="btn btn-black btn-sm j_my_dealLookup_open" onclick="fiLookup(this)">Deal Lookup</button>
                      <button type="button"  class="btn btn-black btn-sm disabled" onclick="searchFi(this);">Refresh Deal</button>
                  </div>
              </div>
          </div>
        </div>
      </div>
      <div>
        <a class="list-title-heading" data-toggle="collapse" href="#editDeal" aria-expanded="false" aria-controls="editDeal">
            <i class="fa fa-angle-down"></i>DEAL
        </a>
        <div class="collapse in" id="editDeal">
          <div class="list-detail-section">
              <div class="form-group hide">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8 input-btn-group input-btn-icon input-icon">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input button_for_deal salesQouteInput" ></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                    <a class="j_my_search_open inactive" onclick="openStockFlyout(this);" data-params="SALES"><i class="prs-icon view"></i></a>
                    <button type="button" id="sales_quote_button" class="btn btn-black btn-sm deal_flyout search_not_open" onclick="searchSalesQuote(this);">Select</button>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8 input-btn-group input-btn-icon">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input button_for_deal fiQuoteInput" ></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                    <a class="j_my_search_open inactive" onclick="openStockFlyout(this);" data-params="FI"><i class="prs-icon view"></i></a>
                    <!-- <button type="button" id="fi_quote_button" class="btn btn-black btn-sm deal_flyout search_not_open" onclick="searchFi(this);">Select</button>-->
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group hide">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group hide">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
                                  
          </div>
        </div>
      </div>
      <div>
        <a class="list-title-heading" data-toggle="collapse" href="#editBuyer" aria-expanded="false" aria-controls="editBuyer">
           <i class="fa fa-angle-down"></i>BUYER
        </a>
        <div class="collapse in" id="editBuyer">
          <div class="list-detail-section">  
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8 input-btn-group input-btn-icon input-icon">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input button_for_deal buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                    <a class="j_my_search_open inactive" onclick="openStockFlyout(this);" data-params="CUSTOMER"><i class="prs-icon view"></i></a>
                    <!-- <button type="button" id="customer_info_button" class="btn btn-black btn-sm deal_flyout search_not_open jq_search_open hide" onclick="searchCustomer(this);">Search</button> -->
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input buyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div>
        <a class="list-title-heading" data-toggle="collapse" href="#editCoBuyer" aria-expanded="false" aria-controls="editCoBuyer">
           <i class="fa fa-angle-down"></i>CO BUYER
        </a>
        <div class="collapse in" id="editCoBuyer">
          <div class="list-detail-section">  
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8 input-btn-group input-btn-icon input-icon">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                    <a class="j_my_search_open inactive" onclick="openStockFlyout(this);" data-params="COBUYER"><i class="prs-icon view"></i></a>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input coBuyerInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div>
        <a class="list-title-heading" data-toggle="collapse" href="#editVessel" aria-expanded="false" aria-controls="editVessel">
            <i class="fa fa-angle-down"></i>BOAT
        </a>
        <div class="collapse in" id="editVessel">
          <div class="list-detail-section">            
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8 input-btn-group input-btn-icon input-icon">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input button_for_deal boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                    <a class="j_my_search_open inactive" onclick="openStockFlyout(this);" data-params="STOCK"><i class="prs-icon view"></i></a>
                    <!-- <button type="button" id="unit_info_button" class="btn btn-black btn-sm deal_flyout search_not_open jq_search_open hide" onclick="searchStock(this);">Search</button> -->
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group hide">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input boatInput"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div class="hide">
        <a class="list-title-heading" data-toggle="collapse" href="#editRELATED" aria-expanded="false" aria-controls="editRELATED">
            <i class="fa fa-angle-down"></i>RELATED DETAILS
        </a>
        <div class="collapse in" id="editRELATED">
          <div class="list-detail-section">            
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input autogenerated"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>     
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>   
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-4 control-label form-label"><CLASS_PROPERTY_LABEL></CLASS_PROPERTY_LABEL></label>
                <div class="col-sm-8">
                    <CLASS_PROPERTY_USER_INPUT placeholder="false" class="form-control inline-input"></CLASS_PROPERTY_USER_INPUT>
                    <span class="list-view-detail hide"></span>
                </div>
              </div> 
          </div>
        </div>
      </div>
      <input type="hidden" value="<SUBMIT_FUNCTION></SUBMIT_FUNCTION>" id="id_detail_submit" name="id_detail_submit" />
      <input type="hidden" value="" id="id_detail_save_type" name="id_detail_save_type" />
      <input type="hidden" id="id_detail_instance_id" name="id_detail_instance_id" value="" />
  </form>
</div>
</div>

For Deal And Other Form
-------------------------
<script type="text/javascript">
  function submitFunc_NSnQQ1oYZi() {
    var flag1=true; var checkflag1=""; var temp1=true;
    var formId = "formId_L03HTQtr4I";
    var formElem = $("#formId_L03HTQtr4I:visible");
    if($(formElem).find("#id_detail_save_type").val() == 'P')
    {
      $(formElem).find(".validationCheck:visible").each(function(i,k){
          var data1 = $.trim($(this).val());
          var element1 = $(this);
          if (data1.indexOf("'") >= 0 || data1.indexOf('"') >= 0) { data1 = "~$~"; }
          if(flag1 == true){
              var fn1="";
              fn1 = $(this).attr("validate-data").split(";");
              var aa1=[];
              for(i=0;i<fn1.length;i++){
                aa1.push(fn1[i]);
              }
              aa1.toString();
              $(aa1).each(function(i,v){                                             
                  var newStr1 = v;
                  var valdata1 = data1;
                  if(newStr1.indexOf("pui_fun")>=0) {
                      var elementId = element1.attr("id");
                      var aaa1 = newStr1.replace("()","('"+elementId+"')");
                  } else {
                      if(valdata1 == ""){
                          var aaa1 = newStr1.replace("()","('')");
                      }else {
                          var aaa1 = newStr1.replace("()","('"+data1+"')");
                      }
                  }
                  checkflag1 = eval(aaa1);
                  if(checkflag1 == false){
                      temp1 = false;
                  }
              });
              if(temp1 == false){
                  flag1 = false;
              } else {
                  flag1 = true;
              }
          }
      });
    }
    if(flag1 == true)
    {  
      if(is_role_assoc != '1') { showFullLoader('content_loader'+form_container); }
      var filter_text = searchModule.getActiveMenuValue();
      var last_filter_id = $('.item-list').find('li.active').attr('id');
      var filter_prop_id = $('.item-list').find('li.active').attr('data-statusid');
      var col_head_prop_id = getColHeadPropertyId();
      var activeMenu = [searchModule.getActiveMenuValue(),searchModule.getActiveMenuDataId()];

      var form_data = new FormData(document.getElementById("formId_L03HTQtr4I"));
      form_data.append('action', 'single');
      form_data.append('col_head_prop_id', col_head_prop_id);
      form_data.append('list_setting_array', list_setting_array);
      form_data.append('list_node_id_array', list_node_id_array);
      form_data.append('list_head_array', list_head_array);
      form_data.append('activeMenu', activeMenu);
      form_data.append('login_user_id', login_user_id);
      form_data.append('login_role_id', login_role_id);
      form_data.append('emailLinks', JSON.stringify(all_settings['deal']['settings']['emailLinks']));
      var pId = [];
      $('.autogenerated:visible').each(function () {
          pId.push($(this).data('id'));
      });
      if(pId.length){
        form_data.append('autogenerated', pId);
      }
      
        $.ajax({
          type: "POST",
          url : "http://localhost/PUI/puidata/page_plugin/code.php",
          data: form_data,
          dataType: "json",
          async: true,
          enctype: "multipart/form-data",
          cache: false,
          contentType: false,
          processData: false,
          success:function(data){
              if(data.result == 0) {
                if (is_role_assoc == '1' && form_container == '_dashboard')
                {
                  instance_node_id_dashboard = data.data.node_id;
                  node_instance_id_dashboard = data.data.node_instance_id;
                  form_action_type = 'view';
                  getRolesOfPlugin('1');
                } 
                else if (is_role_assoc == '0' && form_container == '_dashboard')
                {
                    if(data.data.status == 'P')
                    { 
                      showFullLoader('full_page_loader');
                      GoToPageModule.setDealId(data.data.node_id);
                    }
                    instance_node_id_dashboard = '';
                    node_instance_id_dashboard = '';
                    $('.j_my_createDeal_close').trigger('click');
                }
                else
                {
                  if(typeof updateMenuCount === "function") {
                      updateMenuCount();
                  }
                  if(typeof updateActiveList === "function") {
                      updateActiveList(data.data.col_data, data.data.save_type,data.data.node_id,data.data.statusChange);
                  }
                }
              } else {
                  if(is_role_assoc != '1') { hideFullLoader('content_loader'+form_container); }else{hideFullLoader('content_loader'+form_container);}
                  if(data.Stock=="false") {
                    bootbox.alert(data.Stockmsg);
                    return false;
                  } 
                  if(data.Customer=="false") {
                    bootbox.alert(data.Customermsg);
                    return false;
                  } 
                  if(data.FiQuote=="false") {
                    bootbox.alert(data.FiQuotemsg);
                    return false;
                  } 
                  if(data.SalesQuote=="false") {
                    bootbox.alert(data.SalesQuotemsg);
                    return false;
                  } 
              }
          },
          complete: function(data) {
              if(data.result == 0) {
                $(".validationCheck").val("");
                //hideFullLoader('content_loader');
              }  
          },
          error: function(data) {

          }
        });
       
    }
  }
</script>

For Operation Form 
-------------------
<script type="text/javascript">
if(flag1 == true)
{  
      return formId;
}
</script>

For Deal section js code
<script type="text/javascript">
                
  function submitFunc_bCaPiEU5HF() {
    var flag1=true; var checkflag1=""; var temp1=true;
    var formId = "formId_ooYRyjGYeH";
    var formElem = $("#formId_ooYRyjGYeH:visible");
    if($(formElem).find("#id_detail_save_type").val() == 'P')
    {
      $(formElem).find(".validationCheck:visible").each(function(i,k){
          var data1 = $.trim($(this).val());
          var element1 = $(this);
          if (data1.indexOf("'") >= 0 || data1.indexOf('"') >= 0) { data1 = "~$~"; }
          if(flag1 == true){
              var fn1="";
              fn1 = $(this).attr("validate-data").split(";");
              var aa1=[];
              for(i=0;i<fn1.length;i++){
                aa1.push(fn1[i]);
              }
              aa1.toString();
              $(aa1).each(function(i,v){                                             
                  var newStr1 = v;
                  var valdata1 = data1;
                  if(newStr1.indexOf("pui_fun")>=0) {
                      var elementId = element1.attr("id");
                      var aaa1 = newStr1.replace("()","('"+elementId+"')");
                  } else {
                      if(valdata1 == ""){
                          var aaa1 = newStr1.replace("()","('')");
                      }else {
                          var aaa1 = newStr1.replace("()","('"+data1+"')");
                      }
                  }
                  checkflag1 = eval(aaa1);
                  if(checkflag1 == false){
                      temp1 = false;
                  }
              });
              if(temp1 == false){
                  flag1 = false;
              } else {
                  flag1 = true;
              }
          }
      });
    }
    if(flag1 == true)
    {  
      if(is_role_assoc != '1') { showFullLoader('content_loader'+form_container); }
      var filter_text = searchModule.getActiveMenuValue();
      var last_filter_id = $('.item-list').find('li.active').attr('id');
      var filter_prop_id = $('.item-list').find('li.active').attr('data-statusid');
      var col_head_prop_id = getColHeadPropertyId();
      var activeMenu = [searchModule.getActiveMenuValue(),searchModule.getActiveMenuDataId()];

      var form_data = new FormData(document.getElementById("formId_ooYRyjGYeH"));
      form_data.append('action', 'single');
      form_data.append('col_head_prop_id', col_head_prop_id);
      form_data.append('list_setting_array', list_setting_array);
      form_data.append('list_node_id_array', list_node_id_array);
      form_data.append('list_head_array', list_head_array);
      form_data.append('activeMenu', activeMenu);
      form_data.append('login_user_id', login_user_id);
      form_data.append('login_role_id', login_role_id);
      form_data.append('emailLinks', JSON.stringify(all_settings['deal']['settings']['emailLinks']));
      var pId = [];
      $('.autogenerated:visible').each(function () {
          pId.push($(this).data('id'));
      });
      if(pId.length){
        form_data.append('autogenerated', pId);
      }
      
        $.ajax({
          type: "POST",
          url : "http://localhost/pu/puidata/page_plugin/code.php",
          data: form_data,
          dataType: "json",
          async: true,
          enctype: "multipart/form-data",
          cache: false,
          contentType: false,
          processData: false,
          success:function(data){
              if(data.result == 0) {
                if (is_role_assoc == '1' && form_container == '_dashboard')
                {
                  instance_node_id_dashboard = data.data.node_id;
                  node_instance_id_dashboard = data.data.node_instance_id;
                  form_action_type = 'view';
                  getRolesOfPlugin('1');
                } 
                else if (is_role_assoc == '0' && form_container == '_dashboard')
                {
                    if(data.data.status == 'P')
                    { 
                      showFullLoader('full_page_loader');
                      GoToPageModule.setDealId(data.data.node_id);
                    }
                    instance_node_id_dashboard = '';
                    node_instance_id_dashboard = '';
                    $('.j_my_createDeal_close').trigger('click');
                }
                else
                {
                  if(typeof updateMenuCount === "function") {
                      updateMenuCount();
                  }
                  if(typeof updateActiveList === "function") {
                      updateActiveList(data.data.col_data, data.data.save_type,data.data.node_id,data.data.statusChange);
                  }
                }
              } else if(data.result == 2) {
                $.keep_showing_full_page_loader = false;
                globalVar.dealFilterCheck = false; // delete deals loader issue fixed
                if(is_role_assoc != '1') { hideFullLoader('content_loader'+form_container); }else{hideFullLoader('content_loader'+form_container);}
                
                bootbox.alert(data.message);
                goAhead=false;
                return false;
              } else {
                  if(is_role_assoc != '1') { hideFullLoader('content_loader'+form_container); }else{hideFullLoader('content_loader'+form_container);}
                  if(data.Stock=="false") {
                    bootbox.alert({title: "Alert",message:data.Stockmsg});
                    return false;
                  } 
                  if(data.Customer=="false") {
                    bootbox.alert({title: "Alert",message:data.Customermsg});
                    return false;
                  } 
                  if(data.FiQuote=="false") {
                    bootbox.alert({title: "Alert",message:data.FiQuotemsg});
                    return false;
                  } 
                  if(data.SalesQuote=="false") {
                    bootbox.alert({title: "Alert",message:data.SalesQuotemsg});
                    return false;
                  } 
              }
          },
          complete: function(data) {
              if(data.result == 0) {
                $(".validationCheck").val("");
              }  
          },
          error: function(data) {

          }
        });
       
    }
  }
</script>

// FOR MULTIPLE CLASS
//action = multiple
//add line on post
//form_data.append('post_tree', JSON.stringify(makePostTree()));

// For PPC class
<div id="content_scroler_div" class="customScroll mid-section-HT" >
    <div class="listing-content-wrap" >
        <form class="form-horizontal" id="formId_E2N1ZAaB3c" name="formId_E2N1ZAaB3c" action="post" enctype="multipart/form-data">
            <div class="cls-wrapper cls-tree form-class-section" data-id="819"  id="cls_819">
                <div class="collapse-wrapper">
                    <div class="list-detail-section">
                        <input type="hidden" id="node_class_id" name="node_class_id" value="819" />  
                        <div class="nested-layout clearfix">
                            <a class="list-title-heading class-accordian collapsed-mode "   >
                            <i class="fa fa-angle-up"></i><span class="list-title-accordian">Instructions<span>
                            </a>
                            <div class="collapse " >
                                <div class="list-detail-section">
                                    <div class="form-group nested-layout">
                                        <label class="col-sm-12 control-label form-label">
                                            <div class='labeldiv'>
                                                <div class='labeldiv'>1. Please enter all the information carefully.</div>
                                            </div>
                                        </label>
                                    </div>
                                    <div class="form-group nested-layout">
                                        <label class="col-sm-12 control-label form-label">
                                            <div class='labeldiv'>
                                                <div class='labeldiv'>2. Please enter all the information in correct format.</div>
                                            </div>
                                        </label>
                                    </div>
                                    <div class="form-group nested-layout">
                                        <label class="col-sm-12 control-label form-label">
                                            <div class='labeldiv'>
                                                <div class='labeldiv'>3. Please enter data for required fields.</div>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="nested-layout clearfix">
                            <a class="list-title-heading class-accordian uncollapsed-mode "   >
                            <i class="fa fa-angle-down"></i><span class="list-title-accordian">Team Member<span>
                            </a>
                            <div class="collapse in" >
                                <div class="list-detail-section">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">ID</label> 
                                        <div class="col-sm-8"> <input type="text" class="validationCheck form-control inline-input newsletter_text3" data-id="7986" id="instance_property_caption7986"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder=""  > <input id="instance_property_id7986" name="instance_property_id[]" type="hidden" value="7986" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Name</label> 
                                        <div class="col-sm-8"> <input type="text" class="validationCheck form-control inline-input newsletter_text3" data-id="7782" id="instance_property_caption7782"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder=""  > <input id="instance_property_id7782" name="instance_property_id[]" type="hidden" value="7782" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Title</label> 
                                        <div class="col-sm-8"> <input type="text" class="validationCheck form-control inline-input newsletter_text3" data-id="7783" id="instance_property_caption7783"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder=""  > <input id="instance_property_id7783" name="instance_property_id[]" type="hidden" value="7783" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="nested-layout clearfix">
                            <a class="list-title-heading class-accordian uncollapsed-mode "   >
                            <i class="fa fa-angle-down"></i><span class="list-title-accordian">Manager<span>
                            </a>
                            <div class="collapse in" >
                                <div class="list-detail-section">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Name</label> 
                                        <div class="col-sm-8"> <input type="text" class="validationCheck form-control inline-input newsletter_text3" data-id="7814" id="instance_property_caption7814"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder=""  > <input id="instance_property_id7814" name="instance_property_id[]" type="hidden" value="7814" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Title</label> 
                                        <div class="col-sm-8"> <input type="text" class="validationCheck form-control inline-input newsletter_text3" data-id="7815" id="instance_property_caption7815"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder=""  > <input id="instance_property_id7815" name="instance_property_id[]" type="hidden" value="7815" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="nested-layout clearfix">
                            <a class="list-title-heading class-accordian uncollapsed-mode "   >
                            <i class="fa fa-angle-down"></i><span class="list-title-accordian">Review<span>
                            </a>
                            <div class="collapse in" >
                                <div class="list-detail-section">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Period</label> 
                                        <div class="col-sm-8">
                                            <select name="instance_property_caption[]" class=" form-control form-select select-field nodeZselect nodeselection-dropdown instanceRunTab"  data-id="7817" id="instance_property_caption7817" >
                                                <option value="Quarterly">Quarterly</option>
                                                <option value="Monthly">Monthly</option>
                                                <option value="Yearly">Yearly</option>
                                            </select>
                                            <input id="instance_property_id7817" name="instance_property_id[]" type="hidden" value="7817" />  <span class="list-view-detail hide"></span> 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Date</label> 
                                        <div class="col-sm-8">
                                            <div id='calender_wrapper'><input data-id='7818' id='class_property_id7818' name='class_property_id[]' type='hidden' value='7818'><input type='text'  readonly='' class='instanceRunTab validationCheck datepicker form-control inline-input' id='instance_property_caption7818' name='instance_property_caption[]' placeholder='' validate-data=''></div>
                                            <input id="instance_property_id7818" name="instance_property_id[]" type="hidden" value="7818" />  <span class="list-view-detail hide"></span> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="nested-layout clearfix">
                            <a class="list-title-heading class-accordian uncollapsed-mode "   >
                            <i class="fa fa-angle-down"></i><span class="list-title-accordian">Performance Assessment<span>
                            </a>
                            <div class="collapse in" >
                                <div class="list-detail-section">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Exceptional performance</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7820" id="instance_property_caption7820"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7820" name="instance_property_id[]" type="hidden" value="7820" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Performance guidance</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7821" id="instance_property_caption7821"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7821" name="instance_property_id[]" type="hidden" value="7821" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="nested-layout clearfix">
                            <a class="list-title-heading class-accordian uncollapsed-mode "   >
                            <i class="fa fa-angle-down"></i><span class="list-title-accordian">Team Member Questions<span>
                            </a>
                            <div class="collapse in" >
                                <div class="list-detail-section">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Things we should start?</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7823" id="instance_property_caption7823"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7823" name="instance_property_id[]" type="hidden" value="7823" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Things we should stop?</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7824" id="instance_property_caption7824"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7824" name="instance_property_id[]" type="hidden" value="7824" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Things we should continue?</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7825" id="instance_property_caption7825"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7825" name="instance_property_id[]" type="hidden" value="7825" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">What resources would be helpful to you right now?</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7826" id="instance_property_caption7826"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7826" name="instance_property_id[]" type="hidden" value="7826" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Is there anything I can help you with?</label> 
                                        <div class="col-sm-8"> <textarea  rows="1" cols="55" class="validationCheck form-control inline-input newsletter_text3" name="instance_property_caption[]"  data-id="7827" id="instance_property_caption7827"  validate-data="" placeholder="" ></textarea> <input id="instance_property_id7827" name="instance_property_id[]" type="hidden" value="7827" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="nested-layout clearfix hide">
                            <a class="list-title-heading class-accordian uncollapsed-mode "   >
                            <i class="fa fa-angle-down"></i><span class="list-title-accordian">Document<span>
                            </a>
                            <div class="collapse in" >
                                <div class="list-detail-section">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label form-label">Document Id</label> 
                                        <div class="col-sm-8"> <input type="text" class="validationCheck form-control inline-input newsletter_text3" data-id="7830" id="instance_property_caption7830"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder=""  > <input id="instance_property_id7830" name="instance_property_id[]" type="hidden" value="7830" />  <span class="list-view-detail hide"></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div></div>
                            <div class="form-group"> <a class="hide" href="javascript:submitFunc_n7SyP6Z0c4();">Submit</a> </div>
                            <input type="hidden" value="submitFunc_n7SyP6Z0c4()" id="id_detail_submit" name="id_detail_submit" />
                             <input type="hidden" value="" id="id_detail_save_type" name="id_detail_save_type" />
                              <input type="hidden" id="id_detail_instance_id" name="id_detail_instance_id" value="" /> 
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
                
                            function submitFunc_n7SyP6Z0c4() {
                            var flag1=true; var checkflag1=""; var temp1=true;
                            var formId = "formId_E2N1ZAaB3c";
                            var formElem = $("#formId_E2N1ZAaB3c:visible");
                            $(formElem).find(".validationCheck:visible").each(function(i,k){
                                var data1 = $.trim($(this).val());
                                var element1 = $(this);
                                if (data1.indexOf("'") >= 0 || data1.indexOf('"') >= 0) { data1 = "~$~"; }
                                if(flag1 == true){
                                    var fn1="";
                                    fn1 = $(this).attr("validate-data").split(";");
                                    var aa1=[];
                                    for(i=0;i<fn1.length;i++){
                                      aa1.push(fn1[i]);
                                    }
                                    aa1.toString();
                                    $(aa1).each(function(i,v){                                             
                                        var newStr1 = v;
                                        var valdata1 = data1;
                                        if(newStr1.indexOf("pui_fun")>=0) {
                                            var elementId = element1.attr("id");
                                            var aaa1 = newStr1.replace("()","('"+elementId+"')");
                                        } else {
                                            if(valdata1 == ""){
                                                var aaa1 = newStr1.replace("()","('')");
                                            }else {
                                                var aaa1 = newStr1.replace("()","('"+data1+"')");
                                            }
                                        }
                                        checkflag1 = eval(aaa1);
                                        if(checkflag1 == false){
                                            temp1 = false;
                                        }
                                    });
                                    if(temp1 == false){
                                        flag1 = false;
                                    } else {
                                        flag1 = true;
                                    }
                                }
                            });if(flag1 == true){  
                                    if(is_role_assoc != '1') { showFullLoader('content_loader'); }
                                    var filter_text = searchModule.getActiveMenuValue();
                                    var last_filter_id = $('.item-list').find('li.active').attr('id');
                                    var filter_prop_id = $('.item-list').find('li.active').attr('data-statusid');
                                    var col_head_prop_id = getColHeadPropertyId();
                                    var activeMenu = [searchModule.getActiveMenuValue(),searchModule.getActiveMenuDataId()];

                                    var form_data = new FormData(document.getElementById('formId_E2N1ZAaB3c'));
                                    form_data.append('action', 'single');
                                    form_data.append('col_head_prop_id', col_head_prop_id);
                                    form_data.append('list_setting_array', list_setting_array);
                                    form_data.append('list_node_id_array', list_node_id_array);
                                    form_data.append('list_head_array', list_head_array);
                                    form_data.append('activeMenu', activeMenu);
                                    form_data.append('login_user_id', login_user_id);
                                    form_data.append('login_role_id', login_role_id);
                                    $.ajax({
                                        type: 'POST',
                                        url : 'http://qa.pu.prospus.com/puidata/page_plugin/code.php',
                                        data: form_data,
                                        dataType: 'json',
                                        async: true,
                                        enctype: 'multipart/form-data',
                                        cache: false,
                                        contentType: false,
                                        processData: false,
                                        success:function(data){
                                            if(data.result == 0) {
                                                if(typeof updateMenuCount === 'function') {
                                                    updateMenuCount();
                                                }
                                                if(typeof updateActiveList === 'function') {
                                                    updateActiveList(data.data.col_data, data.data.save_type,data.data.node_id,data.data.statusChange);
                                                }
                                            } else {
                                                alert('failed');
                                            }
                                        },
                                        complete: function(data) {
                                            $('.validationCheck').val('');
                                            if(htmlModule.properties.load_document_view === true) {
                                             setTimeout(function() {  
                                              getReviewDocument(true);
                                             }, 1000);
                                             
                                            }
                                            hideFullLoader('content_loader');
                                        },
                                        error: function(data) {

                                        }
                                    });
                                }}</script>


//For Manage Control

<div id="content_scroler_div" class="customScroll mid-section-HT" > 
    <div class="listing-content-wrap" >
        <form class="form-horizontal" id="formId_ooYRyjGYeH" name="formId_ooYRyjGYeH" action="post" enctype="multipart/form-data">
            <div class="cls-wrapper cls-tree form-class-section" data-id="853"  id="cls_853"><div class="collapse-wrapper"><div class="list-detail-section"> <input type="hidden" id="node_class_id" name="node_class_id" value="853" />  
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Role</label>
                     <div class="col-sm-8">
                         <select name="instance_property_caption[]" class=" form-control form-select select-field nodeZselect nodeselection-dropdown instanceRunTab role "  data-id="8444" id="instance_property_caption8444" > </select> <input id="instance_property_id8444" name="instance_property_id[]" type="hidden" value="8444" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
            
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Action</label>
                     <div class="col-sm-8">
                         <div id='checkbox_wrapper' class='action' ><input type="hidden"  class="instanceRunTab validationCheck" id="instance_property_caption8445" name="instance_property_caption[]" placeholder="" validate-data="" value=""><div class='input-chk'><label><input type='checkbox'  class='checkClass_8445' name='check_8445[]' data-id='8445' id='check_8445_0' onchange='setValueOfNodeZcheckBox(this,8445)'  value='Can View'>Can View</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8445' name='check_8445[]' data-id='8445' id='check_8445_1' onchange='setValueOfNodeZcheckBox(this,8445)'  value='Can Edit'>Can Edit</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8445' name='check_8445[]' data-id='8445' id='check_8445_2' onchange='setValueOfNodeZcheckBox(this,8445)'  value='Can Add'>Can Add</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8445' name='check_8445[]' data-id='8445' id='check_8445_3' onchange='setValueOfNodeZcheckBox(this,8445)'  value='Can Save'>Can Save</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8445' name='check_8445[]' data-id='8445' id='check_8445_4' onchange='setValueOfNodeZcheckBox(this,8445)'  value='Can Complete'>Can Complete</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8445' name='check_8445[]' data-id='8445' id='check_8445_5' onchange='setValueOfNodeZcheckBox(this,8445)'  value='Can Download Pdf'>Can Download Pdf</label></div></div> <input id="instance_property_id8445" name="instance_property_id[]" type="hidden" value="8445" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
            
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Is Current Version</label>
                     <div class="col-sm-8">
                         <select name="instance_property_caption[]" class=" form-control form-select select-field nodeZselect nodeselection-dropdown instanceRunTab is-current-version "  data-id="8446" id="instance_property_caption8446" > <option value="True">True</option><option value="False">False</option></select> <input id="instance_property_id8446" name="instance_property_id[]" type="hidden" value="8446" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
             <div  id="cls_853_854" data-parent-instance-node-id="" data-mode="add"  data-id=854 class="cls-wrapper nested-layout cls-tree clearfix cls_853_854 "   ><a class="list-title-heading class-accordian " ><i class="fa fa-angle-down"></i>OPERATION ROLE CONTROL</a><div class="collapse-wrapper  " >
          <div class="list-detail-section"><span style="cursor:pointer;" class="right manage-right-cls-action"><i class="prs-icon add hide"></i><i class="prs-icon icon_close confirm_remove_close hide"></i></span> 
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Role</label>
                     <div class="col-sm-8">
                         <select name="instance_property_caption[]" class=" form-control form-select select-field nodeZselect nodeselection-dropdown instanceRunTab role "  data-id="8448" id="instance_property_caption8448" > </select> <input id="instance_property_id8448" name="instance_property_id[]" type="hidden" value="8448" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
            
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Action</label>
                     <div class="col-sm-8">
                         <div id='checkbox_wrapper' class='action' ><input type="hidden"  class="instanceRunTab validationCheck" id="instance_property_caption8449" name="instance_property_caption[]" placeholder="" validate-data="" value=""><div class='input-chk'><label><input type='checkbox'  class='checkClass_8449' name='check_8449[]' data-id='8449' id='check_8449_0' onchange='setValueOfNodeZcheckBox(this,8449)'  value='Can View'>Can View</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8449' name='check_8449[]' data-id='8449' id='check_8449_1' onchange='setValueOfNodeZcheckBox(this,8449)'  value='Can Edit'>Can Edit</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8449' name='check_8449[]' data-id='8449' id='check_8449_2' onchange='setValueOfNodeZcheckBox(this,8449)'  value='Can Add'>Can Add</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8449' name='check_8449[]' data-id='8449' id='check_8449_3' onchange='setValueOfNodeZcheckBox(this,8449)'  value='Can Save'>Can Save</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8449' name='check_8449[]' data-id='8449' id='check_8449_4' onchange='setValueOfNodeZcheckBox(this,8449)'  value='Can Complete'>Can Complete</label></div><div class='input-chk'><label><input type='checkbox'  class='checkClass_8449' name='check_8449[]' data-id='8449' id='check_8449_5' onchange='setValueOfNodeZcheckBox(this,8449)'  value='Can Download Pdf'>Can Download Pdf</label></div></div> <input id="instance_property_id8449" name="instance_property_id[]" type="hidden" value="8449" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
            </div></div></div><div  id="cls_853_852" data-parent-instance-node-id="" data-mode="add"  data-id=852 class="cls-wrapper nested-layout cls-tree clearfix cls_853_852 "   ><a class="list-title-heading class-accordian " ><i class="fa fa-angle-down"></i>Pass Deal</a><div class="collapse-wrapper  " >
          <div class="list-detail-section"><span style="cursor:pointer;" class="right manage-right-cls-action"><i class="prs-icon add hide"></i><i class="prs-icon icon_close confirm_remove_close hide"></i></span> 
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Role</label>
                     <div class="col-sm-8">
                         <select name="instance_property_caption[]" class=" form-control form-select select-field nodeZselect nodeselection-dropdown instanceRunTab role "  data-id="8440" id="instance_property_caption8440" > </select> <input id="instance_property_id8440" name="instance_property_id[]" type="hidden" value="8440" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
            
                 <div class="form-group">
                   <label class="col-sm-4 control-label form-label">Common Operation</label>
                     <div class="col-sm-8">
                         <input type="text" class="validationCheck form-control inline-input newsletter_text3 common-operation " data-id="8442" id="instance_property_caption8442"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Common Operation"  > <input id="instance_property_id8442" name="instance_property_id[]" type="hidden" value="8442" />            
                         <span class="list-view-detail hide"></span>
                     </div>      
                 </div>
             <div  id="cls_853_852_851" data-parent-instance-node-id="" data-mode="add"  data-id=851 class="cls-wrapper nested-layout cls-tree clearfix cls_853_852_851 " onclick="getSubClassStructureLayout(851, 1361874, 'Edit', this)"   ><a class="list-title-heading class-accordian " ><i class="fa fa-angle-up"></i>Condition</a><div class="collapse-wrapper hide " >
          <div class="list-detail-section"></div></div></div></div></div></div><div><div></div>
            <div class="form-group">               
                  <a class="hide" href="javascript:submitFunc_HJH3yTDDmi();">Submit</a>            
            </div>  
              <input type="hidden" value="submitFunc_HJH3yTDDmi()" id="id_detail_submit" name="id_detail_submit" />
              <input type="hidden" value="" id="id_detail_save_type" name="id_detail_save_type" />
              <input type="hidden" id="id_detail_instance_id" name="id_detail_instance_id" value="" />          
        </form>
    </div>
</div>
<script type="text/javascript">
  function submitFunc_HJH3yTDDmi() {
    var flag1=true; var checkflag1=""; var temp1=true;
    var formId = "formId_ooYRyjGYeH";
    var formElem = $("#formId_ooYRyjGYeH:visible");
     $(formElem).find(".validationCheck:visible").each(function(i,k){
          var data1 = $.trim($(this).val());
          var element1 = $(this);
          if (data1.indexOf("'") >= 0 || data1.indexOf('"') >= 0) { data1 = "~$~"; }
          if(flag1 == true){
              var fn1="";
              fn1 = $(this).attr("validate-data").split(";");
              var aa1=[];
              for(i=0;i<fn1.length;i++){
                aa1.push(fn1[i]);
              }
              aa1.toString();
              $(aa1).each(function(i,v){                                             
                  var newStr1 = v;
                  var valdata1 = data1;
                  if(newStr1.indexOf("pui_fun")>=0) {
                      var elementId = element1.attr("id");
                      var aaa1 = newStr1.replace("()","('"+elementId+"')");
                  } else {
                      if(valdata1 == ""){
                          var aaa1 = newStr1.replace("()","('')");
                      }else {
                          var aaa1 = newStr1.replace("()","('"+data1+"')");
                      }
                  }
                  checkflag1 = eval(aaa1);
                  if(checkflag1 == false){
                      temp1 = false;
                  }
              });
              if(temp1 == false){
                  flag1 = false;
              } else {
                  flag1 = true;
              }
          }
      });
   
    if(flag1 == true)
    {  
      
      var filter_text = searchModule.getActiveMenuValue();
      var last_filter_id = $('.item-list').find('li.active').attr('id');
      var filter_prop_id = $('.item-list').find('li.active').attr('data-statusid');
      var col_head_prop_id = getColHeadPropertyId();
      var activeMenu = [searchModule.getActiveMenuValue(),searchModule.getActiveMenuDataId()];
      
      $(".nested-layout.cls-tree").each(function () {

                $(this).find("[name='instance_property_id[]']").attr('name', "instance_property_id_sub_cls[]");
                $(this).find("[name='instance_property_caption[]']").attr('name', "instance_property_caption_sub_cls[]");
               
      });
      var form_data = new FormData(document.getElementById("formId_ooYRyjGYeH"));
      form_data.append('action', 'multiple');
      form_data.append('col_head_prop_id', col_head_prop_id);
      form_data.append('list_setting_array', list_setting_array);
      form_data.append('list_node_id_array', list_node_id_array);
      form_data.append('list_head_array', list_head_array);
      form_data.append('activeMenu', activeMenu);
      form_data.append('login_user_id', login_user_id);
      form_data.append('login_role_id', login_role_id);
      form_data.append('is_current_version', $('#instance_property_caption8446').val());
      form_data.append('main_role_id', $('#instance_property_caption8444 option:selected').val());
      
      
      
      form_data.append('emailLinks', JSON.stringify(all_settings['deal']['settings']['emailLinks']));
      var pId = [];
      $('.autogenerated:visible').each(function () {
          pId.push($(this).data('id'));
      });
      if(pId.length){
        form_data.append('autogenerated', pId);
      }
      form_data.append('post_tree', JSON.stringify(makePostTree()));
        $.ajax({
          type: "POST",
          url : "http://localhost/pu/puidata/page_plugin/code.php",
          data: form_data,
          dataType: "json",
          async: true,
          enctype: "multipart/form-data",
          cache: false,
          contentType: false,
          processData: false,
          success:function(data){
              if(data.result == 0) {
                
                  if(typeof updateMenuCount === "function") {
                      updateMenuCount();
                  }
                  if(typeof updateActiveList === "function") {
                      updateActiveList(data.data.col_data, data.data.save_type,data.data.node_id,data.data.statusChange);
                  }
              } 
          },
          complete: function(data) {
              if(data.result == 0) {
                $(".validationCheck").val("");
                //hideFullLoader('content_loader');
              }  
          },
          error: function(data) {

          }
        });
       
    }
  }
</script>

// For Store
<div id="content_scroler_div" class="customScroll mid-section-HT" > 
    <div class="listing-content-wrap" >
    <form class="form-horizontal" id="formId_ooYRyjGYeH" name="formId_ooYRyjGYeH" action="post" enctype="multipart/form-data">
        <div class="cls-wrapper cls-tree form-class-section" data-id="822"  id="cls_822"><div class="collapse-wrapper"><div class="list-detail-section"> <input type="hidden" id="node_class_id" name="node_class_id" value="822" />  
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Location</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 location " data-id="7988" id="instance_property_caption7988"  name="instance_property_caption[]" maxLength="50" validate-data="checkDF43L1zfCdvalidateRegLocation()" onblur="getAllActiveRoleHTML(7988)" placeholder="Location"  > <input id="instance_property_id7988" name="instance_property_id[]" type="hidden" value="7988" /> <script type="text/javascript">function checkDF43L1zfCdvalidateRegLocation(location) { if ($.trim(location) == "") { alert("Please enter location.");  return false; } return true; }</script>           
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">StoreName</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 storename " data-id="7989" id="instance_property_caption7989"  name="instance_property_caption[]" maxLength="50" validate-data="checkgJLaeGt81HvalidateRegStoreName()" placeholder="StoreName"  > <input id="instance_property_id7989" name="instance_property_id[]" type="hidden" value="7989" /> <script type="text/javascript">function checkgJLaeGt81HvalidateRegStoreName(StoreName) { if ($.trim(StoreName) == "") { alert("Please enter storename.");  return false; } return true; }</script>           
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">DisplayName</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 displayname " data-id="8465" id="instance_property_caption8465"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="DisplayName"  > <input id="instance_property_id8465" name="instance_property_id[]" type="hidden" value="8465" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Address1</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 address1 " data-id="8466" id="instance_property_caption8466"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Address1"  > <input id="instance_property_id8466" name="instance_property_id[]" type="hidden" value="8466" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Address2</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 address2 " data-id="8467" id="instance_property_caption8467"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Address2"  > <input id="instance_property_id8467" name="instance_property_id[]" type="hidden" value="8467" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">City</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 city " data-id="8468" id="instance_property_caption8468"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="City"  > <input id="instance_property_id8468" name="instance_property_id[]" type="hidden" value="8468" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">State</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 state " data-id="8469" id="instance_property_caption8469"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="State"  > <input id="instance_property_id8469" name="instance_property_id[]" type="hidden" value="8469" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">ZipCode</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 zipcode " data-id="8470" id="instance_property_caption8470"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="ZipCode"  > <input id="instance_property_id8470" name="instance_property_id[]" type="hidden" value="8470" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">County</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 county " data-id="8471" id="instance_property_caption8471"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="County"  > <input id="instance_property_id8471" name="instance_property_id[]" type="hidden" value="8471" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Phone</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 phone " data-id="8472" id="instance_property_caption8472"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Phone"  > <input id="instance_property_id8472" name="instance_property_id[]" type="hidden" value="8472" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Fax</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 fax " data-id="8473" id="instance_property_caption8473"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Fax"  > <input id="instance_property_id8473" name="instance_property_id[]" type="hidden" value="8473" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">AppOneID</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 apponeid " data-id="8474" id="instance_property_caption8474"  name="instance_property_caption[]" maxLength="50" validate-data="checkoWGt9D0894validateRegAppOneID()" placeholder="AppOneID"  > <input id="instance_property_id8474" name="instance_property_id[]" type="hidden" value="8474" /> <script type="text/javascript">function checkoWGt9D0894validateRegAppOneID(AppOneID) { if ($.trim(AppOneID) == "") { alert("Please enter apponeid.");  return false; } return true; }</script>           
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Region</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 region " data-id="9130" id="instance_property_caption9130"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Region"  > <input id="instance_property_id9130" name="instance_property_id[]" type="hidden" value="9130" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
         <div  id="cls_822_858" data-parent-instance-node-id="" data-mode="add"  data-id=858 class="cls-wrapper nested-layout cls-tree clearfix cls_822_858 "   ><a class="list-title-heading class-accordian " ><i class="fa fa-angle-down"></i>Location Role Details</a><div class="collapse-wrapper  " >
          <div class="list-detail-section"><span style="cursor:pointer;" class="right manage-right-cls-action"><i class="prs-icon add hide"></i><i class="prs-icon icon_close confirm_remove_close hide"></i></span> 
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">LocationNID</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 locationnid " data-id="8755" id="instance_property_caption8755"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="LocationNID"  > <input id="instance_property_id8755" name="instance_property_id[]" type="hidden" value="8755" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">RoleNID</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 rolenid " data-id="8756" id="instance_property_caption8756"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="RoleNID"  > <input id="instance_property_id8756" name="instance_property_id[]" type="hidden" value="8756" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">ActorNID</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 actornid " data-id="8757" id="instance_property_caption8757"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="ActorNID"  > <input id="instance_property_id8757" name="instance_property_id[]" type="hidden" value="8757" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Location</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 location " data-id="8758" id="instance_property_caption8758"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Location"  > <input id="instance_property_id8758" name="instance_property_id[]" type="hidden" value="8758" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Role</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 role " data-id="8759" id="instance_property_caption8759"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Role"  > <input id="instance_property_id8759" name="instance_property_id[]" type="hidden" value="8759" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Actor</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 actor " data-id="8760" id="instance_property_caption8760"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Actor"  > <input id="instance_property_id8760" name="instance_property_id[]" type="hidden" value="8760" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        
           <div class="form-group">
             <label class="col-sm-4 control-label form-label">Email Address</label>
               <div class="col-sm-8">
                   <input type="text" class="validationCheck form-control inline-input newsletter_text3 email-address " data-id="8761" id="instance_property_caption8761"  name="instance_property_caption[]" maxLength="50" validate-data="" placeholder="Email Address"  > <input id="instance_property_id8761" name="instance_property_id[]" type="hidden" value="8761" />            
                   <span class="list-view-detail hide"></span>
               </div>      
           </div>
        </div></div></div><div><div></div>
        <div class="form-group">               
              <a class="hide" href="javascript:submitFunc_HJH3yTDDmi();">Submit</a>            
        </div>  
          <input type="hidden" value="submitFunc_HJH3yTDDmi()" id="id_detail_submit" name="id_detail_submit" />
          <input type="hidden" value="" id="id_detail_save_type" name="id_detail_save_type" />
          <input type="hidden" id="id_detail_instance_id" name="id_detail_instance_id" value="" />          
    </form>
  </div>
</div>
<script type="text/javascript">
  function submitFunc_HJH3yTDDmi() {
    var flag1=true; var checkflag1=""; var temp1=true;
    var formId = "formId_ooYRyjGYeH";
    var formElem = $("#formId_ooYRyjGYeH:visible");
     $(formElem).find(".validationCheck:visible").each(function(i,k){
          var data1 = $.trim($(this).val());
          var element1 = $(this);
          if (data1.indexOf("'") >= 0 || data1.indexOf('"') >= 0) { data1 = "~$~"; }
          if(flag1 == true){
              var fn1="";
              fn1 = $(this).attr("validate-data").split(";");
              var aa1=[];
              for(i=0;i<fn1.length;i++){
                aa1.push(fn1[i]);
              }
              aa1.toString();
              $(aa1).each(function(i,v){                                             
                  var newStr1 = v;
                  var valdata1 = data1;
                  if(newStr1.indexOf("pui_fun")>=0) {
                      var elementId = element1.attr("id");
                      var aaa1 = newStr1.replace("()","('"+elementId+"')");
                  } else {
                      if(valdata1 == ""){
                          var aaa1 = newStr1.replace("()","('')");
                      }else {
                          var aaa1 = newStr1.replace("()","('"+data1+"')");
                      }
                  }
                  checkflag1 = eval(aaa1);
                  if(checkflag1 == false){
                      temp1 = false;
                  }
              });
              if(temp1 == false){
                  flag1 = false;
              } else {
                  flag1 = true;
              }
          }
      });
   
    if(flag1 == true)
    {  
      showFullLoader('full_page_loader');
      var filter_text = searchModule.getActiveMenuValue();
      var last_filter_id = $('.item-list').find('li.active').attr('id');
      var filter_prop_id = $('.item-list').find('li.active').attr('data-statusid');
      var col_head_prop_id = getColHeadPropertyId();
      var activeMenu = [searchModule.getActiveMenuValue(),searchModule.getActiveMenuDataId()];
      
      $(".nested-layout.cls-tree").each(function () {
        $(this).find("[name='instance_property_id[]']").attr('name', "instance_property_id_sub_cls[]");
        $(this).find("[name='instance_property_caption[]']").attr('name', "instance_property_caption_sub_cls[]");
      });
      var form_data = new FormData(document.getElementById("formId_ooYRyjGYeH"));
      form_data.append('action', 'multiple');
      form_data.append('col_head_prop_id', col_head_prop_id);
      form_data.append('list_setting_array', list_setting_array);
      form_data.append('list_node_id_array', list_node_id_array);
      form_data.append('list_head_array', list_head_array);
      form_data.append('activeMenu', activeMenu);
      form_data.append('login_user_id', login_user_id);
      form_data.append('login_role_id', login_role_id);
      
      form_data.append('emailLinks', JSON.stringify(all_settings['deal']['settings']['emailLinks']));
      var pId = [];
      $('.autogenerated:visible').each(function () {
          pId.push($(this).data('id'));
      });
      if(pId.length){
        form_data.append('autogenerated', pId);
      }
      form_data.append('post_tree', JSON.stringify(makePostTree()));
        $.ajax({
          type: "POST",
          url : "http://dev.pu.prospus.com/puidata/page_plugin/code.php",
          data: form_data,
          dataType: "json",
          async: true,
          enctype: "multipart/form-data",
          cache: false,
          contentType: false,
          processData: false,
          success:function(data){
              if(data.result == 0) {
                
                  if(typeof updateMenuCount === "function") {
                      updateMenuCount();
                  }
                  if(typeof updateActiveList === "function") {
                      updateActiveList(data.data.col_data, data.data.save_type,data.data.node_id,data.data.statusChange);
                  }
              } 
          },
          complete: function(data) {
              if(data.result == 0) {
                $(".validationCheck").val("");
                //hideFullLoader('content_loader');
              }  
          },
          error: function(data) {

          }
        });
       
    }
  }
</script>