<?php

/**
 * This makes our life easier when dealing with paths. Everything is relative
 * to the application root now.
 */
ini_set('max_execution_time', 0);
date_default_timezone_set("Asia/Calcutta");
error_reporting(1);
session_start();
if ($_SERVER['REDIRECT_BASE'] == "") {
    $slashes = '/';
} else {
    $slashes = $_SERVER['REDIRECT_BASE'];
}

if ($_SERVER['HTTP_HOST'] == "localhost") {
    DEFINE('BASE_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/pu/');
    DEFINE('ABSO_URL', $_SERVER['DOCUMENT_ROOT'] . $slashes);
    DEFINE('SOCKET_CHAT_URL', "ws://" . $_SERVER['HTTP_HOST'] . ":9001/pu/course-dialogue-server.php");
    DEFINE('EDITOR', 'http://' . $_SERVER['HTTP_HOST'] . '/pu/public/js/edt-worker.js');
    define('STORAGE_NAME', 'file');
} else {
    DEFINE('BASE_URL', 'http://' . $_SERVER['HTTP_HOST'] . $slashes);
    DEFINE('ABSO_URL', $_SERVER['DOCUMENT_ROOT'] . $slashes);
    define('STORAGE_NAME', 'file');


    if ($_SERVER['HTTP_HOST'] == "sta.pu.prospus.com" || $_SERVER['HTTP_HOST'] == "sta-lb-837517909.us-east-1.elb.amazonaws.com") {
        DEFINE('SOCKET_CHAT_URL', "ws://" . $_SERVER['HTTP_HOST'] . ":9001/course-dialogue-server.php");
    } else if ($_SERVER['HTTP_HOST'] == "qa.pu.prospus.com" || $_SERVER['HTTP_HOST'] == "qa-lb-526760236.us-east-1.elb.amazonaws.com") {
        DEFINE('SOCKET_CHAT_URL', "ws://" . $_SERVER['HTTP_HOST'] . ":9003/course-dialogue-server.php");
    } else if ($_SERVER['HTTP_HOST'] == "dev.pu.prospus.com" || $_SERVER['HTTP_HOST'] == "dev-lb-830601176.us-east-1.elb.amazonaws.com") {
        DEFINE('SOCKET_CHAT_URL', "ws://" . $_SERVER['HTTP_HOST'] . ":9003/course-dialogue-server.php");
    }

    DEFINE('EDITOR', 'http://' . $_SERVER['HTTP_HOST'] . '/public/js/edt-worker.js');
}


DEFINE('MENU_SETDEFAULT_PROPERTY_ID', 8451);
DEFINE('PREFIX', 'local_');
DEFINE('CHECKBOX_SEPERATOR', '~#~');
DEFINE('RECORD_PER_PGE', 25);
DEFINE('ENCRYPTION_KEY', 'd0a7e7997b6d5fcd55f4b5c32611b87cd923e88837b63bf2941ef819dc8ca282');
DEFINE('ENCRYPTION_STATUS', '0');
DEFINE('DATA_PER_PGE', 25);

DEFINE('PRODUCTION_CLASS_ID', 433);
DEFINE('SERIES_CLASS_ID', 431);
DEFINE('SEGMENT_CLASS_ID', 430);
DEFINE('TAXONOMY_CLASS_ID', 165);
DEFINE('TAXONOMY_TYPE_PROPERTY_ID', 1656);
DEFINE('DISCENDANT_PROPERTY_ID', 1675);
DEFINE('NODEZ_CLASS_ID', 364);

DEFINE('MANAGE_PHASE_SEQUENCE', '806');
DEFINE('OPERATION_PHASE_CLASS_ID', '781');
DEFINE('PHASE_CLASS_ID', '782');
DEFINE('PHASE_DEAL_P_ID', '6885');
DEFINE('PHASE_PHASE_P_ID', '6886');
DEFINE('PHASE_ROLE_P_ID', '6887');
DEFINE('PHASE_STATUS_P_ID', '6888');
DEFINE('DEAL_PHASE_PROPERTY_ID', '7744');
DEFINE('DEAL_PHASE_VERSION_PROPERTY_ID', '7745');
DEFINE('PHASE_SEQUENCE', '7689');
DEFINE('COURSE_CLASS_ID', 435);
DEFINE('DIALOGUE_CLASS_ID', 179);
DEFINE('STATEMENT_CLASS_ID', 180);
DEFINE('DIALOGUE_TITLE_ID', 839);
DEFINE('SELECTOR_CLASS_ID', 199);
DEFINE('DECLARATION_CLASS_ID', 200);
DEFINE('RULESET_CLASS_ID', 201);
DEFINE('OPERATION_CLASS_ID', 661);
DEFINE('OPERATION_ROLE_CLASS_ID', 662);
DEFINE('MAPPING_ROLE_ACTOR_CLASS_ID', 663);
DEFINE('DEAL_PAYMENT_TYPE_PROPERTY_ID', 3231);
DEFINE('DEAL_DESIGNATION_PROPERTY_ID', 3230);
DEFINE('DEAL_TRADE_IN_PROPERTY_ID', 3229);
DEFINE('MAPPING_DEAL_OP_STATUS', 6354);
DEFINE('CSS_FILE_NODE_PROPERTY_ID', 450312);
DEFINE('DOCUMENT_TITLE', 'Document');
DEFINE('PDF_TITLE', 'PDF Template NID');
DEFINE('PDF_PROPERTY_ID', 5028);
DEFINE('NOTIFICATION_CLASS_ID', 671);
DEFINE('SITE_SUPPORT_EMAIL', 'admin@marinemax.com');
DEFINE('MAPPING_DEAL_OPERATION_CLASS_ID', 724);
DEFINE('OPERATION_DOCUMENT_UPLOADED_CLASS_ID', 849);
DEFINE('MAPPING_API_CLASS_ID', 768);
DEFINE('SUB_MAPPING_CLASS_ID', 769);
DEFINE('TARGET_PROPERTY_ID', 6312);
DEFINE('TARGET_PROPERTY_NAME', 6355);
DEFINE('OBSELETE_PROPERTY_ID', 6356);
DEFINE('DEAL_ROLE_CLASS_ID', 778);
DEFINE('DEAL_ROLE_USER_NODE_PROPERTY_ID', 6786);
DEFINE('DEAL_ROLE_NODE_PROPERTY_ID', 6787);
DEFINE('DEAL_EST_CLOSING_DATE_PROPERTY_ID', 6802);
DEFINE('DATA_SOURCE_PROPERTY_ID', 6795);
DEFINE('MANAGE_PHASE_SEQUENCE', 806);
DEFINE('DEAL_REJECT_CLASS_ID', 823);
DEFINE('DEAL_APPONE_CLASS_ID', 825);
DEFINE('DEAL_APPONE_APPID_PROPERTY_ID', 8029);
DEFINE('DEAL_APPONE_REQUEST_PROPERTY_ID', 8030);
DEFINE('DEAL_APPONE_RESPONSE_PROPERTY_ID', 8031);
DEFINE('MANAGE_CONTROL_CLASS_ID', 853);
DEFINE('MANAGE_CONTROL_ROLE_PROPERTY_ID', 8444);
DEFINE('IS_CURRENT_VERSION_PROPERTY_ID', 8446);
DEFINE('DEAL_CURRENT_VERSION_PROPERTY_ID', 8450);
DEFINE('DEAL_SIZE', 8748);
DEFINE('DEAL_NUMBER', 9090);

//DEFINE('PASSED_DEAL_BY_ROLES_CLS_ID',855);
//DEFINE('PASSED_DEAL_ROLE_PROPERTY_ID',8471);
//DEFINE('PASSED_DEAL_IS_ACTIVE_PROPERTY_ID',8474);
//DEFINE('PASSED_DEAL_ROLE_FROM_PROPERTY_ID',8472);
//DEFINE('PASSED_DEAL_ROLE_TO_PROPERTY_ID',8473);
//DEFINE('PASSED_DEAL_ROLE_TO_DEAL_ID',8473);



DEFINE('PASSED_DEAL_BY_ROLES_CLASS_ID', 855);
DEFINE('PASSED_DEAL_BY_ROLES_CLASS_NID', 1377982);
DEFINE('PASSED_DEAL_D_PID', 8454);
DEFINE('PASSED_DEAL_FR_PID', 8455);
DEFINE('PASSED_DEAL_TR_PID', 8456);
DEFINE('PASSED_DEAL_A_PID', 8457);
DEFINE('PASSED_DEAL_TIMESTAMP', 8749);

DEFINE('RA_MANAGER_COUNTER_CLASS_ID', 857);
DEFINE('RA_MANAGER_ROLE', 8751);
DEFINE('RA_MANAGER_ACTOR', 8752);
DEFINE('RA_MANAGER_COUNT', 8753);
DEFINE('RA_MANAGER_COUNTER', 24);


DEFINE('ROLE_BM', 450187);
DEFINE('ROLE_RA', 454674);
DEFINE('ROLE_RM', 454679);
DEFINE('ROLE_C', 1462795);
DEFINE('ROLE_D', 1462785);
DEFINE('ROLE_ADMIN', 8474);


/* For Only Node Z Class */
DEFINE('VERSION_Z', '16543');
DEFINE('CLASS_Z', '67905');
DEFINE('TAXONOMY_Z', '16525');
DEFINE('DATATYPE_Z', '16537');
DEFINE('FORM_SELECTOR_Z', '16539');
DEFINE('VALIDATION_Z', '16541');
DEFINE('NODE_RIGHTS_Z', '28048');
DEFINE('DATA_SOURCE_Z', '661473');
DEFINE('COLLAPSE_Z', '804675');

DEFINE('CUSTOMER_CLASS_ID', '770');
DEFINE('UNIT_CLASS_ID', '776');
DEFINE('FINANCE_DEALS_CLASS_ID', '801');
DEFINE('CUSTOMER_CLASS_NID', '601263');
DEFINE('UNIT_CLASS_NID', '641371');
DEFINE('OPERATION_PROPERTY_MAP_DEAL_CLASS_ID', '787');
DEFINE('CUSTOMER_PID', '7202');
DEFINE('STOCK_PID', '7203');
DEFINE('SALES_QUOTE_PID', '7204');
DEFINE('FI_QUOTE_PID', '7205');

// Used for pass the deal and operation permission
DEFINE('PASS_DEAL', '852');
DEFINE('MANAGE_CONTROL_CLASS_ID', '853');
DEFINE('OPERATION_ROLE_CONTROL', '854');
DEFINE('DEAL_CLASS', '655');



DEFINE('ROLE_SALES_CONSULTANT', '436104');  //Sales Consultant
DEFINE('ROLE_BUSINESS_MANAGER', '436099');  //Brokerage Consultant
DEFINE('ROLE_BM', '450187');                //Business manager
DEFINE('ROLE_TEAM_SUPPORT', '454669');      //TEAM SUPPORT
DEFINE('ROLE_SELLER', '454664');            //Seller
DEFINE('ROLE_BUYER', '454659');             //Buyer
DEFINE('ROLE_REVENUE_ACCOUNTANT', '454674'); //Revenue Accoutant
DEFINE('ROLE_REVENUE_MANAGER', '454679');   //Revenue Manager
DEFINE('ROLE_CONTROLLER', '1462795');   //Controller
DEFINE('ROLE_DIRECTOR', '1462785');   //Director

DEFINE('DEAL_FI_QUOTE_PID', '3228');
DEFINE('DEAL_STOCK_PID', '3216');
DEFINE('DEAL_STATUS_PID', '3287');
DEFINE('DEAL_SUB_STATUS_PID', '8848');

DEFINE('DEAL_TIMESTAMP_PID', 8913);
DEFINE('DEAL_ASSIGNED_PID', 8914);

//Role Id

DEFINE('BUSINESS_MANAGER', '450187');
DEFINE('REVENUE_ACCOUNTANT', '454674');
DEFINE('REVENUE_MANAGER', '454679');
DEFINE('CONTROLLER', '1462795');
DEFINE('DIRECTOR', '1462785');
DEFINE('DEAL_CREATOR_CLASS_ID', 778);

DEFINE('INDIVIDUAL_CLASS_ID', 632);
DEFINE('INDIVIDUAL_FIRST_NAME', 2921);
DEFINE('INDIVIDUAL_LAST_NAME', 2922);
DEFINE('ROLE_CLASS_ID', 633);
DEFINE('ACCOUNT_CLASS_ID', 634);

DEFINE('LOCATION_ROLE_DETAILS', '858');
DEFINE('OPERATION_ROLE', '662');

DEFINE('LOCATION_ROLE_LNID', '8755');
DEFINE('LOCATION_ROLE_RNID', '8756');
DEFINE('LOCATION_ROLE_ANID', '8757');
DEFINE('LOCATION_ROLE_L', '8758');
DEFINE('LOCATION_ROLE_R', '8759');
DEFINE('LOCATION_ROLE_A', '8760');
DEFINE('LOCATION_ROLE_E', '8761');

DEFINE('ROLE_PID', '3297');
DEFINE('ACTOR_PID', '3298');
DEFINE('DEAL_PID', '3299');
DEFINE('NODEZ_DATASOURCE_SEARCH_ARRAY', json_encode(array('#nbsp#', '#,#', '#-#')));
DEFINE('NODEZ_DATASOURCE_REPLACE_ARRAY', json_encode(array(' ', ', ', '-')));


DEFINE('DEALEROPTIONS_CLASS_ID', 794);
DEFINE('INSURANCES_CLASS_ID', 803);
DEFINE('VANTAGE2K_OPERATION_NID', '455684');
DEFINE('VANTAGE4K_OPERATION_NID', '1662711');


// Decline static file requests back to the PHP built-in webserver
if (php_sapi_name() === 'cli-server') {
    $path = realpath(__DIR__ . parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
    if (__FILE__ !== $path && is_file($path)) {
        return false;
    }
    unset($path);
}

// Setup autoloading
require 'init_autoloader.php';

// Run the application!
Zend\Mvc\Application::init(require 'config/application.config.php')->run();
