<?php
return array(
    'Administrator\Module'                                     => __DIR__ . '/../Module.php',
    'Administrator\MemorySharedManager'                        => __DIR__ . '/../src/Administrator/MemorySharedManager.php',
    'Administrator\StoragePluginManager'                       => __DIR__ . '/../src/Administrator/StoragePluginManager.php',
    'Administrator\Storage\Apc'                                => __DIR__ . '/../src/Administrator/Storage/Apc.php',
    'Administrator\Storage\Db'                                 => __DIR__ . '/../src/Administrator/Storage/Db.php',
    'Administrator\Storage\File'                               => __DIR__ . '/../src/Administrator/Storage/File.php',
    'Administrator\Storage\Memcached'                          => __DIR__ . '/../src/Administrator/Storage/Memcached.php',
    'Administrator\Storage\Memory'                             => __DIR__ . '/../src/Administrator/Storage/Memory.php',
    'Administrator\Storage\Segment'                            => __DIR__ . '/../src/Administrator/Storage/Segment.php',
    'Administrator\Storage\Session'                            => __DIR__ . '/../src/Administrator/Storage/Session.php',
    'Administrator\Storage\ZendShmCache'                       => __DIR__ . '/../src/Administrator/Storage/ZendShmCache.php',
    'Administrator\Storage\ZendDiskCache'                      => __DIR__ . '/../src/Administrator/Storage/ZendDiskCache.php',
    'Administrator\Storage\StorageInterface'                   => __DIR__ . '/../src/Administrator/Storage/StorageInterface.php',
    'Administrator\Storage\CapacityStorageInterface'           => __DIR__ . '/../src/Administrator/Storage/CapacityStorageInterface.php',
    'Administrator\Storage\Exception\ExceptionInterface'       => __DIR__ . '/../src/Administrator/Storage/Exception/ExceptionInterface.php',
    'Administrator\Storage\Exception\RuntimeException'         => __DIR__ . '/../src/Administrator/Storage/Exception/RuntimeException.php',
    'Administrator\Controller\Plugin\SimpleMemoryShared'       => __DIR__ . '/../src/Administrator/Controller/Plugin/SimpleMemoryShared.php',
);
