<table id="account-table" border="" style="border-collapse: collapse;" cellpadding="0" cellspacing="0">
  <thead>
    <tr class="row-0">
      <th class="ExcelTableFormationRow"> <div class="left-col"></div></th>
      <th class="ExcelTableFormationCol"><span class="top-col">1</span></th>
      <th class="HideSection mini-col"></th>
      <th class="ExcelTableFormationCol acntSecCol seller-only"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol HideSection seller-only" style="height:22px"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol acntSecCol"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol HideSection"><span class="top-col "></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol acntSecCol"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol acntSecCol"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse HideSection"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse balancecol"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse"><span class="top-col"></span></th>
      <th class="ExcelTableFormationCol collapse"><span class="top-col"></span></th>
    </tr>
    <tr class="row-1">
      <th class="ExcelTableFormationRow" > <div class="left-col">1</div>
      </th>
      <th class="ExcelTableFormationCol operationSection" data-section="operationSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Operation</span></div>
      </th>
      <th class="mini-col"></th>
      <th class="ExcelTableFormationCol acntSecCol seller-only" data-section="prospusSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Prospus</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection seller-only" data-section="prospusSection" style="height:22px"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Prospus</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only" data-section="prospusSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only" data-section="prospusSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only" data-section="prospusSection"> <div class="col-head "></div>
      </th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="indiaSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="indiaSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">India</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="indiaSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="indiaSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="indiaSection"> <div class="col-head "> <i class="fa fa-plus add"></i>
          <div class="add-col-wrap add-colums">
            <ul class="dropdown-menu ">
              <li role="presentation" class="disabled"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Left </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Domain </a> </li>
                </ul>
              </li>
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Right </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Domain </a>
                    <ul class="sub-item">
                        <li data-toggle="modal" data-target="right"> <a class="add-domain-node" data-node="Seller">
                        <div class="node-circle node-white-circle">N</div>
                        Seller Only </a></li>
                      <li data-toggle="modal" data-target="right"> <a class="add-domain-node" data-node="Buyer">
                        <div class="node-circle node-white-circle">N</div>
                        Buyer Only </a></li>
                      <li data-toggle="modal" data-target="right"> <a class="add-domain-node"  data-node="Seller-Buyer">
                        <div class="node-circle node-white-circle">N</div>
                        Seller-Buyer</a></li>
                      <li data-toggle="modal" data-target=""> <a class="add-domain-node"  data-node="Empty">
                        <div class="node-circle node-white-circle">N</div>
                        Empty</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li role="presentation" class="delete-li delete-domain"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete</a>
              </li>
            </ul>
          </div>
        </div>
      </th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="undefinedSellerBuyerSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="undefinedSellerBuyerSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title seller-buyer-section">Undefined</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="undefinedSellerBuyerSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="undefinedSellerBuyerSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="undefinedSellerBuyerSection"> <div class="col-head "> </div>
      </th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="undefinedSellerBuyerSection"> <div class="col-head"> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="undefinedSellerBuyerSection"> <div class="col-head"> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="undefinedSellerBuyerSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="undefinedSellerBuyerSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="undefinedSellerBuyerSection"> <div class="col-head "> <i class="fa fa-plus add"></i>
          <div class="add-col-wrap add-colums">
            <ul class="dropdown-menu ">
              <li role="presentation" class="disabled"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Left </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Domain </a> </li>
                </ul>
              </li>
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Right </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Domain </a>
                    <ul class="sub-item">
                      <li data-toggle="modal" data-target=""> <a class="add-domain-node" data-node="Seller">
                        <div class="node-circle node-white-circle">N</div>
                        Seller Only </a></li>
                      <li data-toggle="modal" data-target=""> <a class="add-domain-node" data-node="Buyer">
                        <div class="node-circle node-white-circle">N</div>
                        Buyer Only </a></li>
                      <li data-toggle="modal" data-target=""> <a class="add-domain-node" data-node="Seller-Buyer">
                        <div class="node-circle node-white-circle">N</div>
                        Seller-Buyer</a></li>
                      <li data-toggle="modal" data-target=""> <a class="add-domain-node" data-node="Empty">
                        <div class="node-circle node-white-circle">N</div>
                        Empty</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li role="presentation" class="delete-li delete-domain"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete</a>
              </li>
            </ul>
          </div>
        </div>
      </th>
      <th class="ExcelTableFormationCol collapse acntSecCol" data-section="undefinedbalanceSection"> <div class="col-head">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Balance</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse" data-section="undefinedbalanceSection"><div class="col-head "></div></th>
      <th class="ExcelTableFormationCol collapse" data-section="undefinedbalanceSection"><div class="col-head "></div></th>
    </tr>
    <tr class="row-1">
      <th class="ExcelTableFormationRow"><div class="left-col">2</div>
      </th>
      <th class="ExcelTableFormationCol blankRowTd operationSection" data-section="operationSection"> </th>
      <th class="mini-col"></th>
      <th class="ExcelTableFormationCol acntSecCol seller-only" data-section="universeSection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Seller</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection seller-only" data-section="universeSection" style="height:22px"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Seller</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only" data-section="universeSection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only" data-section="universeSection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only" data-section="universeSection"> <div class="col-head altColHead"></div>
      </th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="authoritySection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Authority</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="authoritySection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title indiaSection authoritySection-node">Authority</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="authoritySection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="authoritySection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="authoritySection">
          <div class="col-head altColHead"> <i class="fa fa-plus add"></i>
          <div class="add-col-wrap add-colums">
            <ul class="dropdown-menu ">
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add right </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-node" data-node="Authority">
                    <div class="node-circle node-white-circle">N</div>
                    Add Authority </a> </li>
                </ul>
              </li>
              <li role="presentation" class="delete-li delete-node"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete</a>
              </li>
            </ul>
          </div>
        </div>
      </th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="sellerSection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Seller</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="sellerSection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title undefinedSellerBuyerSection sellerSection-node">Seller</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="sellerSection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="sellerSection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="sellerSection"> <div class="col-head altColHead"> <i class="fa fa-plus add"></i>
          <div class="add-col-wrap add-colums">
            <ul class="dropdown-menu ">
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add right </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-node" data-node="Seller">
                    <div class="node-circle node-white-circle">N</div>
                    Add Seller </a> </li>
                </ul>
              </li>
              <li role="presentation" class="delete-li delete-node"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete</a>
              </li>
            </ul>
          </div>
        </div>
      </th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="buyerSection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Buyer</span> </div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="buyerSection"> <div class="col-head altColHead">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title undefinedSellerBuyerSection buyerSection-node">Buyer</span> </div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="buyerSection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="buyerSection"><div class="col-head altColHead"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="buyerSection"> <div class="col-head altColHead"> <i class="fa fa-plus add"></i>
          <div class="add-col-wrap add-colums">
            <ul class="dropdown-menu ">
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add right </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-node" data-node="Buyer">
                    <div class="node-circle node-white-circle">N</div>
                    Add Buyer </a> </li>
                </ul>
              </li>
              <li role="presentation" class="delete-li delete-node"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete</a>
              </li>
            </ul>
          </div>
        </div>
      </th>
      <th class="ExcelTableFormationCol collapse blankRowTd acntSecCol" data-section="balanceSection">
      </th>
      <th class="ExcelTableFormationCol collapse blankRowTd" data-section="balanceSection"></th>
      <th class="ExcelTableFormationCol collapse blankRowTd" data-section="balanceSection"></th>
    </tr>
    <tr class="row-2">
      <th class="ExcelTableFormationRow"> <div class="left-col">3</div>
      </th>
      <th class="ExcelTableFormationCol  acntSecCol blankRowTd"></th>
      <th class="mini-col"></th>
      <th class="ExcelTableFormationCol  creation-bg acntSecCol seller-only" data-section="subuniverseSection"> <div class="account-col-head  account-panel"></div>
      </th>
      <th class="ExcelTableFormationCol blankRowTd borderColor HideSection seller-only" data-section="subuniverseSection" style="height:22px"> <div class="account-col-head1  account-panel"></div>
      </th>
      <th class="ExcelTableFormationCol blankRowTd borderColor collapse HideSection seller-only" data-section="subuniverseSection"><div class="account-col-head1 account-panel"></div></th>
      <th class="ExcelTableFormationCol blankRowTd borderColor collapse HideSection seller-only" data-section="subuniverseSection"><div class="account-col-head1  account-panel"></div></th>
      <th class="ExcelTableFormationCol blankRowTd borderColor collapse HideSection seller-only" data-section="subuniverseSection"><div class="account-col-head1  account-panel"></div></th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="subauthoritySection"> <div class="account-col-head  account-panel">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span></div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="subauthoritySection"> <div class="account-col-head  account-panel">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span></div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subauthoritySection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subauthoritySection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subauthoritySection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="subsellerSection"> <div class="account-col-head account-panel">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span></div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="subsellerSection"> <div class="account-col-head account-panel">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span></div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subsellerSection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subsellerSection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subsellerSection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol acntSecCol" data-section="subbuyerSection"> <div class="account-col-head account-panel">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span></div>
      </th>
      <th class="ExcelTableFormationCol HideSection" data-section="subbuyerSection"> <div class="account-col-head account-panel">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Undefined</span></div>
      </th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subbuyerSection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection" data-section="subbuyerSection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol collapse HideSection " data-section="subbuyerSection"><div class="account-col-head  account-panel"></div></th>
      <th class="ExcelTableFormationCol blankRowTd borderTopErase collapse acntSecCol balance-border-left" data-section="subbalanceSection">
        <div class="account-col-head1 account-panel"></div>
      </th>

      <th class="ExcelTableFormationCol blankRowTd borderTopErase collapse" data-section="subbalanceSection"><div class="account-col-head1  account-panel"></div></th>
      <th class="ExcelTableFormationCol blankRowTd borderTopErase collapse" data-section="subbalanceSection"><div class="account-col-head1  account-panel"></div></th>
    </tr>
    <tr class="row-3">
      <th class="ExcelTableFormationRow "> <div class="left-col">4</div>
      </th>
      <th class="ExcelTableFormationCol  blankRowTd"></th>
      <th class="mini-col"></th>
      <th class="ExcelTableFormationCol blankRowTd acntSecCol seller-only"></th>
      <th class="ExcelTableFormationCol HideSection seller-only" style="height:22px"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Amount</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Debit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title acntSecCol">Credit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection seller-only"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Balance</span></div></th>
      <th class="ExcelTableFormationCol blankRowTd acntSecCol"></th>
      <th class="ExcelTableFormationCol HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Amount</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Debit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Credit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Balance</span></div></th>
      <th class="ExcelTableFormationCol blankRowTd acntSecCol"></th>
      <th class="ExcelTableFormationCol HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Amount</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Debit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Credit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Balance</span></div></th>
      <th class="ExcelTableFormationCol blankRowTd acntSecCol"></th>
      <th class="ExcelTableFormationCol HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Amount</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Debit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Credit</span></div></th>
      <th class="ExcelTableFormationCol collapse HideSection"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Balance</span></div></th>
      <th class="ExcelTableFormationCol acntSecCol collapse"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Debit</span></div></th>
      <th class="ExcelTableFormationCol collapse"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Credit</span></div></th>
      <th class="ExcelTableFormationCol collapse"><div class="account-col-head col-highlight">
          <div class="node-circle node-white-circle">N</div>
          <span class="account-head-title">Balance</span></div></th>
    </tr>
  </thead>
  <tbody>
    <tr class="row-4 row-group row-fees">
      <td class="ExcelTableFormationRow"><div class="left-col">5</div></td>
      <td class="ExcelTableFormationCol"><div class="account-head-node">
          <div class="node-circle node-white-circle node-white-circle-expanded">N</div>
          <div class="account-title fee-title"><strong>Base Fee</strong></div>
          <i class="fa fa-bars segment"></i>
          <div class="add-col-wrap add-segment">
            <ul class="dropdown-menu">
              <li role="presentation" class="disabled"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Above </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-transaction" data-sequence="above">
                    <div class="node-circle node-white-circle">N</div>
                    Transaction </a> </li>
                </ul>
              </li>
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Below </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-transaction" data-sequence="below">
                    <div class="node-circle node-white-circle">N</div>
                    Transaction </a> </li>
                </ul>
              </li>
              <li class="disabled" role="presentation"> <a class="delete-transaction">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete Transaction </a> </li>
            </ul>
          </div>
        </div></td>
      <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px">
          <div class="account-node universe account-node-select" style="display:none">
          <select name="" class="hide calculate-option">
            <option value="Fixed">Fixed</option>
            <option value="Percentage">Percentage</option>
            <option value="Calculation" disabled>Calculation</option>
          </select>
          <input type="text" class="hide calculate-amount full-width" placeholder="10" />
          <i class="fa fa-plus add" style="display:none;"></i>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only ">
          <div class="account-node">
              <input type="checkbox" value="debit" name="chkDebit">
              <label></label>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
          <div class="account-node">
              <input type="checkbox" value="credit" name="chkCredit">
              <label></label>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection">
        <div class="account-node universe account-node-select" style="display:none">
            <select name="" class="hide calculate-option">
                <option value="Fixed">Fixed</option>
                <option value="Percentage">Percentage</option>
                <option value="Calculation" disabled>Calculation</option>
            </select>
            <input type="text" class="hide calculate-amount full-width" placeholder="10" />
            <i class="fa fa-plus add" style="display:none;"></i>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse  HideSection">
          <div class="account-node">
              <input type="checkbox" value="debit" name="chkDebit">
              <label></label>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse  HideSection">
          <div class="account-node">
              <input type="checkbox" value="credit" name="chkCredit">
              <label></label>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection">
          <div class="account-node account-node-select" style="display:none">
            <select name="" class="hide calculate-option">
              <option value="Fixed">Fixed</option>
              <option value="Percentage">Percentage</option>
              <option value="Calculation" disabled>Calculation</option>
            </select>
            <input type="text" class="hide calculate-amount full-width" placeholder="10" />
            <i class="fa fa-plus add" style="display:none;"></i>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkDebit" type="checkbox" value="debit" />
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkCredit" type="checkbox" value="credit"/>
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection">
          <div class="account-node account-node-select" style="display:none">
            <select name="" class="hide calculate-option">
              <option value="Fixed">Fixed</option>
              <option value="Percentage">Percentage</option>
              <option value="Calculation" disabled>Calculation</option>
            </select>
            <input type="text" class="hide calculate-amount full-width" placeholder="10" />
            <i class="fa fa-plus add" style="display:none;"></i>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkDebit" type="checkbox" value="debit"/>
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkCredit" type="checkbox" value="credit"/>
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse balancecol creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
    </tr>
    <tr class="row-5 row-share-percentage">
      <td class="ExcelTableFormationRow"><div class="left-col">6</div></td>
      <td class="ExcelTableFormationCol"><div class="account-node-gap">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Share(%)</div>
        </div></td>
      <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol HideSection creation-bg seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection custom-border seller-only">
          <div class="account-node" style="display:none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
            <span>%</span>
            <input type="text" class="hide share-percentage-debit" placeholder="0" />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection custom-border seller-only">
          <div class="account-node" style="display:none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>%</span>
            <input type="text" class="hide share-percentage-credit" placeholder="0" />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection custom-border">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>%</span>
              <input type="text" class="hide share-percentage-debit" placeholder="0" />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection custom-border">
      <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>%</span>
                <input type="text" class="hide share-percentage-credit" placeholder="0" />
            </div>
        </div>    
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol "></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-border HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>%</span>
              <input type="text" class="hide share-percentage-debit" placeholder="0" />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-border HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>%</span>
              <input type="text" class="hide share-percentage-credit" placeholder="0" />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-border HideSection">
          <div class="account-node" style="display:none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>%</span>
            <input type="text" class="hide share-percentage-debit" placeholder="0" />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg custom-border collapse HideSection ">
          <div class="account-node" style="display:none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>%</span>
            <input type="text" class="hide share-percentage-credit" placeholder="0" />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse balancecol creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
    </tr>
    <tr class="row-6 row-share">
      <td class="ExcelTableFormationRow"><div class="left-col">7</div></td>
      <td class="ExcelTableFormationCol"><div class="account-node-gap">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Share($)</div>
        </div></td>
       <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only">
          <div class="account-node" style="display:none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="hide share-debit" placeholder="0.00" readonly />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only">
          <div class="account-node" style="display:none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="hide share-credit" placeholder="0.00" readonly />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
            <div class="account-node" style="display:none">
                <div class="node-circle node-white-circle">N</div>
                <div class="account-txt">
                <span>$</span>
                    <input type="text" class="hide share-debit" placeholder="0.00" readonly />
                </div>
            </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide share-credit" placeholder="0.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
        <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide share-debit" placeholder="0.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide share-credit" placeholder="0.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide share-debit" placeholder="0.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg collapse HideSection ">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide share-credit" placeholder="0.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg balancecol collapse"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
    </tr>
    <tr class="row-7 row-distribution">
      <td class="ExcelTableFormationRow"><div class="left-col">8</div></td>
      <td class="ExcelTableFormationCol"><div class="account-node-gap">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Distribution</div>
        </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide distribution-debit" placeholder="100.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide distribution-debit" placeholder="100.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide distribution-debit" placeholder="100.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg collapse HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide distribution-debit" placeholder="100.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg collapse HideSection">
          <div class="account-node" style="display:none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
                <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg collapse HideSection"></td>
      <td class="ExcelTableFormationCol collapse balancecol">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-distribution-debit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-distribution-credit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-distribution-balance" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
    </tr>
    <tr class="row-8 row-balance">
      <td class="ExcelTableFormationRow"><div class="left-col">9</div></td>
      <td class="ExcelTableFormationCol balanceAlign"><div class="account-node-gap1">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Balance</div>
        </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse custom-bg-border  HideSection seller-only">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-debit" placeholder="0.00" readonly />
          </div>
         </div>
      </td>
      <td class="ExcelTableFormationCol collapse custom-bg-border HideSection seller-only">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-credit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-balance" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse custom-bg-border HideSection">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-debit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse custom-bg-border HideSection">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-credit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse  HideSection">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-balance" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse custom-bg-border HideSection">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-debit" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse custom-bg-border HideSection">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-credit" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse custom-bg-border HideSection">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-balance" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-debit" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-bg-border HideSection">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-credit" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-balance" placeholder="0.00" readonly />
          </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse balancecol">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-total-debit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-total-credit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-total-balance" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
    </tr>
    <tr class="row-9 row-group row-fees">
      <td class="ExcelTableFormationRow"><div class="left-col">10</div></td>
      <td class="ExcelTableFormationCol"><div class="account-head-node">
          <div class="node-circle node-white-circle node-white-circle-expanded">N</div>
          <div class="account-title fee-title"><strong>Universal Fee</strong> </div>
          <i class="fa fa-bars segment "></i>
          <div class="add-col-wrap add-segment">
            <ul class="dropdown-menu">
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Above </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-transaction" data-sequence="above">
                    <div class="node-circle node-white-circle">N</div>
                    Transaction </a> </li>
                </ul>
              </li>
              <li role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Add Below </a>
                <ul class="sub-item">
                  <li data-toggle="modal" data-target=""> <a class="add-transaction" data-sequence="below">
                    <div class="node-circle node-white-circle">N</div>
                    Transaction </a> </li>
                </ul>
              </li>
              <li class="disabled" role="presentation"> <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                Delete Transaction </a> </li>
            </ul>
          </div>
        </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol HideSection seller-only" style="height:22px"><div class="account-node universe account-node-select">
          <select name="" class="calculate-option">
            <option value="Fixed">Fixed</option>
            <option value="Percentage">Percentage</option>
            <option value="Calculation" disabled>Calculation</option>
          </select>
          <input type="text" class="calculate-amount full-width" placeholder="10" />
          <i class="fa fa-plus add" style="display:none;"></i> </div></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only"><div class="account-node">
          <input name="chkDebit" type="checkbox" checked="checked" value="debit" disabled="disabled" />
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only"><div class="account-node">
          <input name="chkCredit" type="checkbox" value="credit" disabled="disabled" />
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkDebit" type="checkbox" value="debit" disabled="disabled" />
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkCredit" type="checkbox" value="credit"/>
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse  HideSection"><div class="account-node">
          <input name="chkDebit" type="checkbox" value="debit" disabled="disabled" />
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkCredit" type="checkbox" value="credit"/>
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkDebit" type="checkbox" value="debit" disabled="disabled" />
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection"><div class="account-node">
          <input name="chkCredit" type="checkbox" value="credit"/>
          <label></label>
        </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse balancecol creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
    </tr>
    <tr class="row-10 row-share-percentage">
      <td class="ExcelTableFormationRow"><div class="left-col">11</div></td>
      <td class="ExcelTableFormationCol"><div class="account-node-gap">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Share(%)</div>
        </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg custom-border HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
            <div class="account-node">
                <div class="node-circle node-white-circle">N</div>
                <div class="account-txt">
                <span>%</span>
                  <input type="text" class="share-percentage-debit" placeholder="0" />
                </div>
            </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-border HideSection seller-only"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-border HideSection"></td>
      <td class="ExcelTableFormationCol collapse  custom-border creation-bg HideSection">
          <div class="account-node" style="display: none">
                <div class="node-circle node-white-circle">N</div>
                <div class="account-txt">
                <span>%</span>
                  <input type="text" class="hide share-percentage-credit" placeholder="0" />
                </div>
            </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse custom-border creation-bg  HideSection"></td>
      <td class="ExcelTableFormationCol collapse custom-border creation-bg HideSection">
          <div class="account-node" style="display: none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>%</span>
            <input type="text" class="hide share-percentage-credit" placeholder="0" />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg custom-border HideSection"></td>
      <td class="ExcelTableFormationCol collapse custom-border creation-bg HideSection">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>%</span>
              <input type="text" class="hide share-percentage-credit" placeholder="0" />
            </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse balancecol creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
    </tr>
    <tr class="row-11 row-share">
      <td class="ExcelTableFormationRow"><div class="left-col">12</div></td>
      <td class="ExcelTableFormationCol"><div class="account-node-gap">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Share($)</div>
        </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
          <div class="account-node">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="share-debit" placeholder="0.00" readonly />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg  HideSection">
           <div class="account-node" style="display: none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="hide share-credit" placeholder="0.00" readonly />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg  HideSection">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide share-credit" placeholder="0.00" readonly />
            </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide share-credit" placeholder="0.00" readonly />
            </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg balancecol collapse"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
      <td class="ExcelTableFormationCol collapse creation-bg"></td>
    </tr>
    <tr class="row-12 row-distribution">
      <td class="ExcelTableFormationRow"><div class="left-col">13</div></td>
      <td class="ExcelTableFormationCol"><div class="account-node-gap">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Distribution</div>
        </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
            <div class="account-node">
                <div class="node-circle node-white-circle">N</div>
                <div class="account-txt">
                <span>$</span>
                  <input type="text" class="distribution-debit" placeholder="100.00" readonly />
                </div>
            </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display: none">
                <div class="node-circle node-white-circle">N</div>
                <div class="account-txt">
                <span>$</span>
                  <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
                </div>
            </div>
      </td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg  HideSection">
          <div class="account-node" style="display: none">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
          </div>
        </div>
      </td>
      <td class="ExcelTableFormationCol collapse HideSection creation-bg "></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse creation-bg HideSection">
          <div class="account-node" style="display: none">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="hide distribution-credit" placeholder="100.00" readonly />
            </div>
          </div></td>
      <td class="ExcelTableFormationCol creation-bg collapse HideSection"></td>
      <td class="ExcelTableFormationCol collapse balancecol">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-distribution-debit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-distribution-credit" placeholder="0.00" readonly />
            </div>
            </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-distribution-balance" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
    </tr>
    <tr class="row-13 row-balance">
      <td class="ExcelTableFormationRow"><div class="left-col">14</div></td>
      <td class="ExcelTableFormationCol balanceAlign">
          <div class="account-node-gap1">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-title">Balance</div>
          </div></td>
        <td class="mini-col"></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol seller-only"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection seller-only" style="height:22px"></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-debit" placeholder="0.00" readonly />
            </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-credit" placeholder="0.00" readonly />
            </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse HideSection seller-only">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="total-balance" placeholder="0.00" readonly />
            </div>
          </div></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse HideSection">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-debit" placeholder="0.00" readonly />
          </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-credit" placeholder="0.00" readonly />
          </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-balance" placeholder="0.00" readonly />
          </div>
          </div></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-debit" placeholder="0.00" readonly />
          </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-credit" placeholder="0.00" readonly />
          </div>
          </div></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-balance" placeholder="0.00" readonly />
          </div>
        </div></td>
      <td class="ExcelTableFormationCol creation-bg acntSecCol"></td>
      <td class="ExcelTableFormationCol creation-bg HideSection"></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-debit" placeholder="0.00" readonly />
          </div>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-credit" placeholder="0.00" readonly />
          </div>
        </div></td>
      <td class="ExcelTableFormationCol collapse HideSection custom-bg-border">
          <div class="account-node total">
          <div class="node-circle node-white-circle">N</div>
          <div class="account-txt">
          <span>$</span>
            <input type="text" class="total-balance" placeholder="0.00" readonly />
          </div>
        </div></td>
      <td class="ExcelTableFormationCol collapse balancecol">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-total-debit" placeholder="0.00" readonly />
            </div>
         </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-total-credit" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
      <td class="ExcelTableFormationCol collapse">
          <div class="account-node total">
            <div class="node-circle node-white-circle">N</div>
            <div class="account-txt">
            <span>$</span>
              <input type="text" class="final-total-balance" placeholder="0.00" readonly />
            </div>
          </div>
      </td>
    </tr>
  </tbody>
</table>
