<style>
.showing1 {
    position: absolute !important;
    left: 1.859375px !important;
    top: -2px !important;
    display: inline-block !important;
}

</style>
<div class="fixed-top-header">
    <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
      <tbody>
        <tr class="row-0">
          <td class="ExcelTableFormationRow"><div class="left-col"></div></td>
          <td class="ExcelTableFormationCol col-1 collapse"><span class="top-col">1</span></td>
          <td class="ExcelTableFormationCol collapse event col-2"><span class="top-col">2</span></td>
          <td class="ExcelTableFormationCol col-3"><span class="top-col">3</span></td>
          <td class="ExcelTableFormationCol collapse event col-4"><span class="top-col">4</span></td>
          </tr>
      </tbody>
    </table>
</div>
<table class="fixed-left-column" border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
<tbody>

  <tr class="row-0">
    <td class="ExcelTableFormationRow"><div class="left-col"></div></td>
    <td class="ExcelTableFormationCol col-1 collapse"><span class="top-col">1</span></td>
    <td class="ExcelTableFormationCol collapse event col-2"><span class="top-col">2</span></td>
    <td class="ExcelTableFormationCol col-3"><span class="top-col">3</span></td>
    <td class="ExcelTableFormationCol collapse event col-4"><span class="top-col">4</span></td>
    
    
    
  </tr>
  
  <tr class="row-1">
    <td class="ExcelTableFormationRow"><div class="left-col">1</div></td>
    <td class="ExcelTablerow col-1 collapse"><div data-id="1" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon time-icon"></span><span class="col-head-title">Timeline</span><i class="fa fa-caret-left arrow rotate"></i> </div></td>
    <td class="ExcelTablerow col-2 collapse event "><div data-id="2" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> </div></td>
    <td class="col-3"><div data-id="3" class="col-head"><div class="node-circle node-white-circle node-white-circle">N</div>
        <span class="icon process-icon"></span><span class="col-head-title col-head-assoc">Associations</span><i class="fa fa-caret-left arrow"></i> </div></td>
    <td class="col-4"></td>
  </tr>
  
  <tr class="row-2">
    <td class="ExcelTableFormationRow"><div class="left-col">2</div></td>
    <td class="ExcelTablerow col-1"><div class="">
        <div class="time-col"> <span class="doted-border"></span>
          <div class="node-circle node-white-sm-circle">N</div>
          <span class="col-text"> 
          <span class="col-node-text custom-node"></span>
        </span> </div>
      </div></td>      
    <td class="ExcelTablerow col-2 collapse event">
      <div class="creation-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <span class="col-text"> <span class="creation"></span> 
        <span class="col-node-text custom-node">Creation</span>
       </span>
      </div>
    </td>
	<td class="ExcelTablerow col-3 creation-bg"><div class="blank-div segment-node"></div></td>
    <td class="col-4"></td>
  </tr>
  
  <tr class="row-3">
    <td class="ExcelTableFormationRow"><div class="left-col">3</div></td>
    <td class="ExcelTablerow col-1">
    <div class="blank-div segment-node borderDashed"></div>
    </td>      
    <td class="ExcelTablerow col-2 creation-bg collapse event">
      <div class="blank-div segment-node"></div>
    </td>
    
   <td class="ExcelTablerow col-3 border-light-top">
   	<div class="creation-node">
            <div class="node-circle node-white-circle node-white-circle">N</div>
            <div class="col-text"><span class="col-node-text custom-node">Membership.Process</span></div>
        </div>
   </td>
    <td class="col-4"></td>
  </tr>
  
    <tr class="row-4">
    <td class="ExcelTableFormationRow"><div class="left-col">4</div></td>
    <td class="ExcelTablerow col-1">
    <div class="blank-div segment-node borderDashed"></div>
    </td>      
    <td class="ExcelTablerow col-2 creation-bg collapse event">
      <div class="blank-div segment-node"></div>
    </td>
	<td class="ExcelTablerow col-3 creation-bg"><div class="blank-div segment-node"><span>...</span></div></td>
    <td class="col-4"></td>
  </tr>
  
  
     <tr class="row-5">
    <td class="ExcelTableFormationRow"><div class="left-col">5</div></td>
    <td class="ExcelTablerow col-1">
    <div class="blank-div segment-node borderDashed"></div>
    </td>      
    <td class="ExcelTablerow col-2 border-light-top collapse event">
      <div class="creation-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <div class="col-text"> <span class="destructure"></span>
           <span class="col-node-text custom-node">Destruction</span> 
         </div>
      </div>
    </td>
	<td class="ExcelTablerow col-3 border-light-top">
    <!--<i class="fa fa-plus add add-phase-segment" style="
    display: block;
    top: 1px;
"></i>-->
    <div class="creation-node">
            <div class="node-circle node-white-circle node-white-circle">N</div>
            <div class="col-text"><span class="col-node-text custom-node ">PreAssociation.Process</span></div>
    </div>
   <!-- <div class="add-col-wrap add-colums ">
            <ul class="dropdown-menu show-5 show" style="position: absolute;top: -21px;left: 21px;">
              <li role="presentation" class=""> 
              <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                ACTIONS </a>
                <ul class="sub-item">
                  <li data-target="" data-toggle="modal"> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Associate </a> </li>
                  <li class=""> <a href="#" class="">
                    <div class="node-circle node-white-circle">N</div>
                    Authenticate </a> </li>
                    
                    <li class=""> <a href="#" class="">
                    <div class="node-circle node-white-circle">N</div>
                    Forgot Password </a> </li>
                </ul>
              </li>
            </ul>
      </div>-->
    <i class="fa fa-plus add add-phase-segment show iconTest"></i>
    <div class="add-col-wrap add-colums test showing">
            <ul class="dropdown-menu show-5" >
             <li role="presentation" class=""> 
              <a class="add-right">
                <div class="node-circle node-white-circle-expanded">N</div>
                ACTIONS </a>
                <ul class="sub-item">
                  <li data-target="" data-toggle="modal"> <a class="">
                    <div class="node-circle node-white-circle">N</div>
                    Associate </a> </li>
                  <li class=""> <a href="#" class="">
                    <div class="node-circle node-white-circle">N</div>
                    Authenticate </a> </li>
                    
                    <li class=""> <a href="#" class="">
                    <div class="node-circle node-white-circle">N</div>
                    Forgot Password </a> </li>
                </ul>
              </li>
            </ul>
      </div>  
     </td>
    <td class="col-4"></td>
  </tr>
  

  
  
  
  
  
</tbody>
</table>
<script>
// for testing purpose
$(document).ready(function(){
	
	$('.iconTest').siblings().find('ul.dropdown-menu').addClass('showing1');
	$('.iconTest').click(function(){
	  $(this).siblings().find('ul.dropdown-menu').removeClass('showing1');
	  $(this).siblings().find('ul.dropdown-menu').toggleClass('showing');
	});
});

$('body').click(function(e){
   $('.dropdown-menu').removeClass('showing1');
});
</script>
