<!-- start preview template-->
<!--comment-for-file-type-attached-->
<div id="custom-preview-template" style="display:none">
  <div class="dz-preview dz-file-preview logoFrame">
    <div class="dz-image"><img data-dz-thumbnail /></div>
    <div class="dz-progress">
      <a href="javascript:void(0)" target="_blank" class="canvas_view_mode">
        <canvas id="my_canvas" data-dz-uploadprogress height="40" width="40"></canvas>
      </a>
    </div>
    <div class="dz-details right_margin">
      <div class="dz-filename"><span data-dz-name></span></div>
      <div class="dz-size"><span data-dz-size></span></div>
    </div>
    <span class="dialogue-date right"><ul><li>3:32 PM</li></ul></span>

    <div class="dz-error-message connection_notif">

      <span class="connect_wrap">
      <i class="icon connection_error"></i>
      <span data-dz-errormessage class="errMsg notif_title"> </span>
      </span>

    </div>
    <div class="dz-success-mark"></div>
    <div class="dz-error-mark">
      <title>Error</title>
    </div>
  </div>
</div>
<!--comment-for-file-type-attached-->
<!-- End preview template-->
