<!-- HEADER STARTS --> 
<!doctype html>
<html >

    <head>
        <meta charset="utf-8">
        <meta name="format-detection" content="telephone=no">        
        <!--        <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0'>

        <meta http-equiv="X-UA-Compatible" content="IE=edge; chrome=1; IE=11; IE=10; IE=9; IE=8; IE=7">
        <meta http-equiv="Cache-control" content="public">
        <title>VesselWise</title>

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"><!-- added on 1 Dec for calendar in setting section -->

       
        <!--  <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workflow/bootstrap.min.css"> -->
          <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workflow/nanoscroller.css">
       <!--  <link rel="stylesheet" href="css/form-field.css" /> -->
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workflow/demo.css">
      
         <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workflow/workflow-style.css">
        <!--<style type="text/css">

            .icon {
                background: url("<?php /*echo $this->basePath(); */?>/img/workflow/all_icons.svg");
            }
            .icon-input, .icon-input:active {
                background-image: url("<?php /*echo $this->basePath(); */?>/img/workflow/all_icons.svg");
            }
        </style>-->

        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/jquery-ui.js"></script>
   <!--      <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/bootstrap.min.js"></script> -->
        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/ui_flayout.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/ui_flyout_common.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/jquery.nanoscroller.js"></script>

    </head>
    <body class="body-home" id="Ref-workflow">
<!-- HEADER ENDS --> 

<!-- WORKFLOW STARTS --> 

    <!-- <link rel="stylesheet" href="css/jsplumb.css"> -->
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workflow/demo.css">
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workflow/jsplumb.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/workflow/jquery.mCustomScrollbar.css">
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/workflow/jquery.mCustomScrollbar.concat.min.js"></script> 




    <!-- ================= Workflow ======================= -->
    <div id="Ref-workflow" class="workflow-container">
        <div class='hidden-ViewWorkflow' style="display:none;"></div>
        <div class="workflow-wrapper clearfix">
            <div class="workflow-item-section" style="display:none;">
                <div class="operation-item operation-head">
                    <button type="button" class="btn btn-default btn-back">Back</button>
                </div>
                <div class="operation-status">
                    <button type="button" class="btn btn-default">Define Survey</button>
                    <button type="button" class="btn btn-white">Ongoing Survey</button>
                    <button type="button" class="btn btn-default">Draft Survey</button>
                    <button type="button" class="btn btn-default">Closed Survey</button>
                </div>
            </div>                                            
            <div class="workflow-sidebar">

                <div class="operation-item operation-head clearfix">
                    <span class="title">Phases</span>
                    <span class="addPhase right phaseAddBtn">
                        <i class="icon added"></i>
                    </span>
                </div>
                <ul class="operation-wrap kumark clearfix" id="default-phase">

                </ul> <!-- operation-wrap ends -->
            </div><!-- workflow-sidebar ends -->

            <div class="workflow-editor hor-scroll vw-nicescroll">
                <div class="scroll-content">
                    <div class="workflow-survey-section rolesWorkflow" parentcontainer="">
                        <div class="workflow-action-col " >
                            <div class="operation-item operation-head clearfix" id="operationId">
                                <div class="wf-wrap default-admin" id="section1">
                                    <div class="wf-role btn btn-default dropdown">
                                        <div class="clearfix" href="#" data-toggle="dropdown">
                                            <span class="left">System Administrator</span>
                                            <i class="icon small-close right section-close"></i>
                                            <i class="fa fa-angle-down right wf-arrow"></i>
                                        </div>
                                        <ul role="menu" class="dropdown-menu role-count wf-dropdown">
                                            <li class=""><a class="roles" href="#">Vessel Administrator</a></li>  
                                            <li class=""><a class="roles" href="#">Survey Administrator</a></li>
                                            <li class=""><a class="roles" href="#">Organization Administrator</a></li>
                                            <li class=""><a class="roles" href="#">Vessel Owner</a></li>
                                            <li class=""><a class="roles" href="#">Vessel Crew</a></li>
                                            <li class=""><a class="roles" href="#">Vessel Guest</a></li>
                                            <li class=""><a class="roles" href="#">Observer</a></li>
                                            <li class=""><a class="roles" href="#">Surveyor</a></li>
                                            <li class=""><a class="roles" href="#">Sales Representative</a> </li>                                                                      

                                        </ul>
                                    </div>
                                    <div class="wf-count btn btn-default dropdown">
                                        <div class="clearfix" href="#" data-toggle="dropdown">
                                            <span class="left">1 </span>
                                            <i class="fa fa-angle-down right"></i>
                                        </div>
                                        <ul  role="menu" class="dropdown-menu role-count">
                                            <li class="">
                                                <a class="roles" href="#">1</a>   
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="wf-hover-area">
                                        <div class="propBtn show-popup hide" data-target="#add-workflow-note" data-open="add-workflow-note" onclick="javascript:setModalName(this)"></div>
                                    </div>
                                </div>
                                <div class="add-role default-exe" >
                                    <i class="icon added"></i>
                                </div>
                            </div>
                            <!--   <div class="operation-item">
                                                                                          
                            </div>  -->
                            <div class="workflow-action-block">
                                <div class="nano workflow-nano">
                                    <div class="nano-content">
                                        <div class="demo statemachine-demo" id="statemachine-demo">
                                            <!-- <button type="button" id="addwindow">Add Window</button> -->
                                            <div class="w" id="opened" style="display:none;">BEGIN&nbsp;
                                                <div class="ep" style="display:none;"></div>
                                            </div>


                                            <div class="w hidden " id="template_newwindow">
                                                <div class="ep"></div>
                                            </div>
                                            <div class="newDivAppend kumark">
                                            </div>   
                                            <div class="absLine absLinePos1" sectionid="section1" style="left: 0px;"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!-- workflow-editor ends -->
        </div><!-- workflow-wrapper ends -->


    <!-- FOOTER STARTS --> 

        <div id="add-workflow-note"  class="popup-wrapper overthrow3 no-border-form workflow-wrap">
        <div class="popup-body clearfix" id="add-workflow">  
        </div>
        </div>

        </body>
        </html>
    <!-- container fluid ends -->


    <!-- FOOTER ENDS --> 


    
    </div> <!-- Workflow container end -->





    <!-- ================= Workflow Ends ======================= -->



    <script type="text/javascript">

        $(document).ready(function () {
            $(".nano").nanoScroller();
            $('body').on("click", ".close-btn", function (event) {
                $(this).toggleClass("close-btn-close");
            });
            loadWorkFlow();
        });

    </script>

    



    <!--    <script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
        <script src="js/external/jquery-ui-1.9.2.min.js"></script> -->

    <!-- JS -->
    <!-- support lib for bezier stuff -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/lib/jsBezier-0.6.js"></script>
    <!-- event adapter click event -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/lib/mottle-0.4.js"></script>
    <!-- geom functions for relation -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/lib/biltong-0.2.js"></script>
    <!-- jsplumb util -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/util.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/browser-util.js"></script>
    <!-- base DOM adapter -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/dom-adapter.js"></script>
    <!-- main jsplumb engine -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/jsPlumb.js"></script>
    <!-- endpoint -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/endpoint.js"></script>
    <!-- connection -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/connection.js"></script>
    <!-- anchors -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/anchors.js"></script>
    <!-- connectors, endpoint and overlays  -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/defaults.js"></script>
    <!-- bezier connectors -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/connectors-bezier.js"></script>
    <!-- state machine connectors -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/connectors-statemachine.js"></script>
    <!-- flowchart connectors -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/connectors-flowchart.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/connector-editors.js"></script>
    <!-- SVG renderer -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/renderers-svg.js"></script>

    <!-- vml renderer -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/renderers-vml.js"></script>


    <!-- common adapter -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/base-library-adapter.js"></script>
    <!-- jquery jsPlumb adapter -->
    <script src="<?php echo $this->basePath(); ?>/js/workflow/src/jquery.jsPlumb.js"></script>
    <!-- /JS -->

    <!--  demo code -->

    <script src="<?php echo $this->basePath(); ?>/js/workflow/jquery.nicescroll.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/workflow/workflow_editor.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/workflow/workflow.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/workflow/workflow-process.js"></script>

    <script>
        // (function($){
        //     $(window).load(function(){
        //         $('body .hor-scroll').mCustomScrollbar({
        //             axis:"x",
        //             theme:"dark"
        //         });
        //     });
        // })(jQuery);
  

        (function ($) {
            $(".vw-nicescroll").niceScroll({
                cursorcolor: "#7E7E7E",
                cursorborder: "0",
                cursorborderradius: '0',
                cursorwidth: "4px",
                background: 'rgba(0,0,0,.25)'
            });
        })(jQuery);

    </script>
<!-- WORKFLOW ENDS --> 

