<?php  
$verifyLink = SOCKET_HOST_NAME .'login/addParticipant?token='.$this->encoded_url;
echo $this->header;
$html = '<tr><td style="font:13px Arial, Helvetica, sans-serif; color:#333333">Hello, '.$this->toFirstName .'.</td>
                                  </tr><tr><td style="height:20px;">&nbsp;</td></tr><tr>'
                        . '<td style="font:13px Arial, Helvetica, sans-serif; color:#333333">'
                        . $this->adminName.' has created <b>'.$this->courseTitle.'</b> course with you as <b>'.$this->toRoleName.'</b>. Other actors are:'
                        . '</td>'
                        . '</tr>';
                        $html.='<tr><td>&nbsp;</td></tr>';
                        $actorRoleArr = $this->roles;
                        foreach($actorRoleArr as $actors){
                            if($this->toActorID!= $actors["actorID"]){
                                $html.='<tr><td style="font:13px Arial, Helvetica, sans-serif; color:#333333">'. $actors["actorName"].' as '.$actors["role"].'</td></tr>';
                            }
                          
                        }
                        $html.='<tr><td>&nbsp;</td></tr>';
                        $html.='<tr><td>&nbsp;</td></tr>';
                        $html.='<tr><td>&nbsp;</td></tr>';
                        $html.='<tr><td><a style="color: #fff; text-decoration: none; padding: 8px 20px; background: #49a9fa; border-radius: 2px; font-size: 14px; margin-right: 10px;" href="' . $verifyLink . '">Login</a></td></tr>';
                        $html.='<tr><td>&nbsp;</td></tr>';
                        $html.='<tr>';
              
    
echo $html;
echo $this->footer;
?>