<?php    
$htmlFooter =   '<tr><td style="height:20px;"></td></tr>'
                . '<tr>'
                . '<td style="font:13px Arial, Helvetica, sans-serif; color:#333333;">
                    Regards,<br>Team Prospus
                    </td>'
                . '</tr>'
                . '<tr><td style="height:34px;"></td></tr>'
                . '</table></td><td>&nbsp;</td></tr></table></td></tr>'
                . '<tr><td style="height:34px;"></td></tr>'
                . '<tr><td align="center" valign="top" style="font:11px Arial, Helvetica, sans-serif; color:#666666; height:20px"> &copy; ' . date('Y') . ' Prospus – A leading IT company | All rights reserved. </td></tr>'
                . '<tr><td align="center" valign="top" style="font:11px Arial, Helvetica, sans-serif; color:#666666; height:20px;"><a href="https://www.google.co.in/maps/place/Prospus+Consulting+Pvt+Ltd/@28.5773307,77.3115519,17z/data=!3m1!4b1!4m5!3m4!1s0x390ce45c89d228b5:0x969556b26336f9ea!8m2!3d28.5773307!4d77.3137406">A-27G, Floor 1, Sector-16 Noida, U.P. 201301 India</a></td></tr>'
                . '</table>'
                . '</td>'
                . '</tr>'
                . '</table>'
                . '</td>'
                . '<td width="10"  style="width:20px;">&nbsp;</td>'
                . '</tr>'
                . '</table>'
                . '</td>'
                . '</tr>'
                . '<tr>'
                . '<td height="10" style="height:10px;">&nbsp;</td>'
                . '</tr>'
                . '</table>';    
echo $htmlFooter;
?>