<?php 
 
echo $this->header;

$html = '<tr><td style="font:13px Arial, Helvetica, sans-serif; color:#333333">Hello, '.$this->to_first_name .'.</td></tr>'
         .'<tr><td style="height:20px;">&nbsp;</td></tr>'
         .'<tr><td style="font:13px Arial, Helvetica, sans-serif; color:#333333">To reset your password, please follow this link <a style="color:#004E83; text-decoration:underline;" href="' . $this->loginURL .'store?token='.$this->hash_key. '#setpassword">Reset Password</a>.</td></tr>'
         .'<tr><td style="height:20px;">&nbsp;</td></tr>'
         //.'<tr><td style="font:13px Arial, Helvetica, sans-serif; color:#333333">If you were unable to click on the above link, please copy the below URL into your browser:</td></tr>'
         //.'<tr><td style="height:20px;">&nbsp;</td></tr>'
         //.'<tr><td style="font:13px Arial, Helvetica, sans-serif; color:#333333">' . $this->loginURL .'store?token='.$this->hash_key. '#setpassword</td></tr>'
         //.'<tr><td style="height:20px;">&nbsp;</td></tr>'
         .'<tr>';
    
echo $html;
echo $this->footer;
?>