<?php  
$siteLink = SOCKET_HOST_NAME;
$logourl = "https://www.prospus.com/";//Logo url
$fb = "https://www.facebook.com/pages/Prospus/272943102745384";//facebook url
$googlePlus = "https://plus.google.com/+Prospusgplus";//google plus url
$linkedin = "https://www.linkedin.com/company/4802320?trk=tyah&amp;trkInfo=tarId%3A1419942564257%2Ctas%3Aprospus%20%2Cidx%3A2-1-2";//linkedin url
  
$htmlHeader = '<style type="text/css">
                    @media only screen and (max-width: 599px) {
                        td[class="pattern"] table {
                                width: 100%;
                        }
                        td[class="pattern"] .hero_image img {
                                width: 100%;
                                height: auto !important;
                        }
                    }
                    @media only screen and (max-width: 450px) {
                        td[class="pattern"] .spacer {
                                display: none;
                        }
                        td[class="pattern"] .col {
                                width: 100%;
                                display: block;
                        }
                        td[class="pattern"] .col:first-child {
                                margin-bottom: 30px;
                        }
                        td[class="pattern"] .hero_image img {
                                width: 100%;
                        }
                        a{
                                color: #004E83!important;
                                text-decoration: underline!important;
                        }
                    }
                    .btn-blue {
                          color: #fff;
                        text-decoration: none;
                        padding: 8px 20px;
                        background: #49a9fa;
                        border-radius: 2px;
                        font-size: 14px;
                        margin-right: 10px;
                    }
             </style>';

 $htmlHeader .= '<table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#f5f5f5">
                <tr>
                    <td height="10" style="height:10px;">&nbsp;</td>
                </tr>
                <tr>
                  <td valign="top" >
                  <table border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td width="10" style="width:20px;">&nbsp;</td>
                    <td valign="top"><table  border="0" align="center" cellpadding="35" cellspacing="0" bgcolor="#FFFFFF" >
                <tr>
                            <td><table cellpadding="0" cellspacing="0">
                                <tr>
                                  <td class="pattern" width="600" align="center"><table cellpadding="0" cellspacing="0">
                                      <tr>
                                        <td class="col" width="238" valign="top"><table cellpadding="0" cellspacing="0">
                                            <tr>
                                              <td class="hero_image"><a href="' . $logourl . '" target="_blank"><img src="' . $siteLink . '/public/img/mail/prospus-logo.png" alt=""/></a></td>
                                            </tr>
                                          </table></td>
                                        <td class="spacer" width="40" style="font-size: 1px;">&nbsp;</td>
                                        <td class="col" valign="middle"><table cellpadding="0" cellspacing="0">
                                            <tr>
                                              <td class="hero_image"><table width="50%" border="0" cellspacing="0" cellpadding="0" align="right">
                                                  <tr>
                                                  <td width="57"><table border="0" cellspacing="0" cellpadding="0">
                                                        <tr>
                                                          <td ><a href="' . $fb . '" target="_blank"><img src="' . $siteLink . '/public/img/mail/facebook-icon.png" alt=""  /></a></td>
                                                        </tr>
                                                      </table></td>
                                                    <td width="30">&nbsp;</td>
                                                    <td width="57"><table border="0" cellspacing="0" cellpadding="0">
                                                                            <tr>
                                                                              <td ><a href="' . $googlePlus . '" target="_blank"><img src="' . $siteLink . '/public/img/mail/google-plus-icon.png" alt=""  /></a></td>
                                                                            </tr>
                                                                          </table></td>
                                                     <td width="30">&nbsp;</td>
                                                    <td width="57"><table border="0" cellspacing="0" cellpadding="0">
                                                        <tr>
                                                          <td ><a href="' . $linkedin . '" target="_blank"><img src="' . $siteLink . '/public/img/mail/linkedin-icon.png" alt=""  /></a></td>
                                                        </tr>
                                                      </table></td>
                                                    <td width="30">&nbsp;</td>
                                                   </tr>
                                                </table></td>
                                            </tr>
                                          </table></td>
                                      </tr>
                                    </table></td>
                                </tr>
                            <tr>
                              <td style="height:34px; border-bottom:2px #dadada solid">&nbsp;</td>
                            </tr>
                            <tr>
                              <td style="height:34px;"></td>
                            </tr>
                            <tr>
                            <td width="10" valign="top" style="height:34px; border-bottom:2px #dadada solid; line-height:34px;"><table width="100%" border="0" cellpadding="0" cellspacing="0">
                              <tr>
                                <td width="10">&nbsp;</td>
                                <td valign="top"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                                  ';
 echo $htmlHeader;
?>