<?php if($this->post['type'] == 'mainPage') { ?>
<table class="" border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
<tbody>
  <tr class="row-0">
    <td class="ExcelTableFormationRow"><div class="left-col"></div></td>
    <td class="ExcelTableFormationCol col-1 collapse"><span class="top-col">1</span></td>
    <td class="ExcelTableFormationCol col-2 collapse"><span class="top-col">2</span></td>
    <td class="ExcelTableFormationCol col-3"><span class="top-col">3</span></td>
    <td class="ExcelTableFormationCol col-4 collapse"><span class="top-col">4</span></td>
    <td class="ExcelTableFormationCol col-5 collapse"><span class="top-col">5</span></td>   
    <td class="ExcelTableFormationCol col-6"></td>
  </tr>
  
  <tr class="row-1">
    <td class="ExcelTableFormationRow"><div class="left-col">1</div></td>
    <td class="col-1 collapse"><div data-id="1" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon time-icon"></span><span class="col-head-title">Timeline</span><i class="fa fa-caret-left arrow rotate"></i> </div></td>
    <td class="col-2 collapse"><div data-id="2" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> </div>
    </td>
    <td class="col-3"><div data-id="1" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon time-icon"></span><span class="col-head-title">Process</span><i class="fa fa-caret-left arrow rotate"></i> </div></td>
    <td class="col-4 collapse"><div data-id="2" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> </div>
    </td>  
     <td class="col-5 collapse blue-bg"><div data-id="1" class="col-head">
        <div class="node-circle node-white-circle node-white-circle">N</div><span class="icon time-icon"></span><span class="col-head-title">Phase</span><i class="fa fa-caret-left arrow rotate"></i> </div></td> 
    <td class="col-6 "></td>
  </tr>
  
  <tr class="row-2">
    <td class="ExcelTableFormationRow"><div class="left-col">2</div></td>
    <td class="col-1 collapse"><div class="">
        <div class="time-col"> <span class="doted-border"></span>
          <div class="node-circle node-white-sm-circle">N</div>
          <span class="col-text"> 
          <span class="col-node-text custom-node"></span>
        </span> </div>
      </div>
    </td>
    <td class="col-2 collapse event">
      <div class="creation-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <span class="col-text"> <span class="creation"></span> 
        <span class="col-node-text custom-node">Creation</span>
       </span>
      </div>
    </td>
    <td class="col-3">
      <div class="segment-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <div class="col-text segment-text operation-text">
         <span class="col-node-text"><input type="text" class="custom-node undefined" placeholder="Undefined" name="parent_2_3"><span class="icons"><i class="saveIcon" data-toggle="tooltip" data-placement="bottom" data-original-title="Save"></i><i class="closeIcon" data-toggle="tooltip" data-placement="bottom" data-original-title="Cancel"></i></span></span>
        </div>
      </div>
    </td>
    <td class="col-4 collapse event">
      <div class="creation-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <span class="col-text"> <span class="creation"></span> 
        <span class="col-node-text custom-node">Creation</span>
       </span>
      </div>
    </td>
    <td class=" col-5 creation-bg merge-td collapse blue-bg "><div class="add-three-pane add-panel"><span class="fa fa-plus"></span></div></td>   
    <td class="col-6"></td>
  </tr>
  
 <tr class="row-2">
    <td class="ExcelTableFormationRow"><div class="left-col">2</div></td>
    <td class="col-1 collapse">
      <div class="lastRow">
        <div class="time-col">
          <div class="node-circle node-white-sm-circle">N</div>
          <div class="borderDashed last-borderDashed"></div>
          <span class="col-text"> </span> </div>
      </div>
    </td>
    <td class="col-2 collapse event">
      <div class="creation-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <div class="col-text"> <span class="destructure"></span> 
        <span class="col-node-text custom-node">Destruction</span> 
        </div>
      </div>
    </td>
    <td class="col-3">
      <div class="blank-div segment-node"></div>
    </td>
    <td class="col-4 collapse event">
      <div class="creation-node">
        <div class="node-circle node-white-circle node-white-circle">N</div>
        <div class="col-text"> <span class="destructure"></span> 
        <span class="col-node-text custom-node">Destruction</span> 
        </div>
      </div>
    </td>
    <td class=" col-5 creation-bg merge-td collapse blue-bg"><div class="blank-div segment-node"></div></td>   
    <td class="col-6"></td>
  </tr>
</tbody>
</table>
<?php }?>