<div class="fixed-top-header">
    <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
        <tbody>
            <?php
            for ($row = 0; $row < 2; $row++) {
                ?>
                <tr class="<?php echo $this->tableDataArray[$row][0]['trClass']; ?>" >
                    <?php for ($col = 0; $col < count($this->tableDataArray[$row]); $col++) { ?>
                        <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass']; ?>"><?php echo $this->tableDataArray[$row][$col]['data']; ?></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<table border="" class="fixed-left-column" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
    <tbody>
        <?php
        $operationSegmentCount = $this->checkrole;

            if($operationSegmentCount >= 2){
                    $roleCount = intval($this->checkrole)*4+1;   
                }
            else
            {
                $roleCount = intval($this->checkrole)*4;       
            }        

        
        $flag = 'Y';
        $noflag = 'Y';
        for ($row = 0; $row < count($this->tableDataArray); $row++) {?>
            <tr class="<?php echo $this->tableDataArray[$row][0]['trClass']; ?>" >
                <?php for ($col = 0; $col < count($this->tableDataArray[$row]); $col++) { ?>
                    <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass']; ?>"><?php echo $this->tableDataArray[$row][$col]['data']; ?></td>
            <?php } ?>
            </tr>

            <?php
            if ($this->checkrole == 0 && $this->noOfProcess<1) {
                if ($this->type == 'Below') {
                    $rowIndex = intval($this->currentRowIndex);
                } else {
                    if (intval($this->currentRowIndex) - 1 == 1) {
                        $rowIndex = intval($this->currentRowIndex);
                    } else {
                        $rowIndex = intval($this->currentRowIndex) - 2;
                    }
                }
                if (intval($row) == intval($rowIndex)) {
                    ?>
                    <tr class="">
                        <?php for ($col = 0; $col < count($this->tableDataArray[$row]); $col++) { ?>
                            <?php if (intval($this->currentColumnIndex) == intval($col)) { ?>
                                <td class="col-<?php echo intval($col); ?> ExcelTablerow"><?php echo $this->phaseArray[1]['phase']; ?></td>
                            <?php } else if (intval($this->currentColumnIndex) + 1 == intval($col)) { ?>
                                <td class="col-<?php echo intval($col); ?> ExcelTablerow"><?php echo $this->phaseArray[1]['event']; ?></td>
                            <?php } else { ?>
                                <td class="col-<?php echo intval($col); ?><?php if (intval($col) == 0) { ?> ExcelTableFormationRow<?php } else { ?> ExcelTablerow<?php } ?>"><?php if (intval($this->currentColumnIndex) + 1 > intval($col)) { ?><div class="blank-div segment-node"></div><?php } ?>       </td>
                            <?php } ?>
            <?php } ?>
                    </tr>
                    <tr class="" >
                        <?php for ($col = 0; $col < count($this->tableDataArray[$row]); $col++) { ?>
                            <?php if (intval($this->currentColumnIndex) == intval($col)) { ?>
                                <td class="col-<?php echo intval($col); ?> ExcelTablerow"><?php echo $this->phaseArray[0]['phase']; ?></td>
                            <?php } else if (intval($this->currentColumnIndex) + 1 == intval($col)) { ?>
                                <td class="col-<?php echo intval($col); ?> ExcelTablerow"><?php echo $this->phaseArray[0]['event']; ?></td>
                            <?php } else { ?>
                                <td class="col-<?php echo intval($col); ?><?php if (intval($col) == 0) { ?> ExcelTableFormationRow<?php } else { ?> ExcelTablerow<?php } ?>"><?php if (intval($this->currentColumnIndex) + 1 > intval($col)) { ?><div class="blank-div segment-node"></div><?php } ?></td>
                            <?php } ?>
                    <?php } ?>
                    </tr>
                <?php } ?>
            
            <?php } else { ?>

                <?php
                if ($this->type == 'Below') {
                    $rowIndex = intval($this->currentRowIndex) + 1;
                } else {
                    if (intval($this->currentRowIndex) - 1 == 1) {
                        $rowIndex = intval($this->currentRowIndex);
                    } else {
                        $rowIndex = intval($this->currentRowIndex) - 2;
                    }
                }

                if (intval($row) == intval($rowIndex)) {
                    ?>
                    <tr class="" >
                        <?php for ($col = 0; $col < intval(count($this->tableDataArray[$row])) - (intval($roleCount)); $col++) { ?>

                            <?php if (intval($this->currentColumnIndex) == intval($col)) { ?>

                                <td class="col-<?php echo intval($col); ?> ExcelTablerow"><?php echo $this->phaseArray[2]['phase']; ?></td>
                            <?php } else if (intval($this->currentColumnIndex) + 1 == intval($col)) { ?>
                                <td class="col-<?php echo intval($col); ?> ExcelTablerow"><?php echo $this->phaseArray[2]['event']; ?></td>
                            
                            <?php } else if (intval($this->currentColumnIndex) + 2 == intval($col)) { ?>
                                <?php
                                $countSerielNo = intval($this->currentColumnIndex) + 2;
                                $l = 2; $k = 0;
                                if ($this->checkrole > 0) {
                                    for ($j = 0; $j < (intval($this->checkrole)); $j++) {
                                         
                                        if($j > 0){

                                            $k = intval($this->currentColumnIndex) + intval(($j+1) * $l) + $j;
                                        }
                                        else{

                                            $k = intval($this->currentColumnIndex) +  $l;
                                        }

                                        ?>
                                      <td class="ExcelTablerow"><?php echo $this->roleArray[2]['group']; ?></td>
                                      <td class="ExcelTablerow collapse event"><?php echo $this->roleArray[2]['actor-event']; ?></td>
                                      <td class="ExcelTablerow"><?php echo $this->roleArray[2]['phase']; ?></td>
                                      <td class="ExcelTablerow collapse event"><?php echo $this->roleArray[2]['event']; ?></td>
                                      <td class="ExcelTablerow border-light-bottom Role-segment process-series "><?php echo $this->roleArray[2]['process']; ?>
                                      </td>
                                <?php }
                            } ?>
                                
                            <?php } else { ?>
                                <td class="col-<?php echo intval($col); ?>
                                    <?php if (intval($col) == 0) { ?> ExcelTableFormationRow<?php } else { ?> ExcelTablerow<?php } ?>">
                                    <?php if($col < intval($this->currentColumnIndex)+1){ ?>
                                        <div class="blank-div segment-node"></div>
                                    <?php } ?>
                                </td>

                            <?php } ?>
                        <?php } ?>
                        </tr>

                        <?php for ($number = 0; $number < 2; $number++) { ?>
                        <tr class="">
                            <?php for ($col = 0; $col < intval(count($this->tableDataArray[$row])) - (intval($roleCount)); $col++) { ?>
                                <?php if (intval($this->currentColumnIndex) == intval($col)) { ?>
                                    <td class="col-<?php echo intval($col); ?> ExcelTablerow <?php if ($number == 0) { ?>border-light-top<?php } ?>"><?php echo $this->phaseArray[$number]['phase']; ?>
                                    </td>
                                <?php } else if (intval($this->currentColumnIndex) + 1 == intval($col)) { ?>
                                        <td class="col-<?php echo intval($col); ?> ExcelTablerow">
                                            <?php echo $this->phaseArray[$number]['event']; ?>
                                        </td>
                                <?php } else if (intval($this->currentColumnIndex) + 2 == intval($col)) { ?>
                                    <?php
                                        $countSerielNo = intval($this->currentColumnIndex) + 2; 
                                        $l = 2;
                                        if ($this->checkrole > 0) {
                                            for ($j = 0; $j < (intval($this->checkrole)); $j++) {
                                                 
                                                if($j > 0){

                                                    $k = intval($this->currentColumnIndex) + intval(($j+1) * $l) + $j;
                                                }
                                                else{

                                                    $k = intval($this->currentColumnIndex) +  $l;
                                                }

                                        ?>
                                          <td class="ExcelTablerow"><?php echo $this->roleArray[1]['group']; ?></td>
                                          <td class="ExcelTablerow collapse event"><?php echo $this->roleArray[$number]['actor-event']; ?></td>
                                          <td class="ExcelTablerow <?php if($number==0){ ?>border-light-top<?php }?>"><?php echo $this->roleArray[$number]['phase']; ?></td>
                                          <td class="ExcelTablerow collapse event"><?php echo $this->roleArray[$number]['event']; ?></td>
                                          <td class="ExcelTablerow border-light-bottom Role-segment process-series "><?php echo $this->roleArray[$number]['process']; ?>
                                          </td>
                                    <?php }
                                } ?>
                                    
                            <?php } else { ?>
                                            <td class="col-<?php echo intval($col); ?><?php if (intval($col) == 0) { ?> ExcelTableFormationRow<?php } else { ?> ExcelTablerow<?php } ?>">
                                                <?php if($col < intval($this->currentColumnIndex)+1){ ?>
                                                    <div class="blank-div segment-node"></div>
                                                <?php } ?>
                                            </td>
                            <?php } ?>
                    <?php } ?>
                        </tr>
                <?php } ?>


        <?php } ?>



    <?php } ?>

<?php } ?>
    </tbody>
</table>