<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" dir="ltr">
<head>
    <title>Prospus Universe</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <script type="text/javascript">
        var domainUrl   =   "<?php echo BASE_URL; ?>";
    </script>

    <link rel="shortcut icon" href="<?php echo BASE_URL; ?>public/vw_img/favicon.ico" type="images/ico" sizes="16x16">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300italic' rel='stylesheet' type='text/css'>
    <link href="<?php echo BASE_URL; ?>public/vw_css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo BASE_URL; ?>puidata/css/header-style.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo BASE_URL; ?>public/vw_css/vw-style.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo BASE_URL; ?>public/vw_css/vw-responsive.css" rel="stylesheet" type="text/css"/>

    <!-- Script -->
    <script src="<?php echo BASE_URL; ?>public/vw_js/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="<?php echo BASE_URL; ?>public/vw_js/bootstrap.min.js" type="text/javascript"></script>
    <script src="<?php echo BASE_URL; ?>public/vw_js/script.js" type="text/javascript"></script>
</head>

<body>
    <?php echo $this->content; ?>
</body>
</html>


        