<div class="fixed-top-header">
   <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
      <tbody>
         <?php 
			for($row=0;$row<2;$row++) {
				?>
			   <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
				  <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
							<td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php  echo $this->tableDataArray[$row][$col]['data']; ?></td>
				  <?php } ?>
			   </tr>
			<?php } ?>
      </tbody>
   </table>
</div>
<table border="" class="fixed-left-column" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
<tbody>
<?php   
        $incrmentCounter= '';
        $logicLastLength = intval($this->currentRowIndex)+intval($this->currentLength)-2;

        $lastRow =  ($logicLastLength)+1;

        if($this->suboperationCount < 2){
            $startcol = intval($this->currentColumnIndex)+2;
            $endcol   = intval($this->currentColumnIndex)+3;
        } else {
            $startcol = intval($this->currentColumnIndex)+ 2;
            $endcol = intval($this->currentColumnIndex)  + intval($this->suboperationCount*2);
        }


	for($row=0;$row<count($this->tableDataArray);$row++) { ?>
  <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
      <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
          <?php if(!empty($this->suboperationCount) || $this->suboperationCount!=0){?>
          <?php if(($row == $lastRow) && ($col >= $startcol && $col <= intval($endcol))) { ?>
              <td class="role operation-series"><div class="blank-div segment-node"></div> </td>
            <?php } else {?>
            <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?> </td>
            <?php }?>
            <?php } else {?> 
      <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?> </td>
            <?php } ?>      
<?php } ?>
  </tr>
<?php    
  
  
  if($this->NonSquential=='NonSquential'){

    $incrmentCounter  = 3;
    
    }
    else {
      $incrmentCounter = 2;    
    }
 ?>

  <?php if(intval($row) ==  intval($logicLastLength)) {?>
        <tr class="" >
      <?php for($col=0;$col<intval(count($this->tableDataArray[$row]))-(5+intval($this->noOfRole)+intval($this->domaincount)+intval($this->suboperationCount*2)+intval($this->eventCount));$col++) {   ?>
      		<?php if(intval($this->currentColumnIndex) == intval($col)) { ?>
           
           <td class="ExcelTablerow operation-series operation1 border-light-bottom "><?php echo $this->logicOperationPhaseArray[$incrmentCounter]['operation1']; ?></td>
           <td class="ExcelTablerow operation-series operation-event"><?php echo $this->logicOperationPhaseArray[$incrmentCounter]['event_operation']; ?></td>

           <?php  
           if($this->suboperationCount > 0) {
                for($o = 0;$o < (intval($this->suboperationCount));$o++){ ?>
                   <td class="ExcelTablerow border-light-bottom creation-bg role operation-series sub-operation "><?php echo $this->subOperationArray[$incrmentCounter]['sub_operation1']; ?></td>
            <td class="ExcelTablerow border-light-bottom  operation-series  sub-operation role"><?php echo $this->subOperationArray[$incrmentCounter]['sub_event_operation']; ?></td>
            <?php } 

            } ?>

            <td class="ExcelTablerow operation-series operation2"><?php echo $this->logicOperationPhaseArray[$incrmentCounter]['operation2']; ?></td> 
            <td class="ExcelTablerow operation-series operation-event"><?php echo $this->logicOperationPhaseArray[$incrmentCounter]['event']; ?></td> 

            <?php if($this->eventCount > 0){
                for($e = 0;$e < $this->eventCount;$e++){ ?>
          <td class="ExcelTablerow operation-series creation-bg"><?php echo $this->eventStatusArr[$incrmentCounter]['eventStatus']; ?></td>
            <?php } }  ?>

            <td class="ExcelTablerow operation-series role"><?php echo $this->logicOperationPhaseArray[$incrmentCounter]['role']; ?></td> 
            <?php $countSerielNo = 5; ?>
                  <?php 
                  if($this->noOfRole > 0){
                    for($k = 0;$k < $this->noOfRole;$k++){ 
                    $countSerielNo = intval($k)+5; ?>
            <td class="ExcelTablerow operation-series role"><?php echo $this->roleArray[$incrmentCounter]['role_series']; ?></td>

            <?php } }  ?>

            <?php $logiccountSerielNo = '';
                  if($this->domaincount > 0){
                    for($m = 0;$m < $this->domaincount;$m++){ 
                    $logiccountSerielNo = intval($m)+intval($countSerielNo);

                    ?>
                     <?php if($m==0){?>
            <td class="ExcelTablerow operation-series role domain"><?php echo $this->domainArray[$incrmentCounter]['domain']; ?></td>
            <?php } else {?>
            <td class="ExcelTablerow operation-series role domain"><?php echo $this->commondomainArray[$incrmentCounter]['domain']; ?></td>
            <?php } ?>

            <?php $countSerielNo = $logiccountSerielNo;} }  ?>

         <td class="ExcelTablerow operation-series system"><?php echo $this->logicOperationPhaseArray[$incrmentCounter]['system']; ?></td>
          <?php } else { ?>
          
           <td class="col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow<?php } ?> "><?php if(intval($this->currentColumnIndex) > intval($col)) { ?><div class="blank-div segment-node"></div><?php } ?></td>
          
          <?php } ?>
        <?php } ?>
        </tr>
  
      <?php for($i=0;$i<(count($this->logicOperationPhaseArray)-1);$i++) {

        if($i == 0 && $incrmentCounter=='3'){
          $AddClass = 'creation-bg border-light-top border-light-bottom blankRowTd';
          $bolderLeft = 'blankLeftBorder';
          $bolderRight = 'blankRightBorder';
          $bgclass = '';

        }
        else if($i == 1 && $incrmentCounter=='3'){
          $bgclass = 'creation-bg';
          $bolderLeft = '';
          $bolderRight = '';
          $AddClass = ''; 
        }
        else if($i == 0 && $incrmentCounter=='2'){
          $bgclass = 'creation-bg';
          $bolderLeft = '';
          $bolderRight = '';
          $AddClass = ''; 
        }
      else {
          $AddClass = '';  
          $bolderLeft = '';
          $bolderRight = '';
          $bgclass = '';
          
         }
        
       ?>
      	<tr class="" >
      <?php for($col=0;$col<intval(count($this->tableDataArray[$row]))-(5+intval($this->noOfRole)+intval($this->domaincount)+intval($this->suboperationCount*2)+intval($this->eventCount));$col++) { 

          if($col % 2 == 0 ){
            $bolderClass = 'border-right';
          }
          else {
           $bolderClass = ''; 
          }

       ?>
      		<?php if(intval($this->currentColumnIndex) == intval($col)) { ?>
           <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex); ?> operation-series operation1 <?php echo $AddClass?> <?php echo $bolderLeft?>" ><?php echo $this->logicOperationPhaseArray[$i]['operation1']; ?></td>
             <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+1; ?> operation-series operation-event <?php echo $AddClass?>"><?php echo $this->logicOperationPhaseArray[$i]['event_operation']; ?></td> 
             
             <?php if($this->suboperationCount > 0) {
              for($o = 0;$o < (intval($this->suboperationCount));$o++){   ?>
              <td class="ExcelTablerow operation-series <?php echo $AddClass?> role sub-operation"><?php echo $this->subOperationArray[$i]['sub_operation1']; ?></td>
              <td class="ExcelTablerow operation-series <?php echo $AddClass?> sub-operation role"><?php echo $this->subOperationArray[$i]['sub_event_operation']; ?></td>
            <?php } }?>


            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?> operation-series operation2 <?php echo $AddClass?>">
             <?php echo $this->logicOperationPhaseArray[$i]['operation2']; ?></td> 
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> operation-series operation-event <?php echo $AddClass?>"><?php echo $this->logicOperationPhaseArray[$i]['event']; ?></td> 

            <?php if($this->eventCount > 0){
                for($e = 0;$e < $this->eventCount;$e++){ ?>
          <td class="ExcelTablerow operation-series creation-bg"><?php echo $this->eventStatusArr[$i]['eventStatus']; ?></td>
            <?php } }  ?>

            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+4; ?> operation-series role <?php echo $AddClass?>">	<?php echo $this->logicOperationPhaseArray[$i]['role']; ?></td> 
            
            <?php $countSerielNo = 5;
                    if($this->noOfRole > 0){
                      for($k = 0;$k < $this->noOfRole;$k++){ 
                    $countSerielNo = intval($k)+5; ?>
                    <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+intval($countSerielNo); ?> operation-series role <?php echo $AddClass?>"><?php echo $this->roleArray[$i]['role_series']; ?></td>
            <?php } } ?>
            
            
              <?php $logiccountSerielNo = '';
                  
                    if($this->domaincount > 0){
                    
                      for($m = 0;$m < $this->domaincount;$m++){ 
                      
                      $logiccountSerielNo = intval($m)+intval($countSerielNo);
                    
                    ?>
            <?php if($m==0){?>

            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+intval($countSerielNo); ?> operation-series role domain 
            <?php echo $bgclass;?><?php echo $AddClass?>"><?php echo $this->domainArray[$i]['domain']; ?></td>
            <?php } else {?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+intval($countSerielNo); ?> operation-series role domain 
            <?php echo $bgclass;?><?php echo $AddClass?>"><?php echo $this->commondomainArray[$i]['domain']; ?></td>
            <?php } ?>

            <?php 
                      $countSerielNo = $logiccountSerielNo;
                    } 
                }  ?>


            <td class="ExcelTablerow  col-<?php echo intval($this->currentColumnIndex)+intval($countSerielNo); ?> operation-series system <?php echo $AddClass?> <?php echo $bolderRight;?>"><?php echo $this->logicOperationPhaseArray[0]['system']; ?></td>
          <?php } else { ?>
          <td class="  <?php echo $bolderClass?> col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow <?php } ?> ">
          <div class="blank-div segment-node <?php if(intval($col) == 1 ){ ?> borderDashed <?php }?>"></div></td>
          <?php } ?>
        <?php } ?>
        </tr>
     <?php } ?> 
  <?php } ?>

<?php } ?>
</tbody>
</table>
