<div class="fixed-top-header">
    <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
        <tbody>
            <?php for($row=0;$row<2;$row++) { ?>
            <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
                <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
                <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?></td>
                <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
                <?php if(intval($row) == 0) { ?>
                <td class="ExcelTableFormationCol col-<?php echo intval($this->currentColumnIndex)+2; ?>">
                <span class="top-col"><?php echo intval($this->currentColumnIndex)+2; ?></span>
                <i class="fa fa-plus add add-operation"></i>
                <div class="add-col-wrap add-colums">
                    <ul class="dropdown-menu show-<?php echo intval($this->currentColumnIndex)+2; ?>" >
                        <li role="presentation" class="no-bg disabled">
                            <a role="menuitem" tabindex="-1" class="">
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add left
                            </a>
                            <ul class="sub-item">
                                <li role="presentation" class="no-bg">
                                    <a role="menuitem" tabindex="-1" href="#" class=" add-left-col">
                                        <div class="node-circle node-white-circle">N</div>
                                        Phase 
                                    </a>
                                </li>
                                <li role="presentation" class="no-bg">
                                    <a role="menuitem" tabindex="-1" href="#" class=" add-operation-series">
                                        <div class="node-circle node-white-circle">N</div>
                                        Operation
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li role="presentation" class="no-bg disabled">
                            <a role="menuitem" tabindex="-1" class="" >
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add right
                            </a>
                            <ul class="sub-item">
                                <li role="presentation" class="addSegmentRole">
                                    <a role="menuitem" tabindex="-1" href="#" class="">
                                        <div class="node-circle node-white-circle-expanded">N</div>
                                        Role 
                                    </a>                                    
                                </li>                                            
                            </ul>
                        </li>
                         <li role="presentation" class="delete-series no-bg">
                                    <a role="menuitem" tabindex="-1" href="#" class="" >
                                        <div class="node-circle node-white-circle">N</div>
                                        Delete Series 
                                    </a>
                        </li>
                    </ul>
                </div>
            </td>
            <td class="ExcelTableFormationCol  col-<?php echo intval($this->currentColumnIndex)+3; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+3; ?></span></td>
            <td class="ExcelTableFormationCol  col-<?php echo intval($this->currentColumnIndex)+4; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+4; ?></span></td>
            <td class="ExcelTableFormationCol   col-<?php echo intval($this->currentColumnIndex)+5; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+5; ?></span></td>
            <td class="ExcelTableFormationCol   col-<?php echo intval($this->currentColumnIndex)+6; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+6; ?></span>
            <i class="fa fa-plus add add-operation check-role"></i>
             <div class="add-col-wrap add-check-role ">
                    <ul class="dropdown-menu show-<?php echo intval($this->currentColumnIndex)+6; ?>" >
                       <li role="presentation" class="">
                            <a role="menuitem" tabindex="-1" class="">
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add right
                            </a>
                           <ul class="sub-item">
                                <li role="presentation" class="">
                                    <a role="menuitem" tabindex="-1" href="#" class="">
                                        <div class="node-circle node-white-circle-expanded">N</div>
                                        Role 
                                    </a>
                                    <ul class="sub-item">
                                        <li><a href="#" class="addDomain"><div class="node-circle node-white-circle">N</div>Logic</a></li>
                                        <li><a href="#" class="addSegmentRole"><div class="node-circle node-white-circle">N</div>Human</a></li>
                                    </ul>
                                </li>                                            
                            </ul>
                        </li>
                        <li role="presentation" class="deleteSegmentRole roleSeries">
                                    <a role="menuitem" tabindex="-1" href="#" class="">
                                        <div class="node-circle node-white-circle">N</div>
                                        Delete Series 
                                    </a>
                        </li>
                    </ul>
                </div>
                
            </td>
            <td class="ExcelTableFormationCol   col-<?php echo intval($this->currentColumnIndex)+7; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+7; ?></span></td>
                <?php } else if(intval($row) == 1){ ?>
                <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+2; ?>">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+2; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon operation-icon"></span><span class="col-head-title">Operation</span><i class="fa fa-caret-left arrow"></i>
                    </div>
                </td>
                
                <td class="ExcelTablerow border-top  col-<?php echo intval($this->currentColumnIndex)+3; ?>">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+3; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i>
                    </div>
                </td>
                
                <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+4; ?>">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+4; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon operation-icon"></span><span class="col-head-title">Operation</span><i class="fa fa-caret-left arrow"></i>
                    </div>
                </td>
                <td class="ExcelTablerow border-top  col-<?php echo intval($this->currentColumnIndex)+5; ?>">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+5; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i>
                    </div>
                </td>
                <td class="ExcelTablerow border-top   col-<?php echo intval($this->currentColumnIndex)+6; ?>">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+6; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon role-icon"></span><span class="col-head-title">Role</span><i class="fa fa-caret-left arrow"></i>
                    </div>
                </td>
                <td class="ExcelTablerow border-top   col-<?php echo intval($this->currentColumnIndex)+7; ?>">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+7; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon sys-icon"></span><span class="col-head-title">Universe</span><i class="fa fa-caret-left arrow"></i>
                    </div>
                </td>
                <?php } ?>
                <?php } ?>
                <?php } ?>
               
            </tr>
            <?php }?>
        </tbody>
    </table>
</div>
<table border="" class="fixed-left-column" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
    <tbody>
        <?php $addRow = 0; $newFlag = ''; $flag = ''; 
            for($row=0;$row<count($this->tableDataArray);$row++) {
            ?>
        <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
            <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
            <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?></td>
            <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
            <?php if(intval($row) == 0) { ?>
            <td class="ExcelTableFormationCol col-<?php echo intval($this->currentColumnIndex)+2; ?>">
                <span class="top-col"><?php echo intval($this->currentColumnIndex)+2; ?></span>
                <i class="fa fa-plus add add-operation"></i>
                <div class="add-col-wrap add-colums">
                    <ul class="dropdown-menu show-<?php echo intval($this->currentColumnIndex)+2; ?>" >
                        <li role="presentation" class="no-bg disabled">
                            <a role="menuitem" tabindex="-1" class="">
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add left
                            </a>
                            <ul class="sub-item">
                                <li role="presentation" class="no-bg">
                                    <a role="menuitem" tabindex="-1" href="#" class=" add-left-col">
                                        <div class="node-circle node-white-circle">N</div>
                                        Phase 
                                    </a>
                                </li>
                                <li role="presentation" class="no-bg">
                                    <a role="menuitem" tabindex="-1" href="#" class=" add-operation-series">
                                        <div class="node-circle node-white-circle">N</div>
                                        Operation
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li role="presentation" class="no-bg disabled">
                            <a role="menuitem" tabindex="-1" class="" >
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add right
                            </a>
                            <ul class="sub-item">
                                <li role="presentation" class="no-bg">
                                    <a role="menuitem" tabindex="-1" href="#" class="add-Role">
                                        <div class="node-circle node-white-circle">N</div>
                                        Role 
                                    </a>
                                </li>
                            </ul>
                        </li>
                         <li role="presentation" class="delete-series no-bg disabled">
                                    <a role="menuitem" tabindex="-1" href="#" class="disabled" >
                                        <div class="node-circle node-white-circle">N</div>
                                        Delete Series 
                                    </a>
                        </li>
                    </ul>
                </div>
            </td>
            <td class="ExcelTableFormationCol  col-<?php echo intval($this->currentColumnIndex)+3; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+3; ?></span></td>
            <td class="ExcelTableFormationCol  col-<?php echo intval($this->currentColumnIndex)+4; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+4; ?></span></td>
            <td class="ExcelTableFormationCol   col-<?php echo intval($this->currentColumnIndex)+5; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+5; ?></span></td>
            <td class="ExcelTableFormationCol   col-<?php echo intval($this->currentColumnIndex)+6; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+6; ?></span>
            <i class="fa fa-plus add add-operation check-role"></i>
                <div class="add-col-wrap add-check-role">
                    <ul class="dropdown-menu show-<?php echo intval($this->currentColumnIndex)+6; ?>" >
                      <!--  <li role="presentation" class="">
                            <a role="menuitem" tabindex="-1" class="">
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add right
                            </a>
                            <ul class="sub-item">
                                <li role="presentation" class="addSegmentRole">
                                    <a role="menuitem" tabindex="-1" href="#" class="">
                                        <div class="node-circle node-white-circle">N</div>
                                        Role 
                                    </a>
                                </li>
                            </ul>
                        </li> -->
                        <li role="presentation" class="">
                            <a role="menuitem" tabindex="-1" class="">
                                <div class="node-circle node-white-circle-expanded">N</div>
                                Add right
                            </a>
                        <ul class="sub-item">
                                <li role="presentation" class="">
                                    <a role="menuitem" tabindex="-1" href="#" class="">
                                        <div class="node-circle node-white-circle-expanded">N</div>
                                        Role 
                                    </a>
                                    <ul class="sub-item">
                                        <li><a href="#" class="addDomain"><div class="node-circle node-white-circle">N</div>Logic</a></li>
                                        <li><a href="#" class="addSegmentRole"><div class="node-circle node-white-circle">N</div>Human</a></li>
                                    </ul>
                                </li>                                            
                            </ul>
                        </li>
                        <li role="presentation" class="deleteSegmentRole roleSeries">
                                    <a role="menuitem" tabindex="-1" href="#" class="">
                                        <div class="node-circle node-white-circle">N</div>
                                        Delete Series 
                                    </a>
                        </li>
                    </ul>
                </div>
            </td>
            <td class="ExcelTableFormationCol   col-<?php echo intval($this->currentColumnIndex)+7; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+7; ?></span></td>
            <?php } else if(intval($row) == 1){ ?>
            <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+2; ?>">
                <div data-id="<?php echo intval($this->currentColumnIndex)+2; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon operation-icon"></span><span class="col-head-title">Operation</span><i class="fa fa-caret-left arrow"></i>
                </div>
            </td>
            
            <td class="ExcelTablerow border-top  col-<?php echo intval($this->currentColumnIndex)+3; ?>">
                <div data-id="<?php echo intval($this->currentColumnIndex)+3; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i>
                </div>
            </td>
            
            <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+4; ?>">
                <div data-id="<?php echo intval($this->currentColumnIndex)+4; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon operation-icon"></span><span class="col-head-title">Operation</span><i class="fa fa-caret-left arrow"></i>
                </div>
            </td>
            <td class="ExcelTablerow border-top  col-<?php echo intval($this->currentColumnIndex)+5; ?>">
                <div data-id="<?php echo intval($this->currentColumnIndex)+5; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i>
                </div>
            </td>
            <td class="ExcelTablerow border-top   col-<?php echo intval($this->currentColumnIndex)+6; ?>">
                <div data-id="<?php echo intval($this->currentColumnIndex)+6; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon role-icon"></span><span class="col-head-title">Role</span><i class="fa fa-caret-left arrow"></i>
                </div>
            </td>
            <td class="ExcelTablerow border-top   col-<?php echo intval($this->currentColumnIndex)+7; ?>">
                <div data-id="<?php echo intval($this->currentColumnIndex)+7; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon sys-icon"></span><span class="col-head-title">Universe</span><i class="fa fa-caret-left arrow"></i>
                </div>
            </td>
            <?php } else { ?>
            <?php 
                ?>
            <?php if($newFlag == 'Y') { ?>
            <?php ?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?> operation-series operation1">
                <?php echo $this->phaseArray[5]['operation1']; ?>
            </td>
            
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> operation-series 
                operation-event"><?php echo $this->phaseArray[5]['event_operation']; ?></td>
                
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+4; ?> operation-series operation2">
                <?php echo $this->phaseArray[5]['operation2']; ?>
            </td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+5; ?> operation-series operation-event"><?php echo $this->phaseArray[5]['event']; ?></td>
            
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+6; ?> operation-series role"> <?php echo $this->phaseArray[5]['role']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+7; ?> operation-series system"><?php echo $this->phaseArray[5]['system']; ?></td>
            
            <?php $newFlag = 'N'; }
			else if($addRow < $this->currentColumnSegments) {
                ?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?> operation-series operation1"><?php echo $this->phaseArray[0]['operation1']; ?></td>
            
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> operation-series 
                operation-event"><?php echo $this->phaseArray[0]['event_operation']; ?></td>
            
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+4; ?> operation-series operation2"><?php echo $this->phaseArray[0]['operation2']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+5; ?> operation-series 
                operation-event"><?php echo $this->phaseArray[0]['event']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+6; ?> operation-series role"> <?php echo $this->phaseArray[0]['role']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+7; ?> operation-series system"><?php echo $this->phaseArray[0]['system']; ?></td>
            <?php  $flag = 'Y';  ?>
            <?php }  else {  ?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>"></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?>  "></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+4; ?> "></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+5; ?> "></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+6; ?> "></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+7; ?> "></td>
            <?php } ?>
            <?php } ?>
            <?php } ?>
            <?php } ?>
        </tr>
        <?php if($flag == 'Y') { ?>
        <?php if(intval($addRow) < $this->currentColumnSegments) { ?>
        <?php for($i=1;$i<count($this->phaseArray)-1;$i++) { ?>
        <tr class="" >
            <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
            <td class="col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow<?php } ?>">
                <?php if(intval($this->currentColumnIndex)+2 > intval($col)) { ?>
                <div class="blank-div segment-node"></div>
                <?php } ?>
            </td>
            <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?> operation-series operation1"><?php echo $this->phaseArray[$i]['operation1']; ?></td>
             <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> operation-series operation-event"><?php echo $this->phaseArray[$i]['event_operation']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+4; ?> operation-series operation2"><?php echo $this->phaseArray[$i]['operation2']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+5; ?> operation-series operation-event"><?php echo $this->phaseArray[$i]['event']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+6; ?> operation-series role"> <?php echo $this->phaseArray[$i]['role']; ?></td>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+7; ?> operation-series system"><?php echo $this->phaseArray[$i]['system']; ?></td>
           
            <?php } ?>
            <?php } ?>
        </tr>
        <?php } ?>
        <?php $addRow++;$flag = 'N'; $newFlag = 'Y'; ?>
        <?php } } ?>
        <?php } ?>
    </tbody>
</table>