<div class="fixed-top-header">
    <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
        <tbody>
            <?php for($row=0;$row<2;$row++) { ?>
            <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
                <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
                <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?></td>
                <?php if(intval($col) == (intval($this->currentColumnIndex)+2)) {  ?>
                <?php if(intval($row) == 0) { ?>
                <td class="ExcelTableFormationCol col-<?php echo intval($this->currentColumnIndex)+3; ?>">
                <span class="top-col"><?php echo intval($this->currentColumnIndex)+3; ?></span>
                
            </td>
                <?php } else if(intval($row) == 1){ ?>
                <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+3; ?> Process">
                    <div data-id="<?php echo intval($this->currentColumnIndex)+3; ?>" class="col-head col-wrap show">
                        <div class="node-circle node-white-circle node-white-circle">N</div>
                        <span class="icon operation-icon"></span><span class="col-head-title">Process</span><i class="fa fa-caret-left arrow"></i>
                    </div>
                </td>
                <?php } ?>
                <?php } ?>
                <?php } ?>
               
            </tr>
            <?php }?>
        </tbody>
    </table>
</div>
<table border="" class="fixed-left-column" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
    <tbody>
        <?php 


        $addRow = 0; $newFlag = ''; $flag = ''; 
            for($row=0;$row<count($this->tableDataArray);$row++) {
            ?>
        <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
            <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
            <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?></td>
            <?php if(intval($col) == (intval($this->currentColumnIndex)+2)) {  ?>
            <?php if(intval($row) == 0) { ?>
            <td class="ExcelTableFormationCol col-<?php echo intval($this->currentColumnIndex)+3; ?>">
                <span class="top-col"><?php echo intval($this->currentColumnIndex)+3; ?></span>
                
            </td>
            
            <?php } else if(intval($row) == 1){ ?>
            <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+3; ?> Process">
                <div data-id="<?php echo intval($this->currentColumnIndex)+3; ?>" class="col-head col-wrap show">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon operation-icon"></span><span class="col-head-title">Process</span><i class="fa fa-caret-left arrow"></i>
                </div>
            </td>
            
            <?php } else { ?>
            
            <?php if($newFlag == 'Y') { ?>
            <?php ?>
            <td class="ExcelTablerow Role-segment  col-<?php echo intval($this->currentColumnIndex)+3; ?> process-series ">
                <?php echo $this->processArray[2]['process']; ?>
            </td>
            
            
            <?php $newFlag = 'N'; }
			else if($addRow < $this->currentColumnSegments) {
                ?>
            <td class="ExcelTablerow Role-segment col-<?php echo intval($this->currentColumnIndex)+3; ?> process-series "><?php echo $this->processArray[0]['process']; ?></td>
            
            <?php  $flag = 'Y';  ?>
            <?php }  else {  ?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?>"></td>
            <?php } ?>
            <?php } ?>
            <?php } ?>
            <?php } ?>
        </tr>
        <?php if($flag == 'Y') { ?>
        <?php if(intval($addRow) < $this->currentColumnSegments) { ?>
        <?php for($i=1;$i<count($this->processArray)-1;$i++) { ?>
        <tr class="" >
            <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
            <td class="col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow<?php } ?>">
                <?php if(intval($this->currentColumnIndex)+3 > intval($col)) { ?>
                <div class="blank-div segment-node"></div>
                <?php } ?>
            </td>
            <?php if(intval($col) == (intval($this->currentColumnIndex)+2)) {  ?>
            <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> process-series">
            <?php echo $this->processArray[$i]['process']; ?></td>
            <?php } ?>
            <?php } ?>
        </tr>
        <?php } ?>
        <?php $addRow++;$flag = 'N'; $newFlag = 'Y'; ?>
        <?php } } ?>
        <?php } ?>
    </tbody>
</table>