<div class="span8 req-task-tree permission-table-wrap paper-line-center" id="center-screen">
    <div id="entr_center_content" style="opacity: 1; border-bottom-style: none;">
        <div id="main" style="height: 511px;">
            <div class="nano has-scrollbar">
                <div class="overthrow nano-content description" tabindex="0">
                    <section id="node-wrapper" class="clearfix">
                        <ol class="sortable ui-sortable">
                            <li id="firstNode" data-id="node-6" class="mjs-nestedSortable-expanded entrnode download-cashed mjs-nestedSortable-branch" data-type="node_role">
                                <div class="node-content clearfix node-selected">
                                    <div class="node-left">
                                        <div data-id="node-6" class="node-circle node-white-circle-expanded node-green-circle-expanded">N</div>
                                        <span class="disclose"><span></span></span>
                                        <div class="node-head node-input"> 
                                            <span>Classes</span> 
                                            <span class="node-input">
                                            <input type="hidden" class="node-title-text" name="title" value="Classes">
                                            <input type="hidden" class="caption-text" name="captionText" value="Classes">
                                            <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="Pane 1">
                                            <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                            <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                            <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                            <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                            <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                            <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                            </span> 
                                        </div>
                                    </div>
                                    <div class="node-right">
                                        <a id="classesDisplayPlus~6~Classes" class="action-move get-section-details"><span><i class="fa fa fa-plus"></i></span></a>
                                        <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a> 
                                        <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a> 
                                    </div>
                                </div>
                                <ol class="classDisplaySortable">
                                    <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                        <div class="node-content clearfix">
                                            <div class="node-left">
                                                <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                <span class="disclose"><span></span></span>
                                                <div class="node-head node-input"> 
                                                    <span></span> 
                                                    <span class="node-input">
                                                    <input type="text" class="node-title-text" placeholder="New Class Node" name="title" value="" style="display:block">
                                                    <input type="hidden" class="caption-text" name="captionText" value="">
                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                    </span> 
                                                </div>
                                            </div>
                                            <div class="node-right"> 
                                                <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                <a class="action-move deleteNode"><span><i class="fa fa fa-times"></i></span></a>
                                            </div>
                                        </div>
                                        <ol>
                                            <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                <div class="node-content clearfix">
                                                    <div class="node-left">
                                                        <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                        <span class="disclose"><span></span></span>
                                                        <div class="node-head node-input"> 
                                                            <span>Class Attributes</span> 
                                                            <span class="node-input">
                                                            <input type="text" class="node-title-text" name="title" value="Class Attributes" inputchange="1">
                                                            <input type="hidden" class="caption-text" name="captionText" value="Class Attributes">
                                                            <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                            <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                            <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                            <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                            <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                            <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                            <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                            </span> 
                                                        </div>
                                                    </div>
                                                    <div class="node-right">
                                                        <!-- <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                            <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>-->
                                                    </div>
                                                </div>
                                                <ol>
                                                    <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input fix-width-input"> 
                                                                    <span>Version</span> 
                                                                    <span class="node-input ">
                                                                    <input type="text" class="node-title-text" placeholder="Version" name="title" value="" style="display:block;">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Version">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right">
                                                                <!--<a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                    <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                    <a class="action-move deleteNode"><span><i class="fa fa fa-times"></i></span></a>-->
                                                            </div>
                                                        </div>
                                                        <ol>
                                                        </ol>
                                                    </li>
                                                    <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input fix-width-input"> 
                                                                    <span>Singular</span> 
                                                                    <span class="node-input ">
                                                                    <input type="text" class="node-title-text" placeholder="Singular" name="title" value="" style="display:block;">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Singular">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right">
                                                                <!--<a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                    <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                    <a class="action-move deleteNode"><span><i class="fa fa fa-times"></i></span></a>-->
                                                            </div>
                                                        </div>
                                                        <ol>
                                                        </ol>
                                                    </li>
                                                    <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input fix-width-input"> 
                                                                    <span>Plural</span> 
                                                                    <span class="node-input ">
                                                                    <input type="text" class="node-title-text" placeholder="Plural" name="title" value="" style="display:block;">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Plural">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right">
                                                                <!--<a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                    <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                    <a class="action-move deleteNode"><span><i class="fa fa fa-times"></i></span></a>-->
                                                            </div>
                                                        </div>
                                                        <ol>
                                                        </ol>
                                                    </li>
                                                    <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input fix-width-input"> 
                                                                    <span>Description</span> 
                                                                    <span class="node-input ">
                                                                    <input type="text" class="node-title-text" placeholder="Description" name="title" value="" style="display:block;">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Description">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right">
                                                                <!--<a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                    <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                                    <a class="action-move deleteNode"><span><i class="fa fa fa-times"></i></span></a>-->
                                                            </div>
                                                        </div>
                                                        <ol>
                                                        </ol>
                                                    </li>
                                                </ol>
                                            </li>
                                            <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                <div class="node-content clearfix">
                                                    <div class="node-left">
                                                        <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                        <span class="disclose"><span></span></span>
                                                        <div class="node-head node-input"> 
                                                            <span>Instance Template</span> 
                                                            <span class="node-input">
                                                            <input type="text" class="node-title-text" name="title" value="Instance Template" inputchange="1">
                                                            <input type="hidden" class="caption-text" name="captionText" value="Instance Template">
                                                            <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                            <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                            <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                            <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                            <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                            <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                            <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                            </span> 
                                                        </div>
                                                    </div>
                                                    <div class="node-right"></div>
                                                </div>
                                                <ol>
                                                    <li data-id="node-00" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input"> 
                                                                    <span>Properties</span> 
                                                                    <span class="node-input">
                                                                    <input type="text" inputchange="1" class="node-title-text" placeholder="Properties" name="title" value="Properties">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Properties">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right"> 
                                                                <a class="action-move" onclick="addProperty(this);"><span><i class="fa fa fa-plus"></i></span></a>
                                                                <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                            </div>
                                                        </div>
                                                        <ol></ol>
                                                    </li>
                                                    <li data-id="node-00" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input"> 
                                                                    <span>Operations</span> 
                                                                    <span class="node-input">
                                                                    <input type="text" inputchange="1" class="node-title-text" placeholder="Operations" name="title" value="Operations">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Operations">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right"> 
                                                                <a class="action-move" onclick="addOperation(this);"><span><i class="fa fa fa-plus"></i></span></a>
                                                                <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                            </div>
                                                        </div>
                                                        <ol></ol>
                                                    </li>
                                                    <li data-id="node-00" class="mjs-nestedSortable-leaf mjs-nestedSortable-expanded entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                        <div class="node-content clearfix">
                                                            <div class="node-left isSorting_a">
                                                                <div data-id="node-00" class="node-circle node-white-circle-expanded">N</div>
                                                                <span class="disclose"><span></span></span>
                                                                <div class="node-head node-input"> 
                                                                    <span>Events</span> 
                                                                    <span class="node-input">
                                                                    <input type="text" inputchange="1" class="node-title-text" placeholder="Events" name="title" value="Events">
                                                                    <input type="hidden" class="caption-text" name="captionText" value="Events">
                                                                    <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                                    <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                                    <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                                    <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                                    <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                                    <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                                    <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                                    </span> 
                                                                </div>
                                                            </div>
                                                            <div class="node-right"> 
                                                                <a class="action-move" onclick="addEvent(this);"><span><i class="fa fa fa-plus"></i></span></a>
                                                                <a class="action-move"><span><i class="fa fa-caret-right"></i></span></a>
                                                                <a class="action-move"><span><i class="fa fa-caret-down"></i></span> </a>
                                                            </div>
                                                        </div>
                                                        <ol></ol>
                                                    </li>
                                                </ol>
                                            </li>
                                            <li data-id="node-00" data-type="node_class" class="mjs-nestedSortable-leaf entrnodec download-cashed mjs-nestedSortable-branch mjs-nestedSortable-collapsed">
                                                <div class="node-content clearfix">
                                                    <div class="node-left">
                                                        <div data-id="node-00" class="node-circle node-white-circle-expanded entrnode"> N</div>
                                                        <span class="disclose"><span></span></span>
                                                        <div class="node-head node-input"> 
                                                            <span>Instances</span> 
                                                            <span class="node-input"> 
                                                            <input type="text" class="node-title-text" name="title" value="Instances" inputchange="1">
                                                            <input type="hidden" class="caption-text" name="captionText" value="Instances">
                                                            <input type="hidden" data-nodex-id="1" data-nodex-attrid="1" data-type="checkbox" class="pane-1 node-input-prop" name="prop_Pane_1" value="">
                                                            <input type="hidden" data-nodex-id="2" data-nodex-attrid="" data-type="radio" class="node-type node-input-prop" name="prop_Node_Type" value="">
                                                            <input type="hidden" data-nodex-id="3" data-nodex-attrid="" data-type="radio" class="value node-input-prop" name="prop_Value" value="">
                                                            <input type="hidden" data-nodex-id="4" data-nodex-attrid="" data-type="radio" class="data-type node-input-prop" name="prop_Data_Type" value="">
                                                            <input type="hidden" data-nodex-id="5" data-nodex-attrid="1" data-type="checkbox" class="mono is-class node-input-prop" name="prop_Is_Class" value="">
                                                            <input type="hidden" data-nodex-id="6" data-nodex-attrid="1" data-type="checkbox" class="mono is-instance node-input-prop" name="prop_Is_Instance" value="">
                                                            <input type="hidden" data-nodex-id="7" data-nodex-attrid="" data-type="radio" class="access-modifier node-input-prop" name="prop_Access_Modifier" value="">
                                                            </span> 
                                                        </div>
                                                    </div>
                                                    <div class="node-right"></div>
                                                </div>
                                                <ol></ol>
                                            </li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </section>
                </div>
                <div class="nano-pane" style="display: none;">
                    <div class="nano-slider" style="height: 495px; transform: translate(0px, 0px);"></div>
                </div>
            </div>
        </div>
        <style>
            .custom-menu .custom-edit-node {
            display:none;
            }
        </style>
    </div>
</div>

