<div class="fixed-top-header">
   <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
      <tbody>
         <?php for($row=0;$row<2;$row++) { ?>
      <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
         <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
         <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>"><?php echo $this->tableDataArray[$row][$col]['data'];?></td>
         <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
         <?php if(intval($row) == 0) { ?>
         <td class="ExcelTableFormationCol col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <span class="top-col"><?php echo intval($this->currentColumnIndex)+2; ?></span>
            <i class="fa fa-plus add add-phase-segment"></i>
           
         </td>
         <td class="ExcelTableFormationCol collapse event col-<?php echo intval($this->currentColumnIndex)+3; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+3; ?></span></td>
         <?php } else if(intval($row) == 1){ ?>
         <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <div data-id="<?php echo intval($this->currentColumnIndex)+2; ?>" class="col-head">
               <div class="node-circle node-white-circle node-white-circle">N</div>
               <span class="icon phase-icon"></span><span class="col-head-title">Phase</span>
               <i class="fa fa-caret-left arrow"></i> 
            </div>
         </td>
         <td class="ExcelTablerow border-top collapse event col-<?php echo intval($this->currentColumnIndex)+3; ?>">
            <div data-id="<?php echo intval($this->currentColumnIndex)+3; ?>" class="col-head">
               <div class="node-circle node-white-circle node-white-circle">N</div>
               <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> 
            </div>
         </td>
         <?php } ?>
         <?php } ?>
         <?php } ?>
      </tr>
      <?php }?>
      </tbody>
   </table>
</div>
<!-- <div class="fixed-top-header">
   <table border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
      <tbody>
      <tr>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
      </tr>
      </tbody>
   </table>
</div> -->
<table border="" class="fixed-left-column" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
   <tbody>
      <?php for($row=0;$row<count($this->tableDataArray);$row++) { ?>
      <tr class="<?php echo $this->tableDataArray[$row][0]['trClass'];?>" >
         <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
         <td class="<?php echo $this->tableDataArray[$row][$col]['tdClass'];?>">
         <?php echo $this->tableDataArray[$row][$col]['data'];?></td>
         <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
         <?php if(intval($row) == 0) { ?>
         <td class="ExcelTableFormationCol col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <span class="top-col"><?php echo intval($this->currentColumnIndex)+2; ?></span>
            <i class="fa fa-plus add add-phase-segment"></i>
            <div class="add-col-wrap add-colums">
               <ul class="dropdown-menu show-<?php echo intval($this->currentColumnIndex)+2; ?>">
                  <li class="no-bg ">
                     <a class="add-left disabled">
                        <div class=" node-circle node-white-circle-expanded">N</div>
                        Add left 
                     </a>
                     <ul class="sub-item">
                        <li class="no-bg disabled">
                           <a class=" add-left-col">
                              <div class="node-circle node-white-circle">N</div>
                              Phase 
                           </a>
                        </li>
                        <li class="no-bg disabled">
                           <a class="">
                              <div class="node-circle node-white-circle">N</div>
                              Operation 
                           </a>
                        </li>
                     </ul>
                  </li>
                  <li role="presentation">
                     <a class="add-right">
                        <div class="node-circle node-white-circle-expanded">N</div>
                        Add right 
                     </a>
                     <ul class="sub-item">
                        <li>
                           <a data-toggle="modal" data-target="#Seriespoup" class="popupPhaseClass">
                              <div class="node-circle node-white-circle">N</div>
                              Phase 
                           </a>
                        </li>
                        <li>
                           <a class="add-operation-series" href="#">
                              <div class="node-circle node-white-circle">N</div>
                              Operation 
                           </a>
                        </li>
                     </ul>
                  </li>
                   <li role="presentation" class="delete-series no-bg">
                       <a role="menuitem" tabindex="-1" class="" >
                           <div class=" node-circle node-white-circle">N</div>
                          Delete Series
                       </a> 
                   </li>
               </ul>
            </div>
         </td>
         <td class="ExcelTableFormationCol collapse event col-<?php echo intval($this->currentColumnIndex)+3; ?>"><span class="top-col"><?php echo intval($this->currentColumnIndex)+3; ?></span></td>
         <?php } else if(intval($row) == 1){ ?>
         <td class="ExcelTablerow border-top col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <div data-id="<?php echo intval($this->currentColumnIndex)+2; ?>" class="col-head">
               <div class="node-circle node-white-circle node-white-circle">N</div>
               <span class="icon phase-icon"></span><span class="col-head-title">Phase</span>
               <i class="fa fa-caret-left arrow"></i> 
            </div>
         </td>
         <td class="ExcelTablerow border-top collapse event col-<?php echo intval($this->currentColumnIndex)+3; ?>">
            <div data-id="<?php echo intval($this->currentColumnIndex)+3; ?>" class="col-head">
               <div class="node-circle node-white-circle node-white-circle">N</div>
               <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> 
            </div>
         </td>
         <?php } else { ?>
         <?php if(intval($addRow) < $this->currentColumnSegments) { ?>
         <?php if($newFlag == 'Y') { ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <?php echo $this->phaseArray[1]['phase']; ?>
         </td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"><?php echo $this->phaseArray[1]['event']; ?></td>
         <?php $newFlag = 'N'; } else { ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <?php echo $this->phaseArray[0]['phase']; ?>
         </td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"><?php echo $this->phaseArray[0]['event']; ?></td>
         <?php $flag = 'Y'; ?>
         <?php } ?>
         <?php } else { ?>
         <?php if($newFlag == 'Y') { ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <?php echo $this->phaseArray[1]['phase']; ?>
         </td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"><?php echo $this->phaseArray[1]['event']; ?></td>
         <?php $newFlag = 'N'; } else { ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>"></td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"></td>
         <?php } ?>
         <?php $flag = 'N'; } ?>
         <?php } ?>
         <?php } ?>
         <?php } ?>
      </tr>
      <?php if($flag == 'Y' && intval($addRow) < $this->currentColumnSegments) { ?>
      <tr class="" >
         <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
         <td class="col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow<?php } ?>">
            <?php if(intval($this->currentColumnIndex)+2 > intval($col)) { ?>
            <div class="blank-div segment-node"></div>
            <?php } ?>
         </td>
         <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <?php echo $this->phaseArray[1]['phase']; ?>
         </td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"><?php echo $this->phaseArray[1]['event'];  ?>  </td>
         <?php } ?>
         <?php } ?>
      </tr>
      <?php for($index=0;$index<intval($this->noOfSegment)-1;$index++) { ?>
      <tr class="" >
         <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
         <td class="col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow<?php } ?>">
            <?php if(intval($this->currentColumnIndex)+2 > intval($col)) { ?>
            <div class="blank-div segment-node"></div>
            <?php } ?>
         </td>
         <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <?php echo $this->phaseArray[0]['phase']; ?>
         </td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"><?php echo $this->phaseArray[0]['event']; ?></td>
         <?php } ?>
         <?php } ?>
      </tr>
      <?php if(intval($index) <  intval($this->noOfSegment)-2) { ?>
      <tr class="" >
         <?php for($col=0;$col<count($this->tableDataArray[$row]);$col++) { ?>
         <td class="col-<?php echo intval($col); ?><?php if(intval($col) == 0 ){ ?> ExcelTableFormationRow<?php } else{ ?> ExcelTablerow<?php } ?>">
            <?php if(intval($this->currentColumnIndex)+2 > intval($col)) { ?>
            <div class="blank-div segment-node"></div>
            <?php } ?>
         </td>
         <?php if(intval($col) == (intval($this->currentColumnIndex)+1)) {  ?>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+2; ?>">
            <?php echo $this->phaseArray[1]['phase']; ?>
         </td>
         <td class="ExcelTablerow col-<?php echo intval($this->currentColumnIndex)+3; ?> collapse event"><?php echo $this->phaseArray[1]['event']; ?></td>
         <?php } ?>
         <?php } ?>
      </tr>
      <?php } ?>
      <?php } ?>
      <?php $addRow++; $flag = 'N'; $newFlag = 'Y'; ?>
      <?php } ?>
      <?php } ?>
   </tbody>
</table>
