<div id="marketplace" class="marketplace-wrapper">
	<div class="nano">
		<div class="nano-content">
		    <div class="market-banner">
			    <div class="top-section">
			        <img src="<?php echo PU_CDN_URL; ?>public/img/prospus-white-logo.png">
			        <h2>Prospus Marketplace</h2>
			        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>    
			    </div>
			    <div class="services">
			    	<div class="row">
			    		<div class="col-md-4">
			    			<div>
			    				<span class="lg-icon">
			    					<i class="micro-icon"></i>
			    				</span>
			    				<h2>micro solution</h2>
			    				<p>We build digital products, from beginning to end.</p>

			    			</div>
			    		</div>
			    		<div class="col-md-4">
			    			<div>
			    				<span class="lg-icon">
			    					<i class="plugin-icon"></i>
			    				</span>
			    				<h2>plugin anywhere</h2>
			    				<p>We build digital products, from beginning to end.</p>

			    			</div>
			    		</div>
			    		<div class="col-md-4">
			    			<div>
			    				<span class="lg-icon">
			    					<i class="custom-icon"></i>
			    				</span>
			    				<h2>CUSTOM DEVELOPMENT</h2>
			    				<p>We build digital products, from beginning to end.</p>
			    			</div>
			    		</div>

			    	</div>
			    </div>
			</div>

			<div class="app-list-pane">
				<h2 class="bdr-heading"><span>Our Solutions</span></h2>
				<div class="app-list-row">
					<div class="app-list-col">
					    <div class="app-left-pane">
					    	<span class="app-icon"><img src="<?php echo PU_CDN_URL;?>public/img/app_1.png"></span>
					    	<span class="app-rating">
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    	</span>
					    </div>
				        <div class="app-right-pane">
						    <h2>Expense Transaction</h2>
						    <h2>Publisher: Prospus</h2>
						    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
						    <div class="app-bottom-pane">
						    	<button class="btn btn-blue">Details</button>
						    	<button class="btn btn-blue active">Buy Now</button>
						    </div>
						</div> 
					</div>
					<div class="app-list-col">
					    <div class="app-left-pane"><span class="app-icon"><img src="public/img/app_2.png"></span></div>
				        <div class="app-right-pane">
						    <h2>Expense Transaction</h2>
						    <h2>Publisher: Prospus</h2>
						    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
						    <div class="app-bottom-pane">
						    	<button class="btn btn-blue">Details</button>
						    	<button class="btn btn-blue active">Buy Now</button>
						    </div>
						</div> 
					</div>
					<div class="app-list-col">
					    <div class="app-left-pane"><span class="app-icon"><img src="public/img/app_3.png"></span></div>
				        <div class="app-right-pane">
						    <h2>Expense Transaction</h2>
						    <h2>Publisher: Prospus</h2>
						    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
						    <div class="app-bottom-pane">
						    	<button class="btn btn-blue">Details</button>
						    	<button class="btn btn-blue active">Buy Now</button>
						    </div>
						</div> 
					</div>
					<div class="app-list-col">
					    <div class="app-left-pane">
					    	<span class="app-icon"><img src="<?php echo PU_CDN_URL;?>public/img/app_1.png"></span>
					    	<span class="app-rating">
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    		<i class="fa fa-star-o"></i>
					    	</span>
					    </div>
				        <div class="app-right-pane">
						    <h2>Expense Transaction</h2>
						    <h2>Publisher: Prospus</h2>
						    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
						    <div class="app-bottom-pane">
						    	<button class="btn btn-blue">Details</button>
						    	<button class="btn btn-blue active">Buy Now</button>
						    </div>
						</div> 
					</div>
					<div class="app-list-col">
					    <div class="app-left-pane"><span class="app-icon"><img src="public/img/app_2.png"></span></div>
				        <div class="app-right-pane">
						    <h2>Expense Transaction</h2>
						    <h2>Publisher: Prospus</h2>
						    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
						    <div class="app-bottom-pane">
						    	<button class="btn btn-blue">Details</button>
						    	<button class="btn btn-blue active">Buy Now</button>
						    </div>
						</div> 
					</div>
					<div class="app-list-col">
					    <div class="app-left-pane"><span class="app-icon"><img src="public/img/app_3.png"></span></div>
				        <div class="app-right-pane">
						    <h2>Expense Transaction</h2>
						    <h2>Publisher: Prospus</h2>
						    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
						    <div class="app-bottom-pane">
						    	<button class="btn btn-blue">Details</button>
						    	<button class="btn btn-blue active">Buy Now</button>
						    </div>
						</div> 
					</div>

				</div>
			</div>
		</div>
	</div>
	
</div>