<?php
/*
 * SERVER SETTINGS
 */
ini_set("display_errors", 0);
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Content-Type");

$host       = 'http://'.$_SERVER['HTTP_HOST'];
$doc_root   = $_SERVER['DOCUMENT_ROOT'];
DEFINE('PAGE_PLUGIN_CONFIG_FILE', 'config_prod.php');
DEFINE('BASE_URL_API', $host.'/puidata/page_plugin/');
DEFINE('WEB_API_URL', $host.'/pui/');
DEFINE('UPLOAD_URL_API', 'http://puprodcdn.s3.amazonaws.com/public/nodeZimg/');
DEFINE('ABS_API_URL', 'http://puprodcdn.s3.amazonaws.com/');
DEFINE('PRINT_API_URL', $host.'/puidata/print_only.php');
DEFINE('MAPPING_API_URL', $host.'/puidata/marinemax_api/index.php');
DEFINE('MARINEMAX_ABSO_URL_API', $doc_root.'/puidata/page_plugin/api_files/');
DEFINE('MARINEMAX_API_URL', 'https://integrator.marinemax.com/rest/V1/');
DEFINE('FILE_DOMAIN', 'pro.pu.prospus.com');
DEFINE('APPONE_API_URL', 'https://gateway.appone.net');

/*
 * ROLE SETTINGS
 */
DEFINE('ADMIN', '603696');
DEFINE('ROLE_SALES_CONSULTANT', '436104');  
DEFINE('ROLE_BUSINESS_MANAGER', '436099');  /*========>This is for Brokerage Consultant<=================================*/
DEFINE('ROLE_BM', '450187');                
DEFINE('ROLE_TEAM_SUPPORT', '454669');      
DEFINE('ROLE_SELLER', '454664');            
DEFINE('ROLE_BUYER', '454659');             
DEFINE('ROLE_REVENUE_ACCOUNTANT', '454674');
DEFINE('ROLE_REVENUE_MANAGER', '454679');   
DEFINE('ROLE_CONTROLLER', '1462795');   
DEFINE('ROLE_DIRECTOR', '1462785');   
DEFINE('MAPPING_ROLE_ACTOR_PID', '5026');
DEFINE('MAPPING_ROLE_ACTOR_CLASS_ID', 663);
DEFINE('VISIBLE_ROLES_PROP_ID',7405);
DEFINE('REQUIRED_ROLES_PROP_ID',7406);
DEFINE('ROLE_PID', '3297');
DEFINE('LOCATION_ROLE_DETAILS', '858');
DEFINE('ROLE_SUPERADMIN', '1746983');

/*
 * PHASE SETTINGS
 */
DEFINE('PHASEI','686864');
DEFINE('PHASEII','686869');
DEFINE('PHASEIII','686884');
DEFINE('PHASE_SEQUENCE', '7689');
DEFINE('PHASE_CLASS_ID', '782');
DEFINE('PHASE_DEAL_P_ID', '6885');
DEFINE('PHASE_PHASE_P_ID', '6886');
DEFINE('PHASE_ROLE_P_ID', '6887');
DEFINE('PHASE_STATUS_P_ID', '6888');
DEFINE('MANAGE_PHASE_SEQUENCE', '806');

/*
 * OPEREATION SETTINGS
 */
DEFINE('OPERATION_PID', '5027');
DEFINE('OPERATION_DOCUMENT_UPLOADED_CLASS_ID', '849');
DEFINE('MAPPING_DEAL_OPERATION_CLASS_ID', '724');
define('OPERATION_PHASE_CLASS_ID', '781');
DEFINE('LAST_VISITED_OPERATION_PID', '7992');
DEFINE('OPERATION_CLASS_ID', '661');
DEFINE('OPERATIONS_ROLES_CLASS_ID',662);
DEFINE('OPERATION_PROPERTY_MAP_DEAL_CLASS_ID', '787');
DEFINE('OPERATION_ROLE_CLASS_ID', '662'); //'416174'

/*
 * PASS DEAL SETTINGS
 */
DEFINE('PASSED_DEAL_BY_ROLES_CLASS_ID',855);
DEFINE('PASSED_DEAL_BY_ROLES_CLASS_NID',1377982);
DEFINE('PASSED_DEAL_D_PID',8454);
DEFINE('PASSED_DEAL_FR_PID',8455);
DEFINE('PASSED_DEAL_TR_PID',8456);
DEFINE('PASSED_DEAL_A_PID',8457);
DEFINE('PASSED_DEAL_TIMESTAMP',8749);

/*
 * DEAL SETTINGS
 */
DEFINE('DEAL_VIEW_ID', '660336');
DEFINE('DEAL_PHASE_PROPERTY_ID', '7744');
DEFINE('DEAL_PHASE_VERSION_PROPERTY_ID', '7745');
DEFINE('DEAL_CLASS_ID', '655');
DEFINE('DEAL_STATUS_PID','3287');
DEFINE('DEAL_SUB_STATUS_PID','8848');
DEFINE('DEAL_PERMISSIONS_PROP_ID',7404);
DEFINE('DEAL_PID','3299');
DEFINE('DEAL_CUSTOMER_PID', '3210');
DEFINE('DEAL_STOCK_PID','3216');
DEFINE('DEAL_SALES_QUOTE_PID','3227');
DEFINE('DEAL_FI_QUOTE_PID','3228');
DEFINE('DEAL_COBUYER_PID','8383');
DEFINE('PROPERTYID_OF_DEAL_ID','3208');
DEFINE('DEAL_CLASS_NODEID','396138');
DEFINE('DEAL_REJECTION','823');
DEFINE('DEAL_APPONE_CLASS_ID', 825);
DEFINE('DEAL_APPONE_APPID_PROPERTY_ID', 8029);
DEFINE('DEAL_APPONE_REQUEST_PROPERTY_ID', 8030);
DEFINE('DEAL_APPONE_RESPONSE_PROPERTY_ID', 8031);
DEFINE('DEAL_PAYMENT_TYPE_PROPERTY_ID', 3231);
DEFINE('DEAL_CONTROL_VERSION_IDS',8450);
DEFINE('DEAL_NET_SALE_LIST',8747);
DEFINE('DEAL_SIZE',8748);
DEFINE('DEAL_TIMESTAMP_PID', 8913);
DEFINE('DEAL_ASSIGNED_PID', 8914);
DEFINE('DEAL_CREATOR_CLASS_ID',778);
DEFINE('DEAL_ON_HOLD_STATUS',3287);
DEFINE('DEAL_LOCATION_PID',6807); 
DEFINE('DEAL_EXISTS_PID',9097); 
DEFINE('ESTIMATED_CLOSING_DATE',6802);
DEFINE('DEAL_CUSTOMER_FIRST_NAME',3211); 
DEFINE('DEAL_CUSTOMER_LAST_NAME',3240); 


/*
 * PPC SETTINGS
 */
DEFINE('PROPERTYID_OF_REVIEW_ID','7986');
DEFINE('PERFORMANCE_REVIEW_CLASS_NODEID','839021');
DEFINE('PPC_SETTING','Employee Review');

/*
 * MENU SETTINGS
 */
DEFINE('MENU_RAs', '1457918');
DEFINE('MENU_RMs','1457928');
DEFINE('MINE','1457938');
DEFINE('MENU_RM_C_D','1457948');
DEFINE('MENU_C_D','1457958');
DEFINE('ADD_DEAL_MENU_LIST_ID', '398431');
DEFINE('DELETE_DEAL_MENU_LIST_ID', '398440');

/*
 * APPONE SETTINGS
 */
DEFINE('APPONE_UNSIGNED_PROPERTY_ID', 7211);
DEFINE('APPONE_OPERATION_CLASS_ID', 788);

/*
 * NODEZ Astra API SETTINGS
 */
DEFINE('NODEZ_DATASOURCE_SEARCH_ARRAY', json_encode(array('#nbsp#', '#,#', '#-#')));
DEFINE('NODEZ_DATASOURCE_REPLACE_ARRAY', json_encode(array(' ', ', ', '-')));

/*
 * STORE CLASS SETTINGS
 */
DEFINE('STORE_CLASS_ID', 822);
DEFINE('STORE_LOCATION_PROPERTY_ID', 7988);

/*
 * DOCUMENT SETTINGS
 */
DEFINE('DOCUMENT_PID', '5028');
DEFINE('DOCUMENT_TITLE', 'Document');

/*
 * CUSTOMER SETTINGS
 */
DEFINE('CUSTOMER_CLASS_ID', '770');
DEFINE('CUSTOMER_CLASS_NID', '601263');
DEFINE('CUSTOMER_PID', '7202');

/*
 * BUYER SETTINGS
 */
DEFINE('CO_BUYER_CLASS_ID', '847');
DEFINE('COBUYER_CLASS_NID', '1130248');
DEFINE('COBUYER_PID','8452');

/*
 * SALES SETTINGS
 */
DEFINE('SALES_QUOTES_CLASS_ID', '790');
DEFINE('SALES_QUOTE_CLASS_NID', '793357');
DEFINE('SALES_QUOTE_PID','7204');

/*
 * MANAGE CONTROL SETTINGS
 * '416174'
 */
DEFINE('MANAGE_CONTROL_CLASS_ID', '853'); 

/*
 * ACTOR SETTINGS
 */
DEFINE('ACTOR_PID','3298');

/*
 * STOCK SETTINGS
 */
DEFINE('STOCK_PID','7203');

/*
 * PDF SETTINGS
 */
DEFINE('PDF_TITLE', 'PDF Template NID');

/*
 * FI QUOTE SETTINGS
 */
DEFINE('FI_QUOTE_CLASS_NID', '796488');
DEFINE('FI_QUOTE_SALESPERSON_CLASS_NID', '794374');
DEFINE('FI_QUOTE_PID','7205');

/*
 * FUNDING SETTINGS
 */
DEFINE('COMPLETE_FUNDING_ID', '757734');

/*
 * ON HOLD CLASS SETTINGS
 */
DEFINE('ON_HOLD_CLASS_ID', '859');

/*
 * FORM SETTINGS
 */
DEFINE('FORM_PID', '5029');


/*
 * UNIT CLASS SETTINGS
 */
DEFINE('UNIT_CLASS_NID', '641371');
DEFINE('UNIT_CLASS_ID', '776');
DEFINE('UNIT_MOTOR_CLASS_NID', '640713');
/*
 * FINANCE DEAL CLASS SETTINGS
 */
DEFINE('FINANCE_DEALS_CLASS_ID', '801');


/*
 * INDIVIDUAL INSTANCE SETTINGS
 * '1142405'
 */
DEFINE('INDIVIDUAL_INSTANCE_NODE_ID', '1196249'); 

/*
 * ROLE ARRAY SETTINGS
 */
$rolePhaseArray=  json_encode(array(ROLE_BM=>'686864',ROLE_REVENUE_ACCOUNTANT=>'686869',ROLE_REVENUE_MANAGER=>'686884'));
DEFINE('ROLE_NAME', json_encode(array(ROLE_SALES_CONSULTANT => 'Sales Consultant',ROLE_BM => 'Business Manager',ROLE_BUSINESS_MANAGER => 'Brokerage Consultant',ROLE_REVENUE_ACCOUNTANT => 'Revenue Accoutant')));


DEFINE('TRADES_CLASS_NID', '793864'); 

/* -----------------------
  | MENU OPERATION INSTANCE ID FOR SUPER ADMIN ROLE    |
  ------------------------ */
DEFINE('SUPER_ADMIN_MENU_OPERATION_INSTANCE_ID','1754498');
DEFINE('OPERATION_TRADE_IN_PROPERTY_ID', '6957');
DEFINE('OPERATION_CONDITION_PROPERTY_ID', '6956');
DEFINE('OPERATION_DEAL_TYPE_PROPERTY_ID', 3290);
DEFINE('OPERATION_TYPE_PROPERTY_ID',7397);
DEFINE('OPERATION_PHASE_CAPPING_PROPERTY_ID',7794);
DEFINE('OPERATION_PHASE_FINANCING_PROPERTY_ID',7795);
DEFINE('OPERATION_PHASE_CASH_PROPERTY_ID',7796);
DEFINE('OPERATION_PHASE_CLOSING_PROPERTY_ID',7797);
DEFINE('OPERATION_PHASE_POSTING_PROPERTY_ID',7798);
DEFINE('OPERATION_OTHER_ROLE_PERMISSION_PROPERTY_ID', 8849);
DEFINE('OPERATION_OWNED_BY_PROPERTY_ID',8850);
DEFINE('OPERATION_READ_BY_PROPERTY_ID',8851);
DEFINE('OPERATION_EDITED_BY_PROPERTY_ID',8852);
DEFINE('OPERATION_PRINT_ORDER_PROPERTY_ID',8878);
DEFINE('OPERATION_READ_ONLY_OWNER_PROPERTY_ID',9140);
DEFINE('OPERATION_NAME_PROPERTY_ID', 3281);
DEFINE('OPERATION_ICON_PROPERTY_ID', 3282);
DEFINE('OPERATION_DESCRIPTION_PROPERTY_ID', 3283);
DEFINE('OPERATION_VIEW_NID_PROPERTY_ID', 3284);
DEFINE('OPERATION_SEQUENCE_PROPERTY_ID', 3285);
DEFINE('OPERATION_ROLE_PROPERTY_ID', 3288);
DEFINE('OPERATION_PDF_TEMPLATE_NID_PROPERTY_ID', 3472);
DEFINE('OPERATION_NODE_CLASS_PROPERTY_ID', json_encode(array(OPERATION_PHASE_CAPPING_PROPERTY_ID, OPERATION_PHASE_FINANCING_PROPERTY_ID, OPERATION_PHASE_CASH_PROPERTY_ID, OPERATION_PHASE_CLOSING_PROPERTY_ID, OPERATION_PHASE_POSTING_PROPERTY_ID, OPERATION_OWNED_BY_PROPERTY_ID, OPERATION_READ_BY_PROPERTY_ID, OPERATION_EDITED_BY_PROPERTY_ID, OPERATION_PRINT_ORDER_PROPERTY_ID, OPERATION_READ_ONLY_OWNER_PROPERTY_ID, OPERATION_NAME_PROPERTY_ID,OPERATION_ICON_PROPERTY_ID,OPERATION_DESCRIPTION_PROPERTY_ID,OPERATION_VIEW_NID_PROPERTY_ID,OPERATION_SEQUENCE_PROPERTY_ID,OPERATION_ROLE_PROPERTY_ID,OPERATION_DEAL_TYPE_PROPERTY_ID,OPERATION_TYPE_PROPERTY_ID, OPERATION_PDF_TEMPLATE_NID_PROPERTY_ID)));

/* ------------------------------
  | STORED PROCEDURE Settings    |
  -------------------------------*/
DEFINE('USE_STORED_PROCEDURE', FALSE);

/* -----------------------
  | Vantage Settings    |
  ------------------------ */
DEFINE('VANTAGE2K_OPERATION_NID', '455684');
DEFINE('VANTAGE4K_OPERATION_NID', '1659278');

DEFINE('ALLOW_SECTION_ARRAY', json_encode(array('Team Members','Operations','Requirements',PPC_SETTING, 'Control','Store')));

/* --------------------------------
  | Individual Settings            |
  --------------------------------- */
DEFINE('INDIVIDUAL_DEVICE_ID', '');
