<?php
ini_set("display_errors", 0);
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Content-Type");
if($_SERVER['HTTP_HOST'] == "localhost")
{
    /*DEFINE('BASE_URL_API', 'http://'.$_SERVER['HTTP_HOST'].'/pu/puidata/page_plugin/');
    DEFINE('WEB_API_URL', 'http://'.$_SERVER['HTTP_HOST'].'/pu/pui/');
    DEFINE('UPLOAD_URL_API', 'http://'.$_SERVER['HTTP_HOST'].'/pu/public/nodeZimg/');
    DEFINE('ABS_API_URL', 'http://'.$_SERVER['HTTP_HOST'].'/pu/');
    DEFINE('MAPPING_API_URL', 'http://'.$_SERVER['HTTP_HOST'].'/pu/puidata/marinemax_api/index.php');
    DEFINE('MARINEMAX_ABSO_URL_API',$_SERVER['DOCUMENT_ROOT'].'/pu/puidata/page_plugin/api_files/');*/
    $host       = 'http://'.$_SERVER['HTTP_HOST'].'/pu';
    $doc_root   = $_SERVER['DOCUMENT_ROOT'].'/pu';
}
else
{
    /*DEFINE('BASE_URL_API', 'http://'.$_SERVER['HTTP_HOST'].'/puidata/page_plugin/');
    DEFINE('WEB_API_URL', 'http://'.$_SERVER['HTTP_HOST'].'/pui/');
    DEFINE('UPLOAD_URL_API', 'http://'.$_SERVER['HTTP_HOST'].'/public/nodeZimg/');
    DEFINE('ABS_API_URL', 'http://'.$_SERVER['HTTP_HOST'].'/');
    DEFINE('MAPPING_API_URL', 'http://'.$_SERVER['HTTP_HOST'].'/puidata/marinemax_api/index.php');
    DEFINE('MARINEMAX_ABSO_URL_API',$_SERVER['DOCUMENT_ROOT'].'/puidata/page_plugin/api_files/');*/
    $host       = 'http://'.$_SERVER['HTTP_HOST'];
    $doc_root   = $_SERVER['DOCUMENT_ROOT'];

}

DEFINE('BASE_URL_API', $host.'/puidata/page_plugin/');
DEFINE('WEB_API_URL', $host.'/pui/');
DEFINE('UPLOAD_URL_API', $host.'/public/nodeZimg/');
DEFINE('ABS_API_URL', $host.'/');
DEFINE('MAPPING_API_URL', $host.'/puidata/marinemax_api/index.php');
DEFINE('MARINEMAX_ABSO_URL_API', $doc_root.'/puidata/page_plugin/api_files/');


DEFINE('MARINEMAX_API_URL', 'https://devintegrator.marinemax.com/rest/V1/');

DEFINE('FILE_DOMAIN', 'sta.pu.prospus.com');
DEFINE('MAPPING_DEAL_OPERATION_CLASS_ID', '724');
DEFINE('OPERATION_DOCUMENT_UPLOADED_CLASS_ID', '849');
DEFINE('MAPPING_ROLE_ACTOR_PID', '5026');
DEFINE('OPERATION_PID', '5027');
DEFINE('DOCUMENT_PID', '5028');
DEFINE('FORM_PID', '5029');
DEFINE('LAST_VISITED_OPERATION_PID', '7992');
DEFINE('DEAL_VIEW_ID', '660336');
define('OPERATION_PHASE_CLASS_ID', '781');
DEFINE('PHASE_CLASS_ID', '782');
DEFINE('PHASE_DEAL_P_ID', '6885');
DEFINE('PHASE_PHASE_P_ID', '6886');
DEFINE('PHASE_ROLE_P_ID', '6887');
DEFINE('PHASE_STATUS_P_ID', '6888');
DEFINE('COMPLETE_FUNDING_ID', '757734');
DEFINE('DEAL_PHASE_PROPERTY_ID', '7744');
DEFINE('DEAL_PHASE_VERSION_PROPERTY_ID', '7745');

DEFINE('DOCUMENT_TITLE', 'Document');
DEFINE('PDF_TITLE', 'PDF Template NID');
DEFINE('DEAL_CLASS_ID', '655');
DEFINE('OPERATION_CLASS_ID', '661');
DEFINE('ADD_DEAL_MENU_LIST_ID', '398431');
DEFINE('DELETE_DEAL_MENU_LIST_ID', '398440');
DEFINE('ROLE_SALES_CONSULTANT', '436104');  //Sales Consultant
DEFINE('ROLE_BUSINESS_MANAGER', '436099');  //Brokerage Consultant
DEFINE('ROLE_BM', '450187');                //Business manager
DEFINE('ROLE_TEAM_SUPPORT', '454669');      //TEAM SUPPORT
DEFINE('ROLE_SELLER', '454664');            //Seller
DEFINE('ROLE_BUYER', '454659');             //Buyer
DEFINE('ROLE_REVENUE_ACCOUNTANT', '454674');//Revenue Accoutant
DEFINE('ROLE_REVENUE_MANAGER', '454679');   //Revenue Manager
DEFINE('ROLE_CONTROLLER', '1462795');   //Controller
DEFINE('ROLE_DIRECTOR', '1462785');   //Director
DEFINE('DEAL_STATUS_PID','3287');
DEFINE('DEAL_SUB_STATUS_PID','8848');
DEFINE('MAPPING_ROLE_ACTOR_CLASS_ID', 663);

DEFINE('MANAGE_PHASE_SEQUENCE', '806');
DEFINE('CUSTOMER_CLASS_ID', '770');
DEFINE('UNIT_CLASS_ID', '776');
DEFINE('SALES_QUOTES_CLASS_ID', '790');
DEFINE('FINANCE_DEALS_CLASS_ID', '801');
DEFINE('CO_BUYER_CLASS_ID', '847');
DEFINE('ADMIN', '603696');
DEFINE('PHASEI','686864');
DEFINE('PHASEII','686869');
DEFINE('PHASEIII','686884');
DEFINE('PHASEIII','686884');
DEFINE('PHASE_SEQUENCE', '7689');
/***********Anil****************/
DEFINE('ON_HOLD_CLASS_ID', '859');

DEFINE('OPERATIONS_ROLES_CLASS_ID',662);
DEFINE('VISIBLE_ROLES_PROP_ID',7405);
DEFINE('REQUIRED_ROLES_PROP_ID',7406);
DEFINE('DEAL_PERMISSIONS_PROP_ID',7404);

$rolePhaseArray=  json_encode(array(ROLE_BM=>'686864',ROLE_REVENUE_ACCOUNTANT=>'686869',ROLE_REVENUE_MANAGER=>'686884'));
DEFINE('ROLE_NAME', json_encode(array(ROLE_SALES_CONSULTANT => 'Sales Consultant',ROLE_BM => 'Business Manager',ROLE_BUSINESS_MANAGER => 'Brokerage Consultant',ROLE_REVENUE_ACCOUNTANT => 'Revenue Accoutant')));

/* --------------------------------------------- */
DEFINE('CUSTOMER_CLASS_NID', '601263');
DEFINE('UNIT_CLASS_NID', '641371');
DEFINE('SALES_QUOTE_CLASS_NID', '793357');
DEFINE('FI_QUOTE_CLASS_NID', '796488');
DEFINE('COBUYER_CLASS_NID', '1130248');

DEFINE('MAPPING_ROLE_ACTOR_CLASS_ID', '663');
DEFINE('ROLE_PID', '3297');
DEFINE('ACTOR_PID','3298');
DEFINE('DEAL_PID','3299');

DEFINE('OPERATION_PROPERTY_MAP_DEAL_CLASS_ID', '787');
DEFINE('CUSTOMER_PID', '7202');
DEFINE('STOCK_PID','7203');
DEFINE('SALES_QUOTE_PID','7204');
DEFINE('FI_QUOTE_PID','7205');
DEFINE('COBUYER_PID','8452');

DEFINE('DEAL_CUSTOMER_PID', '3210');
DEFINE('DEAL_STOCK_PID','3216');
DEFINE('DEAL_SALES_QUOTE_PID','3227');
DEFINE('DEAL_FI_QUOTE_PID','3228');
DEFINE('DEAL_COBUYER_PID','8383');
DEFINE('PROPERTYID_OF_DEAL_ID','3208');
DEFINE('DEAL_CLASS_NODEID','396138');
DEFINE('DEAL_REJECTION','823');

DEFINE('STORE_CLASS_ID', 822);
DEFINE('STORE_LOCATION_PROPERTY_ID', 7988);
DEFINE('APPONE_UNSIGNED_PROPERTY_ID', 7211);
DEFINE('APPONE_OPERATION_CLASS_ID', 788);

DEFINE('DEAL_APPONE_CLASS_ID', 825);
DEFINE('DEAL_APPONE_APPID_PROPERTY_ID', 8029);
DEFINE('DEAL_APPONE_REQUEST_PROPERTY_ID', 8030);
DEFINE('DEAL_APPONE_RESPONSE_PROPERTY_ID', 8031);

DEFINE('DEAL_PAYMENT_TYPE_PROPERTY_ID', 3231);


//ADDED BY:- GAURAV DUTT PANCHAL
DEFINE('PROPERTYID_OF_REVIEW_ID','7986');// FOR PPC CLASS
DEFINE('PERFORMANCE_REVIEW_CLASS_NODEID','839021');//FOR PPC CLASS
DEFINE('PPC_SETTING','Employee Review');//FOR PPC CLASS

//For Setting NODEZ Astra API
DEFINE('NODEZ_DATASOURCE_SEARCH_ARRAY', json_encode(array('#nbsp#', '#,#', '#-#')));
DEFINE('NODEZ_DATASOURCE_REPLACE_ARRAY', json_encode(array(' ', ', ', '-')));


DEFINE('INDIVIDUAL_INSTANCE_NODE_ID', '1196249'); //'1142405'

DEFINE('OPERATION_ROLE_CLASS_ID', '662'); //'416174'
DEFINE('MANAGE_CONTROL_CLASS_ID', '853'); //'416174'
DEFINE('DEAL_CONTROL_VERSION_IDS',8450);
DEFINE('DEAL_NET_SALE_LIST',8747);
DEFINE('DEAL_SIZE',8748);


DEFINE('PASSED_DEAL_BY_ROLES_CLASS_ID',855);
DEFINE('PASSED_DEAL_BY_ROLES_CLASS_NID',1377982);
DEFINE('PASSED_DEAL_D_PID',8454);
DEFINE('PASSED_DEAL_FR_PID',8455);
DEFINE('PASSED_DEAL_TR_PID',8456);
DEFINE('PASSED_DEAL_A_PID',8457);
DEFINE('PASSED_DEAL_TIMESTAMP',8749);
DEFINE('DEAL_CREATOR_CLASS_ID',778);
DEFINE('DEAL_ON_HOLD_STATUS',3287);

DEFINE('DEAL_LOCATION_PID',6807);
DEFINE('LOCATION_ROLE_DETAILS', '858');

DEFINE('MENU_RAs', '1457918');
DEFINE('MENU_RMs','1457928');
DEFINE('MINE','1457938');
DEFINE('MENU_RM_C_D','1457948');
DEFINE('MENU_C_D','1457958');


DEFINE('DEAL_TIMESTAMP_PID', 8913);
DEFINE('DEAL_ASSIGNED_PID', 8914);

?>
