<div class="doc-file-pane">
    
    <h2>General</h2>
    
    <div class="file-pane">
        <div id="accordion" role="tablist" aria-multiselectable="true">
            <div>
                <div class="" role="tab" id="headingOne">
                    <h4>
                        <div class="doc-field">
                            <div class="form-group">
                                <label class="col-sm-2 label-field">Templates</label>
                                <div class="col-sm-8">
                                    <label>Document</label>
                                </div>
                                <div class="col-sm-2">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#general" aria-expanded="true" aria-controls="general" class="disabledField collapsed">
                                        <i class="fa fa-angle-down general-collapse"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </h4>
                </div>
                <div id="general" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                </div>
            </div>
        </div>
    </div>

    <div class="file-pane">
        <div class="form-group">
            <label class="col-sm-2 label-field">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control input-field" id="document_title" required="required" maxlength="50">
                <span class="char-limit"><span Class="charCount">0</span>/50 characters</span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 label-field">Location</label>
            <div class="col-sm-10">
                <label>Lorem.ipsum.doc.ipsum.foldername</label>
            </div>
        </div>
    </div>

<div class="file-pane">
    <table class="table table-style table-head table-doc">
        <thead>
            <tr>
                <th>Role</th>
                <th>Name</th>
                <th>View</th>
                <th>Edit</th>
                <th>Annotate</th>
                <th>Remove</th>
            </tr>
        </thead>    
    </table>
<div class="nano listedEntry">
<div class="nano-content">
<table class="table table-style table-doc ref-listed-user">
<tbody>
<tr>
<td>
<select class="select-field">
<option selected>Owner</option>
<option>Collaborator</option>
</select>
</td>
<td>
<div class="userName">
<i class="icon by-actor"></i>
<span>Lorem Ipsum</span>
</div>
</td>
<td>
<div class="checkbox disabledField">
<label><input type="checkbox" checked></label>
</div>
</td>
<td>
<div class="checkbox disabledField">
<label><input type="checkbox" checked></label>
</div>
</td>
<td>
<div class="checkbox disabledField">
<label><input type="checkbox" checked></label>
</div>
</td>
<td></td>
</tr>
<tr>
<td>
<select class="select-field">
<option>Owner</option>
<option selected>Collaborator</option>
</select>
</td>
<td>
<div class="userName">
<i class="icon sm-role"></i>
<span>Lorem Ipsum</span>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td><i class="icon close"></i></td>
</tr>
<tr>
<td>
<select class="select-field">
<option>Owner</option>
<option selected>Collaborator</option>
</select>
</td>
<td>
<div class="userName">
<i class="icon actor"></i>
<span>Lorem Ipsum</span>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td><i class="icon close"></i></td>
</tr>
<tr>
<td>
<select class="select-field">
<option>Owner</option>
<option selected>Collaborator</option>
</select>
</td>
<td>
<div class="userName">
<i class="icon sm-role"></i>
<span>Lorem Ipsum</span>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td>
<div class="checkbox">
<label><input type="checkbox"></label>
</div>
</td>
<td><i class="icon close"></i></td>
</tr>
<tr>
    <td>
        <select class="select-field">
        <option>Owner</option>
        <option selected>Collaborator</option>
        </select>
    </td>
    <td>
        <div class="userName">
        <i class="icon actor"></i>
        <span>Lorem Ipsum</span>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td><i class="icon close"></i></td>
</tr>
<tr>
    <td>
        <select class="select-field">
        <option>Owner</option>
        <option selected>Collaborator</option>
        </select>
    </td>
    <td>
        <div class="userName">
        <i class="icon sm-role"></i>
        <span>Lorem Ipsum</span>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td><i class="icon close"></i></td>
</tr>
<tr>
    <td>
        <select class="select-field">
        <option>Owner</option>
        <option selected>Collaborator</option>
        </select>
    </td>
    <td>
        <div class="userName">
        <i class="icon actor"></i>
        <span>Lorem Ipsum</span>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td>
        <div class="checkbox">
        <label><input type="checkbox"></label>
        </div>
    </td>
    <td><i class="icon close"></i></td>
</tr>

                                            </tbody>    
                                        </table>
                                    </div>
                                </div>
                           
                                <table class="table table-style table-doc table-footer">
                                    <tfoot>
                                        <tr>
                                            <td>
                                                <select class="select-field">
                                                    <option>Select</option>
                                                    <option>Owner</option>
                                                    <option selected>Collaborator</option>
                                                </select>
                                            </td>
                                            <td>
                                                <div class="Add-more-actor ref-addMore-user">
                                                <div class="option-wrap">
                                                <a id="dLabel" data-target="#" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                <i class="icon add-actor-icon"></i>
                                                </a>                     
                                                <ul class="dropdown-menu filter-drp" aria-labelledby="dLabel">
                                                <li><a><i class="icon sm-role"></i><span>By Role</span></a></li>
                                                <li><a><i class="icon by-actor"></i><span>By Actor</span></a></li>
                                                <li><a><i class="icon actor"></i><span>By Group</span></a></li>
                                                </ul>
                                                </div>
                                                <input type="text" class="form-control input-field" required="required">
                                                </div>
                                            </td>
                                            <td>
                                                <div class="checkbox">
                                                <label><input type="checkbox"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="checkbox">
                                                <label><input type="checkbox"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="checkbox">
                                                <label><input type="checkbox"></label>
                                                </div>
                                            </td>
                                            <td></td>
                                        </tr>
                                    </tfoot>    
                                </table>
                            </div>                                                   
                        </div> 

                        <div class="user-action-wrap action-file2" style="display:none;">
                            <a class="user-roles" onclick="createDocumentPanel()">
                                <i class="icon done" data-original-title="" title=""></i>
                                <br><span>Create</span>
                            </a>
                            <a class="user-roles" onclick="closeDocumentFlyout()">
                                <i class="icon cancel" data-original-title="" title=""></i>
                                <br><span>Close</span>
                            </a>
                        </div> 
                        <div class="user-action-wrap action-file1" style="display:none;">
                            <a class="user-roles ref-hideTollbar document-file-save-btn">
                                <i class="icon save" data-original-title="" title=""></i>
                                <br><span>Save</span>
                            </a>
                            <a class="user-roles ref-hideTollbar">
                                <i class="icon cancel" data-original-title="" title=""></i>
                                <br><span>Close</span>
                            </a>
                        </div> 
                 