<?php if($this->mode == 'Edit') { ?>
<div id="node-tab">             
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active nano" id="NodeX-tab">
        <ol class="class-wrapper table-list-view dual-pane-height nano-content">            
                <?php foreach($this->nodeClassX as $key => $nodeX) { ?>

                      <?php 
                            $caption2 = '';
                            if(intval($nodeX['encrypt_status']) == 1)
                            {
                                $caption2 =  $this->encryption_decryption('mc_decrypt',array('decrypt' =>$nodeX['caption'],'key' =>ENCRYPTION_KEY)); 
                            } 
                            else
                            {
                                $caption2 = $nodeX['caption'];
                            }
                        ?>

                    <li>
                        <div class="node-content clearfix">                            
                                 <div class="custom-checkbox nodeClass-X">                                      
                                 <input type="checkbox" id="<?php echo $nodeX['node_id']; ?>" value="<?php echo $nodeX['node_id']; ?>" name="nodeX[]">
                                 <label></label>    
                                </div>
                                <div class="node-left">
                                <div class="node-circle node-white-circle<?php if(count($nodeX['caption']) > 0) { ?>-expanded<?php } ?>">N</div>
                                <div class="node-head node-input"> 
                                    <span><?php echo $caption2; ?></span>
                                </div>
                            </div>
                        </div>
                        
                    </li>
                <?php } ?>
            
        </ol>
    </div>
    <div role="tabpanel" class="tab-pane" id="render-tab">render</div>
    <div role="tabpanel" class="tab-pane" id="node-modal-tab">node</div>
    <div role="tabpanel" class="tab-pane" id="prespective-tab">prespective</div>
  </div>

</div>
<?php } else { ?>
<div id="node-tab">             
  <!-- Tab panes -->
  <div class="tab-content">
                <div role="tabpanel" class="tab-pane active nodexdisplay nano" id="NodeX-tab">
                    <ol class="class-wrapper table-list-view dual-pane-height nano-content">                        
                        <?php 
                        
                        foreach($this->nodeClassX as $key => $nodeX) { ?>

                          <?php 
                            $caption3 = '';
                            if(intval($nodeX['encrypt_status']) == 1)
                            {
                                $caption3 =  $this->encryption_decryption('mc_decrypt',array('decrypt' =>$nodeX['caption'],'key' =>ENCRYPTION_KEY)); 
                            } 
                            else
                            {
                                $caption3 = $nodeX['caption'];
                            }
                          ?>

                                <li>
                                    <div class="node-content clearfix">
                                        <span class="sprite-icon tick-icon thirdnodeX-Panel" id="<?php echo $nodeX['node_id']; ?>"></span>
                                        <div class="node-left">                                            
                                            <div class="node-circle node-white-circle<?php if(count($nodeX['caption']) > 0) { ?>-expanded<?php } ?>">N</div> 
                                            <div class="node-head node-input"> 
                                                <span> <?php echo $caption3; ?></span>
                                               
                                            </div>
                                        </div>
                                    </div>
                                    
                                </li>
                            <?php } ?>
                        
                    </ol>
                </div>
               <!--  <div role="tabpanel" class="tab-pane" id="render-tab">render</div>
                <div role="tabpanel" class="tab-pane" id="node-modal-tab">node</div>
                <div role="tabpanel" class="tab-pane" id="prespective-tab">prespective</div> -->
              </div>

</div>
<?php } ?>
