<?php
$caption = "";
$countnumber = $this->countnumber;

$temp_count = array();

if(intval($this->classArray['encrypt_status']) == 1)
{
	$caption = $this->encryption_decryption('mc_decrypt',array('decrypt' =>$this->classArray['caption'],'key' =>ENCRYPTION_KEY)); 
} 
else
{
	$caption = $this->classArray['caption'];
}


function getProperty($propertyArray,$flag,$obj,$tempNumber) { ?>
	<?php foreach($propertyArray as $key => $value){
		$caption1 = "";		
		if(intval($value['encrypt_status']) == 1)
		{
			$caption2 = $obj->encryption_decryption('mc_decrypt',array('decrypt' =>$value['caption'],'key' =>ENCRYPTION_KEY)); 
		} 
		else
		{
			$caption2 = $value['caption'];
		}
		?>
		<li data-class="<?php echo $value['node_class_property_id']; ?>" class="calculate-position">
			<div class="node-content clearfix ">
				<span class="number_print1 property_id_<?php echo $value['node_class_property_id'].$tempNumber; ?>"></span>
				<script type="text/javascript">
					temp = parseInt($("#hidden_line_number").val()) + 1;
					$(".property_id_<?php echo $value['node_class_property_id'].$tempNumber; ?>").html(temp);
					$("#hidden_line_number").val(temp);
				</script>
				<div class="node-left">
					<div class="node-circle node-white-circle<?php if(count($value['child']) > 0){ ?>-expanded<?php } ?>">N</div>
					<div class="node-head node-input"> 
						<span class="sub-class-style"><?php echo $caption2; ?></span> 
					</div>
				</div>
			</div>
			<?php if(count($value['child']) > 0){ ?>
				<ol>
					<?php getProperty($value['child'],$flag,$obj,$tempNumber); ?>
				</ol>
			<?php } ?>
		</li>
	<?php }
} ?>



<?php if(count($this->classArray['instances']) > 0){ ?>

	<input type="hidden" id="hidden_line_number" value="<?php echo $countnumber;?>" />


	<ol class="class-structure-within-subclass">
		<?php 
		foreach($this->classArray['instances'] as $instance => $instanceArray){ ?>
			
			<?php if(count($instanceArray['property']) > 0){ $flag = 'Y'; ?>

				<?php foreach($instanceArray['property'] as $key => $value) { ?>
					<?php 
					$caption1 = "";		
					if(intval($value['encrypt_status']) == 1)
					{
						$caption1 = $obj->encryption_decryption('mc_decrypt',array('decrypt' =>$value['caption'],'key' =>ENCRYPTION_KEY)); 
					} 
					else
					{
						$caption1 = $value['caption'];
					}
					?>

					<li data-class="<?php echo $value['node_class_property_id']; ?>" class="calculate-position">
						<div class="node-content clearfix ">
							<span class="number_print1 property_id_<?php echo $countnumber.$value['node_class_property_id']; ?>"><?php //echo intval($countnumber) + 1;?></span>
							<script type="text/javascript">
								var tempnum = parseInt($("#hidden_line_number").val()) + 1;
								$(".property_id_<?php echo $countnumber.$value['node_class_property_id']; ?>").html(tempnum);
								$("#hidden_line_number").val(tempnum);
								
								/*temp = parseInt(<?php echo $countnumber;?>) + 1;
								$("#hidden_line_number").val(temp);*/
							</script>
							<div class="node-left">
								<div class="node-circle node-white-circle<?php if(count($value['child']) > 0){ ?>-expanded<?php } ?>">N</div>
								<div class="node-head node-input"> 
									<span class="sub-class-style"><?php echo $caption1; ?></span> 
								</div>
							</div>
						</div>								
					
						<?php if(count($value['child']) > 0) { ?>
							<ol>
								<?php getProperty($value['child'],$flag,$this,$countnumber); ?>
							</ol>
				        <?php } ?>
					</li>
				<?php $countnumber++;} ?>

			<?php } ?>
				
		<?php } ?>

		<ol class="sortable-list" id="sortable">
			<?php foreach($this->classArray['childsArray'] as $key => $val) { ?>
			    <li class="sub-class-list add-custom-hr-scroll-sub-class">
			    	<?php 
			    	if(trim($this->classArray['disable_expand'][$key]) != 'inactive'){
			    		$expand_function = 'getSubClassStructure('.$val['node_class_id'].','.$val['child_node_id'].',this, '.$this->classArray['number_print'][$key].')';
			    		$in_active_class = 'active';
			    		$in_active_style = 'style=""';
			    	}else{
			    		$expand_function = '';
			    		$in_active_class = 'inactive';
			    		$in_active_style = 'style="pointer-events:none"';
			    	} ?>
			    	<div class="node-content clearfix" onclick="<?php echo $expand_function; ?>">
						<span class="number_print1"><?php echo $this->classArray['number_print'][$key];?></span>
			    		<div class="node-left">
			    			<div class="node-circle node-white-circle-expanded">N</div>
			    			<div class="node-head node-input">
			    				<?php 
		    					$caption2 = '';
								if(intval($val['encrypt_status']) == 1)
								{
									$caption2 =  $this->encryption_decryption('mc_decrypt',array('decrypt' =>$val['caption'],'key' =>ENCRYPTION_KEY)); 
								} 
								else
								{
									$caption2 = $val['caption'];
								}
			    				?>
			    				<span class="sub-class-style"><input type="hidden" class="temp-sub-class-<?php echo $val['child_node_id'];?>"><?php echo strtoupper($caption2).' ('.$val['child_node_id'].')'; ?></span>
			    			</div>
			    		</div>
			    		
			    		<!--new-chevron-add-->
						<div class="node-right-sub clearfix">
							<a class="action-move act-mov-sub <?php echo $in_active_class;?>" <?php echo $in_active_style;?>><span><i class="fa fa-angle-up"></i></span></a>
						</div>
						<!--new-chvron-add-->
			    	</div>
			    </li>
			<?php } ?>
		</ol>
	</ol>
<?php } ?>