<div class="right-popup leftFlyout" id="courseTemplateFlyout" >
    <div class="course-flyout-wrap">
        <div class="courseflyout">
            <div class="control-bar">
                <div class="row">
                    <div class="col-md-12 left-head">
                        <div class="block-head block-rightHead">
                            <span class="main-title-wrap">
                                <span class="main-title">Courses</span>
                            </span>
                            <div class="control-btn-wrap right searchFlyout">
                                <form>
                                    <input class="form-control" placeholder="Search" type="text">
                                    <a href="#" class="searchFlyoutOpen"><i class="icon-sm search"></i></a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nano course-inner-wrap">
                <div class="nano-content">
                    <div class="production-list-pane">
                        <h3>Subscribed</h3>
                        <ol class="table-list-style all-users" id="courseTemplateFlyoutList">
                        </ol>
                    </div>
                    <div class="production-list-pane top-bdr">
                        <h3>Suggested courses</h3>
                        <ol class="table-list-style all-users">
                            <li>
                                <div class="left">
                                    <div class="node-content">
                                        <span class="app-icon"><img src="<?php echo PU_CDN_URL; ?>public/img/leave-application.png"></span>
                                        <span class="app-name">
                                            <span>Leave Application</span>
                                            <span class="sm-text">$25.00 / Month</span>
                                        </span>
                                        <span class="btn-box"><button class="btn btn-bdr-blue" type="button">Buy</button></span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="left">
                                    <div class="node-content">
                                        <span class="app-icon"><img src="<?php echo PU_CDN_URL; ?>public/img/Employee-Management.png"></span>
                                        <span class="app-name">
                                            <span>Employee Mangement</span>
                                            <span class="sm-text">$.99 / Usage</span>
                                        </span>
                                        <span class="btn-box"><button class="btn btn-bdr-blue" type="button">Buy</button></span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="left">
                                    <div class="node-content">
                                        <span class="app-icon"><img src="<?php echo PU_CDN_URL; ?>public/img/Employee-Exit.png"></span>
                                        <span class="app-name">
                                            <span>Employee Exit</span>
                                            <span class="sm-text">$199.00 / Year</span>
                                        </span>
                                        <span class="btn-box"><button class="btn btn-bdr-blue" type="button">Buy</button></span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="left">
                                    <div class="node-content">
                                        <span class="app-icon"><img src="<?php echo PU_CDN_URL; ?>public/img/Build-a-course.png"></span>
                                        <span class="app-name">
                                            <span><b>Build a Course</b></span>
                                        </span>
                                    </div>
                                </div>
                            </li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <div class="user-action-wrap">

            <a class="LeftFlyoutClose" id="courseTemplateFlyout"><i class="icon-sm close"></i><br><span>Close</span></a>
            <a id="helpNoderAnchor" href="javascript:void(0)" data-toggle="modal" data-target="#" data-direction="right" class="fixed-btm-icon strat_click1 helpnodeFlyout" strat-id="not_ajax" data-original-title="Help"><i class="icon-sm help" data-original-title="" title=""></i><br><span>Help</span></a>
        </div>
    </div>
</div>