<table class="fixed-left-column" border="" style="border-collapse: collapse; border:0px; background-color:#FFF; border-color:#d5d5d5; color:#999">
    <tbody>
        <tr class="row-0">
            <td class="ExcelTableFormationRow">
                <div class="left-col"></div>
            </td>
            <td class="ExcelTableFormationCol col-1 collapse"><span class="top-col">1</span></td>
            <td class="ExcelTableFormationCol col-2 collapse event"><span class="top-col">2</span></td>
            <td class="ExcelTableFormationCol col-3 "><span class="top-col">3</span></td>
            <td class="ExcelTableFormationCol col-4 collapse event  "><span class="top-col">4</span></td>
            <td class="ExcelTableFormationCol col-5"><span class="top-col">5</span></td>
            <td class="ExcelTableFormationCol col-6 collapse  event  "><span class="top-col">6</span></td>
            <td class="ExcelTableFormationCol col-7"><span class="top-col">7</span></td>
            <td class="ExcelTableFormationCol col-8 collapse  event"><span class="top-col">8</span></td>
            <td class="ExcelTableFormationCol col-9"><span class="top-col">9</span></td>
            
        </tr>
        <tr class="row-1">
            <td class="ExcelTableFormationRow">
                <div class="left-col">1</div>
            </td>
            <td class="ExcelTablerow col-1 collapse">
                <div data-id="1" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon time-icon"></span><span class="col-head-title">Timeline</span><i class="fa fa-caret-left arrow rotate"></i> 
                </div>
            </td>
            <td class="ExcelTablerow collapse event col-2">
                <div data-id="2" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> 
                </div>
            </td>
            <td class="col-3 ">
                <div data-id="3" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon process-icon"></span><span class="col-head-title">Process</span><i class="fa fa-caret-left arrow"></i> 
                </div>
            </td>
            <td class="ExcelTablerow col-4  collapse event">
                <div data-id="4" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon event-icon"></span><span class="col-head-title">.Event</span></span><i class="fa fa-caret-left arrow rotate"></i> 
                </div>
            </td>
            <td class=" col-5 ">
                <div data-id="5" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon phase-icon"></span><span class="col-head-title">Phase</span><i class="fa fa-caret-left arrow"></i> 
                </div>
            </td>
            <td class="ExcelTablerow col-6  collapse event">
                <div data-id="6" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> 
                </div>
            </td>
            <td class="col-7 ">
                <div data-id="7" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon operation-icon"></span><span class="col-head-title">Operation</span><i class="fa fa-caret-left arrow"></i> 
                </div>
            </td>
            <td class="ExcelTablerow  col-8 event collapse">
                <div data-id="8" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon event-icon"></span><span class="col-head-title">.Event</span><i class="fa fa-caret-left arrow rotate"></i> 
                </div>
            </td>
            <td class="col-9 ">
                <div data-id="9" class="col-head">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="icon role-icon"></span><span class="col-head-title">Role</span><i class="fa fa-caret-left arrow"></i> 
                </div>
            </td>
            
        </tr>
        <tr class="row-2">
            <td class="ExcelTableFormationRow">
                <div class="left-col">2</div>
            </td>
            <td class="ExcelTablerow col-1 collapse merge-td">
                <div class="">
                    <div class="time-col">
                        <span class="doted-border"></span>
                        <div class="node-circle node-white-sm-circle">N</div>
                        <span class="col-text"> 
                        <span class="col-node-text custom-node"></span>
                        </span> 
                        <span class="table-count" data-id="1">1</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-2  collapse event border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <span class="col-text"> <span class="creation"></span> 
                    <span class="col-node-text custom-node">Creation</span>
                    <span class="table-count" data-id="2">2</span>
                    </span>
                </div>
            </td>
            <td class="ExcelTablerow col-3   merge-td">
                <div class="segment-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text">
                        <span class="col-node-text custom-node" placeholder = "Perspective">Perspective</span>
                        <span class="table-count" data-id="3">3</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-4  collapse event border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="creation"></span> 
                        <span class="col-node-text custom-node">Creation</span>
                        <span class="table-count" data-id="4">4</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow  col-5 merge-td">
                <div class="segment-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text custom-node" placeholder ="Manifestation" >Manifestation</span>
                        <span class="table-count" data-id="5">5</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-6  collapse event border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="creation"></span> 
                        <span class="col-node-text custom-node">Creation</span> 
                        <span class="table-count" data-id="6">6</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-7  merge-td">
                <div class="segment-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text custom-node col-node-Actor-Perspective" placeholder ="Identify Actor" >Identify Actor</span>
                        <span class="table-count" data-id="7">7</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-8 collapse event border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="creation"></span> 
                        <span class="col-node-text custom-node">Creation</span> 
                        <span class="table-count" data-id="8">8</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-9  merge-td creation-bg">
                <div class="blank-div segment-node"></div>
            </td>
           
        </tr>
        <tr class="row-3">
            <td class="ExcelTableFormationRow">
                <div class="left-col">3</div>
            </td>
            <td class="ExcelTablerow col-1 collapse merge-td ">
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow col-2  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-3 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-4 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-5 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-6  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-7  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-8 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-9 border-light-top border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text custom-node col-node-Actor-Perspective" placeholder = "ACTOR.Identify()" >ACTOR.Identify()</span>
                        <span class="table-count" data-id="9">9</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-10"></td>
        </tr>
        <tr class="row-4">
            <td class="ExcelTableFormationRow">
                <div class="left-col">4</div>
            </td>
            <td class="ExcelTablerow col-1 collapse merge-td ">
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow col-2  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-3 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-4  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-5  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-6  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-7  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-8 collapse event border-light-top border-light-bottom ">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="destructure"></span> 
                        <span class="col-node-text custom-node">Destruction</span> 
                        <span class="table-count"data-id="10">10</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-9   creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
             
        </tr>
        <tr class="row-5">
            <td class="ExcelTableFormationRow">
                <div class="left-col">5</div>
            </td>
            <td class="ExcelTablerow collapse merge-td col-1">
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow col-2  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-3 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-4  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-5  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-6 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-7  border-light-top merge-td">
                <div class="segment-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text custom-node col-node-Actor-Perspective" placeholder ="Update Actor">Update Actor</span>
                        <span class="table-count" data-id="11">11</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-8 collapse event border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="creation"></span> 
                        <span class="col-node-text custom-node">Creation</span> 
                        <span class="table-count" data-id="12">12</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-9  merge-td creation-bg">
                <div class="blank-div segment-node"></div>
            </td>
             
        </tr>
        <tr class="row-6">
            <td class="ExcelTableFormationRow">
                <div class="left-col">6</div>
            </td>
            <td class="ExcelTablerow  collapse merge-td col-1 ">
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow col-2  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-3  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-4  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-5  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-6  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-7  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-8 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-9  border-light-top border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text custom-node col-node-Actor-Perspective" placeholder = "ACTOR.Update()" >ACTOR.Update()</span>
                        <span class="table-count" data-id="13">13</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-10"></td>
        </tr>
        <tr class="row-7">
            <td class="ExcelTableFormationRow">
                <div class="left-col">7</div>
            </td>
            <td class="ExcelTablerow collapse merge-td col-1 ">
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow  col-2 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-3  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-4  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-5  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-6 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-7 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-8 collapse event border-light-top border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="destructure"></span> 
                        <span class="col-node-text custom-node">Destruction</span> 
                        <span class="table-count" data-id="14">14</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-9  creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
             
        </tr>
        <tr class="row-8">
            <td class="ExcelTableFormationRow">
                <div class="left-col">8</div>
            </td>
            <td class="ExcelTablerow collapse merge-td col-1">
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow   collapse event creation-bg merge-td col-2">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-3 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-4  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-5  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow   col-6 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
         
            <td class="ExcelTablerow  col-7 border-light-top  merge-td">
                <div class="segment-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text custom-node col-node-Actor-Perspective" placeholder = "Generate Perspective">Generate Perspective</span>
                        <span class="table-count" data-id="15">15</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-8 collapse event border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="creation"></span> 
                        <span class="col-node-text custom-node">Creation</span> 
                        <span class="table-count" data-id="16">16</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow  col-9 event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
             
        </tr>
        <tr class="row-9">
            <td class="ExcelTableFormationRow">
                <div class="left-col">11</div>
            </td>
            <td class="ExcelTablerow  collapse merge-td col-1 " >
                <div class="blank-div segment-node borderDashed"></div>
            </td>
            <td class="ExcelTablerow col-2  collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-3  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-4 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-5 merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-6 collapse event creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-7  merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-8  event collapse creation-bg merge-td">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-9 event border-light-top border-light-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text segment-text operation-text"> 
                        <span class="col-node-text col-node-Actor-Perspective custom-node" title="ACTOR.PERSPECTIVE.Generate()" placeholder="ACTOR.PERSPECTIVE." > ACTOR.PERSPECTIVE.</span>
                        <span class="table-count" data-id="17">17</span>
                    </div>
                </div>
            </td>
             
        </tr>
        <tr class="row-10">
            <td class="ExcelTableFormationRow  border-bottom">
                <div class="left-col">13</div>
            </td>
            <td class="ExcelTablerow  col-1 collapse merge-td border-bottom">
                <div class="time-col">
                    <div class="node-circle node-white-sm-circle">N</div>
                    <div class="borderDashed last-borderDashed"></div>
                    <span class="col-text"> </span> 
                </div>
            </td>
            <td class="ExcelTablerow  col-2 collapse event border-light-top  border-bottom">
                <div class="lastRow creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="destructure"></span> 
                        <span class="col-node-text custom-node">Destruction</span> 
                        <span class="table-count" data-id="21">21</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-3  border-bottom">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow col-4  collapse event border-light-top  border-bottom">
                <div class="lastRow creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="destructure"></span> 
                        <span class="col-node-text custom-node">Destruction</span> 
                        <span class="table-count" data-id="20">20</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-5  border-bottom">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-6 collapse event border-light-top  border-bottom">
                <div class="lastRow creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="destructure"></span> 
                        <span class="col-node-text custom-node">Destruction</span> 
                        <span class="table-count" data-id="19">19</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow col-7 border-bottom">
                <div class="blank-div segment-node"></div>
            </td>
            <td class="ExcelTablerow  col-8  collapse event border-light-top  border-bottom">
                <div class="creation-node">
                    <div class="node-circle node-white-circle node-white-circle">N</div>
                    <div class="col-text"> <span class="destructure"></span> 
                        <span class="col-node-text custom-node">Destruction</span> 
                        <span class="table-count" data-id="18">18</span>
                    </div>
                </div>
            </td>
            <td class="ExcelTablerow  col-9  creation-bg merge-td border-bottom" >
                <div class="blank-div segment-node"></div>
            </td>
            
        </tr>
    </tbody>
</table>