<div class="total-width-pane slide-wrap active " >
    <div class="listing-wrapper dashSlider clearfix set-height active activeWrap">
        <div class="control-bar">
            <div class="row">
                <div class="col-md-12 left-head">
                    <div class="block-head">
                        <span class="main-title-wrap">
                            <span class="main-title left-side-heading">Contact : List</span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-one-third">
            <table class="table table-style table-responsive table-head ActiveRow actor-table">
                <thead>
                    <th class="filterDrp">
                        <span>First Name<i class="fa fa-angle-down"></i></span>
                        <ul aria-labelledby="dLabel" role="menu" class="dropdown-menu multi-menu">
                            <li >Sort by ascending</li>
                            <li>Sort by descending</li>
                            <li class="parent-item">Text Filters <i class="fa fa-angle-right"></i>
                                <ul class="multi-sub-menu dropdown-menu">
                                    <li>Equals To</li>
                                    <li>Not Equals To</li>
                                    <li>Begins With</li>
                                    <li>Ends With</li>
                                    <li>Contains</li>
                                    <li>Does Not Contain</li>
                                </ul>
                            </li>
                            <div class="search-item-wrap">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search" data-value="entr-actor-name">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default search-button-box entr-actor-name" type="button"></button>
                                    </span>
                                </div>
                            </div>
                        </ul>
                    </th>
                    <th class="filterDrp">
                        <span>Last Name<i class="fa fa-angle-down"></i></span>
                        <ul aria-labelledby="dLabel" role="menu" class="dropdown-menu multi-menu">
                            <li >Sort by ascending</li>
                            <li>Sort by descending</li>
                           
                        </ul>
                    </th>
                    <th class="filterDrp">
                        <span>Email Id<i class="fa fa-angle-down"></i></span>
                        <ul aria-labelledby="dLabel" role="menu" class="dropdown-menu multi-menu">
                            <li >Sort by ascending</li>
                            <li>Sort by descending</li>
                           
                        </ul>
                    </th>
                    <th class="filterDrp">
                        <span>Role<i class="fa fa-angle-down"></i></span>
                        <ul aria-labelledby="dLabel" role="menu" class="dropdown-menu multi-menu">
                            <li>All</li>
                            <li>Draft</li>
                            <li>Published</li>
                           
                        </ul>
                    </th>
                </thead>
            </table>
            <div class="nano fixedTableHig">
                <div class="nano-content">
                    <table class="table table-style table-responsive actor-table ActiveRow "> 
                        <tbody> 
                        <tr class="current">
                            <td>Loremipsum</td>
                            <td>Loremipsum</td>
                            <td>Loremipsum@prospus.com</td>
                            <td>Draft</td> 
                        </tr> 
                        <?php
                        for ($i = 1; $i <= 10; $i++) {  ?>     
                            <tr>
                                <td>Loremipsum</td>
                                <td>Loremipsum</td>
                                <td>Loremipsum@prospus.com</td>
                                <td>Draft</td> 
                            </tr>
                            <tr>
                                <td>dummytest</td>
                                <td>Loremipsum</td>
                                <td>dummytest@prospus.com</td>
                                <td>Published</td> 
                            </tr>
                      <?php  } 
                        ?>
                        </tbody>
                    </table> 
                </div>
            </div>
        </div>
    </div>
    
    <div class="display-wrapper dashSlider clearfix set-height active">
        <div class="control-bar">
            <div class="row">
                <div class="col-md-12 left-head">
                    <div class="block-head">
                        <span class="main-title-wrap">
                            <span class="main-title left-side-heading">Account : Details</span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="nano">
            <div class="nano-content HalfPaneHeight ">
                <div class="accountViewMode account-detail-mode">
                    <div class="">
                        <h6>General</h6>
                        <div class="">
                            <form class="form-horizontal">          
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">First Name</label>
                                    <div class="col-sm-9">
                                        <span>Lorem</span>
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">Last Name</label>
                                    <div class="col-sm-9">
                                        <span>Ipsum</span>
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">Email Id</label>
                                    <div class="col-sm-9">
                                        <span>lorem.ipsum@prospus.com</span>
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">Role</label>
                                    <div class="col-sm-9">
                                        <span>Published</span>
                                    </div>
                                </div>                                
                            </form>
                        </div>
                    </div>
                </div>                           
                
                <div class="accountEditMode account-detail-mode hide">
                    <div class="">
                        <h6>General</h6>
                        <div class="">
                            <form class="form-horizontal">          
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">First Name</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control input-field" placeholder="">
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">Last Name</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control input-field" placeholder="">
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">Email Id</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control input-field" placeholder="">
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 label-field">Role</label>
                                    <div class="col-sm-9">
                                        <div class="select-wrap">
                                            <select class="select-field">
                                                <option value="All">All</option>
                                                <option value="Draft">Draft</option>
                                                <option value="Published" selected>Published</option>
                                            </select>
                                        </div>
                                        
                                    </div>
                                </div>                                
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</div>
